// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

use std::sync::Arc;

use async_trait::async_trait;

/// Operations implemented by the local Application role.
#[async_trait]
pub trait ApplicationHandler: Send + Sync {
    async fn ping(
        &self,
        context: crate::HandlerContext,
        request: PingRequest,
    ) -> Result<PingResponse, crate::Error>;
    async fn session_initialize(
        &self,
        context: crate::HandlerContext,
        request: SessionInitializeRequest,
    ) -> Result<SessionInitializeResponse, crate::Error>;
    async fn session_terminate(
        &self,
        context: crate::HandlerContext,
        request: SessionTerminateRequest,
    ) -> Result<EmptyResponse, crate::Error>;
}

#[doc(hidden)]
pub const APPLICATION_HANDLER_METHODS: &[&str] = &[
    METHOD_PING,
    METHOD_SESSION_INITIALIZE,
    METHOD_SESSION_TERMINATE,
];

/// Convert a role implementation into runtime request registrations.
pub fn application_handlers(handler: Arc<dyn ApplicationHandler>) -> Vec<crate::RequestRegistration> {
    let mut registrations = Vec::new();
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<PingRequest, PingResponse, _, _>(
            METHOD_PING,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.ping(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<SessionInitializeRequest, SessionInitializeResponse, _, _>(
            METHOD_SESSION_INITIALIZE,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.session_initialize(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<SessionTerminateRequest, EmptyResponse, _, _>(
            METHOD_SESSION_TERMINATE,
            true,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.session_terminate(context, request).await }
            },
        ));
    }
    drop(handler);
    registrations
}

/// Operations implemented by the local Voice role.
#[async_trait]
pub trait VoiceHandler: Send + Sync {
    async fn application_move(
        &self,
        context: crate::HandlerContext,
        request: ApplicationMoveRequest,
    ) -> Result<ApplicationMoveResponse, crate::Error>;
    async fn audio_buffer_clear(
        &self,
        context: crate::HandlerContext,
        request: AudioBufferClearRequest,
    ) -> Result<AudioBufferClearResponse, crate::Error>;
    async fn call_hangup(
        &self,
        context: crate::HandlerContext,
        request: CallHangupRequest,
    ) -> Result<EmptyResponse, crate::Error>;
    async fn ping(
        &self,
        context: crate::HandlerContext,
        request: PingRequest,
    ) -> Result<PingResponse, crate::Error>;
    async fn recording_start(
        &self,
        context: crate::HandlerContext,
        request: RecordingStartRequest,
    ) -> Result<RecordingStartResponse, crate::Error>;
    async fn recording_stop(
        &self,
        context: crate::HandlerContext,
        request: RecordingStopRequest,
    ) -> Result<EmptyResponse, crate::Error>;
    async fn session_get(
        &self,
        context: crate::HandlerContext,
        request: SessionGetRequest,
    ) -> Result<SessionGetResponse, crate::Error>;
    async fn session_set(
        &self,
        context: crate::HandlerContext,
        request: SessionSetRequest,
    ) -> Result<EmptyResponse, crate::Error>;
}

#[doc(hidden)]
pub const VOICE_HANDLER_METHODS: &[&str] = &[
    METHOD_APPLICATION_MOVE,
    METHOD_AUDIO_BUFFER_CLEAR,
    METHOD_CALL_HANGUP,
    METHOD_PING,
    METHOD_RECORDING_START,
    METHOD_RECORDING_STOP,
    METHOD_SESSION_GET,
    METHOD_SESSION_SET,
    METHOD_SESSION_TERMINATE,
];

/// Convert a role implementation into runtime request registrations.
pub fn voice_handlers(handler: Arc<dyn VoiceHandler>) -> Vec<crate::RequestRegistration> {
    let mut registrations = Vec::new();
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<ApplicationMoveRequest, ApplicationMoveResponse, _, _>(
            METHOD_APPLICATION_MOVE,
            true,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.application_move(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<AudioBufferClearRequest, AudioBufferClearResponse, _, _>(
            METHOD_AUDIO_BUFFER_CLEAR,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.audio_buffer_clear(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<CallHangupRequest, EmptyResponse, _, _>(
            METHOD_CALL_HANGUP,
            true,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.call_hangup(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<PingRequest, PingResponse, _, _>(
            METHOD_PING,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.ping(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<RecordingStartRequest, RecordingStartResponse, _, _>(
            METHOD_RECORDING_START,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.recording_start(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<RecordingStopRequest, EmptyResponse, _, _>(
            METHOD_RECORDING_STOP,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.recording_stop(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<SessionGetRequest, SessionGetResponse, _, _>(
            METHOD_SESSION_GET,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.session_get(context, request).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<SessionSetRequest, EmptyResponse, _, _>(
            METHOD_SESSION_SET,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.session_set(context, request).await }
            },
        ));
    }
    registrations.push(crate::RequestRegistration::rejection(
        METHOD_SESSION_TERMINATE,
        crate::WireError { code: 501, message: "session.terminate is not supported. please use application.move or call.hangup instead".to_owned(), data: None },
    ));
    drop(handler);
    registrations
}

/// Typed client for operations implemented by a peer in the Application role.
pub struct ApplicationPeer<R> {
    requester: R,
}

impl<R> ApplicationPeer<R> {
    #[must_use]
    pub const fn new(requester: R) -> Self { Self { requester } }

    /// Return the underlying raw requester.
    pub fn into_inner(self) -> R { self.requester }
}

impl<R: crate::Requester> ApplicationPeer<R> {
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn ping(&self, request: PingRequest) -> Result<PingResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn session_initialize(&self, request: SessionInitializeRequest) -> Result<SessionInitializeResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn session_terminate(&self, request: SessionTerminateRequest) -> Result<EmptyResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
}

/// Typed client for operations implemented by a peer in the Voice role.
pub struct VoicePeer<R> {
    requester: R,
}

impl<R> VoicePeer<R> {
    #[must_use]
    pub const fn new(requester: R) -> Self { Self { requester } }

    /// Return the underlying raw requester.
    pub fn into_inner(self) -> R { self.requester }
}

impl<R: crate::Requester> VoicePeer<R> {
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn application_move(&self, request: ApplicationMoveRequest) -> Result<ApplicationMoveResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn audio_buffer_clear(&self, request: AudioBufferClearRequest) -> Result<AudioBufferClearResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn call_hangup(&self, request: CallHangupRequest) -> Result<EmptyResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn ping(&self, request: PingRequest) -> Result<PingResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn recording_start(&self, request: RecordingStartRequest) -> Result<RecordingStartResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn recording_stop(&self, request: RecordingStopRequest) -> Result<EmptyResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn session_get(&self, request: SessionGetRequest) -> Result<SessionGetResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn session_set(&self, request: SessionSetRequest) -> Result<EmptyResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
}

/// Typed emitter for events owned by the Application role.
pub struct ApplicationEvents<N> {
    notifier: N,
}

impl<N> ApplicationEvents<N> {
    #[must_use]
    pub const fn new(notifier: N) -> Self { Self { notifier } }

    /// Return the underlying raw notifier.
    pub fn into_inner(self) -> N { self.notifier }
}

impl<N: crate::Notifier> ApplicationEvents<N> {
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn agent_tool_call(&self, event: AgentToolCallEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn audio_speech_started(&self, event: AudioSpeechStartedEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn input_transcript(&self, event: InputTranscriptEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn output_transcript_delta(&self, event: OutputTranscriptDeltaEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn output_transcript_done(&self, event: OutputTranscriptDoneEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
}

/// Typed emitter for events owned by the Voice role.
pub struct VoiceEvents<N> {
    notifier: N,
}

impl<N> VoiceEvents<N> {
    #[must_use]
    pub const fn new(notifier: N) -> Self { Self { notifier } }

    /// Return the underlying raw notifier.
    pub fn into_inner(self) -> N { self.notifier }
}

impl<N: crate::Notifier> VoiceEvents<N> {
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn audio_info(&self, event: AudioInfoEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn call_hangup(&self, event: CallHangupEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn dtmf(&self, event: DtmfEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn session_updated(&self, event: SessionUpdatedEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
}

/// Peer events received by the local Application role.
#[async_trait]
pub trait ApplicationEventHandler: Send + Sync {
    async fn audio_info(
        &self,
        context: crate::HandlerContext,
        event: AudioInfoEvent,
    ) -> Result<(), crate::Error>;
    async fn call_hangup(
        &self,
        context: crate::HandlerContext,
        event: CallHangupEvent,
    ) -> Result<(), crate::Error>;
    async fn dtmf(
        &self,
        context: crate::HandlerContext,
        event: DtmfEvent,
    ) -> Result<(), crate::Error>;
    async fn session_updated(
        &self,
        context: crate::HandlerContext,
        event: SessionUpdatedEvent,
    ) -> Result<(), crate::Error>;
}

/// Convert a role event implementation into runtime event registrations.
pub fn application_event_handlers(handler: Arc<dyn ApplicationEventHandler>) -> Vec<crate::EventRegistration> {
    let mut registrations = Vec::new();
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<AudioInfoEvent, _, _>(
            EVENT_AUDIO_INFO,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.audio_info(context, event).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<CallHangupEvent, _, _>(
            EVENT_CALL_HANGUP,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.call_hangup(context, event).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<DtmfEvent, _, _>(
            EVENT_DTMF,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.dtmf(context, event).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<SessionUpdatedEvent, _, _>(
            EVENT_SESSION_UPDATED,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.session_updated(context, event).await }
            },
        ));
    }
    drop(handler);
    registrations
}

/// Peer events received by the local Voice role.
#[async_trait]
pub trait VoiceEventHandler: Send + Sync {
    async fn agent_tool_call(
        &self,
        context: crate::HandlerContext,
        event: AgentToolCallEvent,
    ) -> Result<(), crate::Error>;
    async fn audio_speech_started(
        &self,
        context: crate::HandlerContext,
        event: AudioSpeechStartedEvent,
    ) -> Result<(), crate::Error>;
    async fn input_transcript(
        &self,
        context: crate::HandlerContext,
        event: InputTranscriptEvent,
    ) -> Result<(), crate::Error>;
    async fn output_transcript_delta(
        &self,
        context: crate::HandlerContext,
        event: OutputTranscriptDeltaEvent,
    ) -> Result<(), crate::Error>;
    async fn output_transcript_done(
        &self,
        context: crate::HandlerContext,
        event: OutputTranscriptDoneEvent,
    ) -> Result<(), crate::Error>;
}

/// Convert a role event implementation into runtime event registrations.
pub fn voice_event_handlers(handler: Arc<dyn VoiceEventHandler>) -> Vec<crate::EventRegistration> {
    let mut registrations = Vec::new();
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<AgentToolCallEvent, _, _>(
            EVENT_AGENT_TOOL_CALL,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.agent_tool_call(context, event).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<AudioSpeechStartedEvent, _, _>(
            EVENT_AUDIO_SPEECH_STARTED,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.audio_speech_started(context, event).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<InputTranscriptEvent, _, _>(
            EVENT_INPUT_TRANSCRIPT,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.input_transcript(context, event).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<OutputTranscriptDeltaEvent, _, _>(
            EVENT_OUTPUT_TRANSCRIPT_DELTA,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.output_transcript_delta(context, event).await }
            },
        ));
    }
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<OutputTranscriptDoneEvent, _, _>(
            EVENT_OUTPUT_TRANSCRIPT_DONE,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.output_transcript_done(context, event).await }
            },
        ));
    }
    drop(handler);
    registrations
}
