// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

use super::*;
use serde::{de::DeserializeOwned, Serialize};

fn assert_round_trip<T>(name: &str, golden: &str)
where
    T: DeserializeOwned + Serialize,
{
    let value: T = serde_json::from_str(golden).unwrap_or_else(|error| panic!("{name}: {error}"));
    let actual = serde_json::to_string(&value).unwrap();
    assert_eq!(actual, golden, "{name}");
}

#[test]
#[allow(clippy::manual_string_new, clippy::too_many_lines, clippy::unreadable_literal)]
fn generated_golden_payloads_round_trip_exact_bytes() {
    assert_round_trip::<AgentToolCallEvent>("events/agent.tool.call.json/round_trip", "{\"name\":\"lookup_order\"}");
    {
        let constructed = AgentToolCallEvent { name: "lookup_order".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"name\":\"lookup_order\"}", "events/agent.tool.call.json/construct");
    }
    assert_round_trip::<AudioInfoEvent>("events/audio.info.json/round_trip", "{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}");
    {
        let constructed = AudioInfoEvent { read: AudioInfoItem { bytes: 0, bytes_per_second: 0.0, bytes_total: 0 }, write: AudioInfoItem { bytes: 0, bytes_per_second: 0.0, bytes_total: 0 } };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}", "events/audio.info.json/construct");
    }
    assert_round_trip::<AudioSpeechStartedEvent>("events/audio.speech.started.json/round_trip", "{\"origin\":\"sender\"}");
    {
        let constructed = AudioSpeechStartedEvent { origin: "sender".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"origin\":\"sender\"}", "events/audio.speech.started.json/construct");
    }
    assert_round_trip::<CallHangupEvent>("events/call.hangup.json/round_trip", "{\"reason\":\"caller\"}");
    {
        let constructed = CallHangupEvent { reason: Some("caller".to_owned()) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"reason\":\"caller\"}", "events/call.hangup.json/construct");
    }
    assert_round_trip::<DtmfEvent>("events/dtmf.json/round_trip", "{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}");
    {
        let constructed = DtmfEvent { seq: 7, pressed_at: 1700000000000, released_at: 1700000000120, digit: "5".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}", "events/dtmf.json/construct");
    }
    assert_round_trip::<InputTranscriptEvent>("events/input.transcript.json/round_trip", "{\"delta\":\"hello there\"}");
    {
        let constructed = InputTranscriptEvent { delta: "hello there".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"delta\":\"hello there\"}", "events/input.transcript.json/construct");
    }
    assert_round_trip::<OutputTranscriptDeltaEvent>("events/output.transcript.delta.json/round_trip", "{\"delta\":\"Hi \"}");
    {
        let constructed = OutputTranscriptDeltaEvent { delta: "Hi ".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"delta\":\"Hi \"}", "events/output.transcript.delta.json/construct");
    }
    assert_round_trip::<OutputTranscriptDoneEvent>("events/output.transcript.done.json/round_trip", "{}");
    {
        let constructed = OutputTranscriptDoneEvent { text: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "events/output.transcript.done.json/construct");
    }
    assert_round_trip::<SessionUpdatedEvent>("events/session.updated.json/round_trip", "{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}");
    {
        let constructed = SessionUpdatedEvent { audio_codec: Some(AudioCodec { id: "L16/8000/1".to_owned(), name: "L16".to_owned(), sample_rate: 8000, bit_depth: 16, channels: 1 }) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}", "events/session.updated.json/construct");
    }
    assert_round_trip::<ApplicationMoveRequest>("payloads/application.move.request.json/round_trip", "{\"reason\":\"handoff\",\"application_id\":\"app-2\"}");
    {
        let constructed = ApplicationMoveRequest { reason: Some("handoff".to_owned()), application_id: Some("app-2".to_owned()) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"reason\":\"handoff\",\"application_id\":\"app-2\"}", "payloads/application.move.request.json/construct");
    }
    assert_round_trip::<ApplicationMoveResponse>("payloads/application.move.response.json/round_trip", "{\"next_application_id\":\"app-2\"}");
    {
        let constructed = ApplicationMoveResponse { next_application_id: Some("app-2".to_owned()) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"next_application_id\":\"app-2\"}", "payloads/application.move.response.json/construct");
    }
    assert_round_trip::<AudioBufferClearRequest>("payloads/audio.buffer.clear.request.json/round_trip", "{}");
    {
        let constructed = AudioBufferClearRequest(serde_json::Map::from_iter([]));
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "payloads/audio.buffer.clear.request.json/construct");
    }
    assert_round_trip::<AudioBufferClearResponse>("payloads/audio.buffer.clear.response.json/round_trip", "{\"len\":320}");
    {
        let constructed = AudioBufferClearResponse { len: 320 };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"len\":320}", "payloads/audio.buffer.clear.response.json/construct");
    }
    assert_round_trip::<CallHangupRequest>("payloads/call.hangup.request.json/round_trip", "{\"reason\":\"caller\"}");
    {
        let constructed = CallHangupRequest { reason: "caller".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"reason\":\"caller\"}", "payloads/call.hangup.request.json/construct");
    }
    assert_round_trip::<EmptyResponse>("payloads/call.hangup.response.json/round_trip", "{}");
    {
        let constructed = EmptyResponse(serde_json::Map::from_iter([]));
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "payloads/call.hangup.response.json/construct");
    }
    assert_round_trip::<PingRequest>("payloads/ping.request.json/round_trip", "{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}");
    {
        let constructed = PingRequest { t0: 1700000000000, rtt: Some(42), data: Some(serde_json::json!({"probe":"canonical"})) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}", "payloads/ping.request.json/construct");
    }
    assert_round_trip::<PingResponse>("payloads/ping.response.json/round_trip", "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}");
    {
        let constructed = PingResponse { t0: 1700000000000, t1: 1700000000010, t2: 1700000000012, owd: 5, data: Some(serde_json::json!({"probe":"canonical"})) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}", "payloads/ping.response.json/construct");
    }
    assert_round_trip::<RecordingStartRequest>("payloads/recording.start.request.json/round_trip", "{\"tags\":[\"support\",\"canonical\"]}");
    {
        let constructed = RecordingStartRequest { tags: Some(vec!["support".to_owned(), "canonical".to_owned()]) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"tags\":[\"support\",\"canonical\"]}", "payloads/recording.start.request.json/construct");
    }
    assert_round_trip::<RecordingStartResponse>("payloads/recording.start.response.json/round_trip", "{\"id\":\"recording-1\"}");
    {
        let constructed = RecordingStartResponse { id: "recording-1".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"id\":\"recording-1\"}", "payloads/recording.start.response.json/construct");
    }
    assert_round_trip::<RecordingStopRequest>("payloads/recording.stop.request.json/round_trip", "{\"id\":\"recording-1\"}");
    {
        let constructed = RecordingStopRequest { id: "recording-1".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"id\":\"recording-1\"}", "payloads/recording.stop.request.json/construct");
    }
    assert_round_trip::<EmptyResponse>("payloads/recording.stop.response.json/round_trip", "{}");
    {
        let constructed = EmptyResponse(serde_json::Map::from_iter([]));
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "payloads/recording.stop.response.json/construct");
    }
    assert_round_trip::<SessionGetRequest>("payloads/session.get.request.json/round_trip", "{\"keys\":[\"customer\",\"attempt\"]}");
    {
        let constructed = SessionGetRequest { keys: vec!["customer".to_owned(), "attempt".to_owned()] };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"keys\":[\"customer\",\"attempt\"]}", "payloads/session.get.request.json/construct");
    }
    assert_round_trip::<SessionGetResponse>("payloads/session.get.response.json/round_trip", "{\"attempt\":2,\"customer\":\"Ada\"}");
    {
        let constructed = SessionGetResponse(serde_json::Map::from_iter([("attempt".to_owned(), serde_json::json!(2)), ("customer".to_owned(), serde_json::json!("Ada"))]));
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"attempt\":2,\"customer\":\"Ada\"}", "payloads/session.get.response.json/construct");
    }
    assert_round_trip::<SessionInitializeRequest>("payloads/session.initialize.request.json/round_trip", "{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}");
    {
        let constructed = SessionInitializeRequest { application: AppInfo { id: "app-1".to_owned() }, call: CallInfo { id: "call-1".to_owned(), session_id: "session-1".to_owned(), from: "+12025550100".to_owned(), to: "+12025550101".to_owned() }, audio_codec_offerings: vec![AudioCodec { id: "L16/8000/1".to_owned(), name: "L16".to_owned(), sample_rate: 8000, bit_depth: 16, channels: 1 }], metadata: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}", "payloads/session.initialize.request.json/construct");
    }
    assert_round_trip::<SessionInitializeResponse>("payloads/session.initialize.response.json/round_trip", "{\"audio_codec\":null}");
    {
        let constructed = SessionInitializeResponse { audio_codec: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"audio_codec\":null}", "payloads/session.initialize.response.json/construct");
    }
    assert_round_trip::<SessionSetRequest>("payloads/session.set.request.json/round_trip", "{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}");
    {
        let constructed = SessionSetRequest { data: serde_json::Map::from_iter([("attempt".to_owned(), serde_json::json!(2)), ("customer".to_owned(), serde_json::json!("Ada"))]) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}", "payloads/session.set.request.json/construct");
    }
    assert_round_trip::<EmptyResponse>("payloads/session.set.response.json/round_trip", "{}");
    {
        let constructed = EmptyResponse(serde_json::Map::from_iter([]));
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "payloads/session.set.response.json/construct");
    }
    assert_round_trip::<SessionTerminateRequest>("payloads/session.terminate.request.json/round_trip", "{\"reason\":\"completed\"}");
    {
        let constructed = SessionTerminateRequest { reason: "completed".to_owned() };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"reason\":\"completed\"}", "payloads/session.terminate.request.json/construct");
    }
    assert_round_trip::<EmptyResponse>("payloads/session.terminate.response.json/round_trip", "{}");
    {
        let constructed = EmptyResponse(serde_json::Map::from_iter([]));
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "payloads/session.terminate.response.json/construct");
    }
    assert_round_trip::<AudioInfoEvent>("variants/events/audio.info-nonzero.json/round_trip", "{\"read\":{\"bytes\":1280,\"bytes_per_second\":12800,\"bytes_total\":6400},\"write\":{\"bytes\":32,\"bytes_per_second\":106.66666666666667,\"bytes_total\":96}}");
    {
        let constructed = AudioInfoEvent { read: AudioInfoItem { bytes: 1280, bytes_per_second: 12800.0, bytes_total: 6400 }, write: AudioInfoItem { bytes: 32, bytes_per_second: 106.66666666666667, bytes_total: 96 } };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"read\":{\"bytes\":1280,\"bytes_per_second\":12800,\"bytes_total\":6400},\"write\":{\"bytes\":32,\"bytes_per_second\":106.66666666666667,\"bytes_total\":96}}", "variants/events/audio.info-nonzero.json/construct");
    }
    assert_round_trip::<CallHangupEvent>("variants/events/call.hangup-no-reason.json/round_trip", "{}");
    {
        let constructed = CallHangupEvent { reason: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "variants/events/call.hangup-no-reason.json/construct");
    }
    assert_round_trip::<OutputTranscriptDoneEvent>("variants/events/output.transcript.done-text-empty.json/round_trip", "{\"text\":\"\"}");
    {
        let constructed = OutputTranscriptDoneEvent { text: Some("".to_owned()) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"text\":\"\"}", "variants/events/output.transcript.done-text-empty.json/construct");
    }
    assert_round_trip::<OutputTranscriptDoneEvent>("variants/events/output.transcript.done-text.json/round_trip", "{\"text\":\"Hi there\"}");
    {
        let constructed = OutputTranscriptDoneEvent { text: Some("Hi there".to_owned()) };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"text\":\"Hi there\"}", "variants/events/output.transcript.done-text.json/construct");
    }
    assert_round_trip::<ApplicationMoveRequest>("variants/payloads/application.move.request-empty.json/round_trip", "{}");
    {
        let constructed = ApplicationMoveRequest { reason: None, application_id: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "variants/payloads/application.move.request-empty.json/construct");
    }
    assert_round_trip::<ApplicationMoveResponse>("variants/payloads/application.move.response-no-next.json/round_trip", "{}");
    {
        let constructed = ApplicationMoveResponse { next_application_id: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "variants/payloads/application.move.response-no-next.json/construct");
    }
    assert_round_trip::<PingRequest>("variants/payloads/ping.request-no-optionals.json/round_trip", "{\"t0\":1700000000000}");
    {
        let constructed = PingRequest { t0: 1700000000000, rtt: None, data: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"t0\":1700000000000}", "variants/payloads/ping.request-no-optionals.json/construct");
    }
    assert_round_trip::<PingResponse>("variants/payloads/ping.response-no-data.json/round_trip", "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5}");
    {
        let constructed = PingResponse { t0: 1700000000000, t1: 1700000000010, t2: 1700000000012, owd: 5, data: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5}", "variants/payloads/ping.response-no-data.json/construct");
    }
    assert_round_trip::<RecordingStartRequest>("variants/payloads/recording.start.request-no-tags.json/round_trip", "{}");
    {
        let constructed = RecordingStartRequest { tags: None };
        let actual = serde_json::to_string(&constructed).unwrap();
        assert_eq!(actual, "{}", "variants/payloads/recording.start.request-no-tags.json/construct");
    }
}
