// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

use super::*;

#[test]
fn generated_role_metadata_is_complete() {
    assert_eq!(APPLICATION_HANDLER_METHODS.len(), 3);
    assert_eq!(VOICE_HANDLER_METHODS.len(), 9);
}

struct GeneratedApplicationHandler;

#[async_trait::async_trait]
impl ApplicationHandler for GeneratedApplicationHandler {
    async fn ping(&self, _context: crate::HandlerContext, request: PingRequest) -> Result<PingResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}").unwrap())
    }
    async fn session_initialize(&self, _context: crate::HandlerContext, request: SessionInitializeRequest) -> Result<SessionInitializeResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{\"audio_codec\":null}").unwrap())
    }
    async fn session_terminate(&self, _context: crate::HandlerContext, request: SessionTerminateRequest) -> Result<EmptyResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"reason\":\"completed\"}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{}").unwrap())
    }
}

#[tokio::test]
#[allow(clippy::too_many_lines)]
async fn generated_application_request_contract_is_executable() {
    let registrations = application_handlers(Arc::new(GeneratedApplicationHandler));
    let methods = registrations.iter().map(crate::RequestRegistration::method).collect::<Vec<_>>();
    assert_eq!(methods, APPLICATION_HANDLER_METHODS);
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_PING).unwrap();
        let request = serde_json::from_str("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}").unwrap());
        assert!(!reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_SESSION_INITIALIZE).unwrap();
        let request = serde_json::from_str("{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{\"audio_codec\":null}").unwrap());
        assert!(!reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_SESSION_TERMINATE).unwrap();
        let request = serde_json::from_str("{\"reason\":\"completed\"}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{}").unwrap());
        assert!(reply.terminal);
    }
}

struct GeneratedApplicationEventHandler;

#[async_trait::async_trait]
impl ApplicationEventHandler for GeneratedApplicationEventHandler {
    async fn audio_info(&self, _context: crate::HandlerContext, event: AudioInfoEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
    async fn call_hangup(&self, _context: crate::HandlerContext, event: CallHangupEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"reason\":\"caller\"}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
    async fn dtmf(&self, _context: crate::HandlerContext, event: DtmfEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
    async fn session_updated(&self, _context: crate::HandlerContext, event: SessionUpdatedEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
}

#[tokio::test]
async fn generated_application_event_contract_is_executable() {
    let registrations = application_event_handlers(Arc::new(GeneratedApplicationEventHandler));
    assert_eq!(registrations.len(), 4);
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_AUDIO_INFO).unwrap();
        let event = serde_json::from_str("{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_CALL_HANGUP).unwrap();
        let event = serde_json::from_str("{\"reason\":\"caller\"}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_DTMF).unwrap();
        let event = serde_json::from_str("{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_SESSION_UPDATED).unwrap();
        let event = serde_json::from_str("{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
}

struct GeneratedVoiceHandler;

#[async_trait::async_trait]
impl VoiceHandler for GeneratedVoiceHandler {
    async fn application_move(&self, _context: crate::HandlerContext, request: ApplicationMoveRequest) -> Result<ApplicationMoveResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"reason\":\"handoff\",\"application_id\":\"app-2\"}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{\"next_application_id\":\"app-2\"}").unwrap())
    }
    async fn audio_buffer_clear(&self, _context: crate::HandlerContext, request: AudioBufferClearRequest) -> Result<AudioBufferClearResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{\"len\":320}").unwrap())
    }
    async fn call_hangup(&self, _context: crate::HandlerContext, request: CallHangupRequest) -> Result<EmptyResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"reason\":\"caller\"}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{}").unwrap())
    }
    async fn ping(&self, _context: crate::HandlerContext, request: PingRequest) -> Result<PingResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}").unwrap())
    }
    async fn recording_start(&self, _context: crate::HandlerContext, request: RecordingStartRequest) -> Result<RecordingStartResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"tags\":[\"support\",\"canonical\"]}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{\"id\":\"recording-1\"}").unwrap())
    }
    async fn recording_stop(&self, _context: crate::HandlerContext, request: RecordingStopRequest) -> Result<EmptyResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"id\":\"recording-1\"}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{}").unwrap())
    }
    async fn session_get(&self, _context: crate::HandlerContext, request: SessionGetRequest) -> Result<SessionGetResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"keys\":[\"customer\",\"attempt\"]}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{\"attempt\":2,\"customer\":\"Ada\"}").unwrap())
    }
    async fn session_set(&self, _context: crate::HandlerContext, request: SessionSetRequest) -> Result<EmptyResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{}").unwrap())
    }
}

#[tokio::test]
#[allow(clippy::too_many_lines)]
async fn generated_voice_request_contract_is_executable() {
    let registrations = voice_handlers(Arc::new(GeneratedVoiceHandler));
    let methods = registrations.iter().map(crate::RequestRegistration::method).collect::<Vec<_>>();
    assert_eq!(methods, VOICE_HANDLER_METHODS);
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_APPLICATION_MOVE).unwrap();
        let request = serde_json::from_str("{\"reason\":\"handoff\",\"application_id\":\"app-2\"}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{\"next_application_id\":\"app-2\"}").unwrap());
        assert!(reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_AUDIO_BUFFER_CLEAR).unwrap();
        let request = serde_json::from_str("{}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{\"len\":320}").unwrap());
        assert!(!reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_CALL_HANGUP).unwrap();
        let request = serde_json::from_str("{\"reason\":\"caller\"}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{}").unwrap());
        assert!(reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_PING).unwrap();
        let request = serde_json::from_str("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}").unwrap());
        assert!(!reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_RECORDING_START).unwrap();
        let request = serde_json::from_str("{\"tags\":[\"support\",\"canonical\"]}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{\"id\":\"recording-1\"}").unwrap());
        assert!(!reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_RECORDING_STOP).unwrap();
        let request = serde_json::from_str("{\"id\":\"recording-1\"}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{}").unwrap());
        assert!(!reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_SESSION_GET).unwrap();
        let request = serde_json::from_str("{\"keys\":[\"customer\",\"attempt\"]}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{\"attempt\":2,\"customer\":\"Ada\"}").unwrap());
        assert!(!reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_SESSION_SET).unwrap();
        let request = serde_json::from_str("{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{}").unwrap());
        assert!(!reply.terminal);
    }
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_SESSION_TERMINATE).unwrap();
        let request = serde_json::from_str("{\"reason\":\"completed\"}").unwrap();
        let error = registration.handle(crate::HandlerContext::default(), request).await.unwrap_err();
        match error {
            crate::Error::Handler(error) => assert_eq!(error, crate::WireError { code: 501, message: "session.terminate is not supported. please use application.move or call.hangup instead".to_owned(), data: None }),
            other => panic!("unexpected rejection: {other}"),
        }
    }
}

struct GeneratedVoiceEventHandler;

#[async_trait::async_trait]
impl VoiceEventHandler for GeneratedVoiceEventHandler {
    async fn agent_tool_call(&self, _context: crate::HandlerContext, event: AgentToolCallEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"name\":\"lookup_order\"}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
    async fn audio_speech_started(&self, _context: crate::HandlerContext, event: AudioSpeechStartedEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"origin\":\"sender\"}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
    async fn input_transcript(&self, _context: crate::HandlerContext, event: InputTranscriptEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"delta\":\"hello there\"}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
    async fn output_transcript_delta(&self, _context: crate::HandlerContext, event: OutputTranscriptDeltaEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"delta\":\"Hi \"}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
    async fn output_transcript_done(&self, _context: crate::HandlerContext, event: OutputTranscriptDoneEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
}

#[tokio::test]
async fn generated_voice_event_contract_is_executable() {
    let registrations = voice_event_handlers(Arc::new(GeneratedVoiceEventHandler));
    assert_eq!(registrations.len(), 5);
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_AGENT_TOOL_CALL).unwrap();
        let event = serde_json::from_str("{\"name\":\"lookup_order\"}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_AUDIO_SPEECH_STARTED).unwrap();
        let event = serde_json::from_str("{\"origin\":\"sender\"}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_INPUT_TRANSCRIPT).unwrap();
        let event = serde_json::from_str("{\"delta\":\"hello there\"}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_OUTPUT_TRANSCRIPT_DELTA).unwrap();
        let event = serde_json::from_str("{\"delta\":\"Hi \"}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_OUTPUT_TRANSCRIPT_DONE).unwrap();
        let event = serde_json::from_str("{}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
}
