// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

// Generated `babelforcev1` catalog types.

use serde::{Deserialize, Serialize};

/// Data emitted by `agent.tool.call` when the agent invokes a tool.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentToolCallEvent {
    /// Tool name; arguments and results are deliberately excluded.
    pub name: String,
}

impl crate::Validate for AgentToolCallEvent {}

/// IVR application metadata supplied when a session starts.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppInfo {
    /// Application or graph-node identifier.
    pub id: String,
}

impl crate::Validate for AppInfo {}

/// Parameters for terminal operation `application.move`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationMoveRequest {
    /// Optional reason for leaving the current graph node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Optional target graph-node identifier; absence means advance normally.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
}

impl crate::Validate for ApplicationMoveRequest {}

/// Result of `application.move`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationMoveResponse {
    /// Graph node selected after the move, when known.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_application_id: Option<String>,
}

impl crate::Validate for ApplicationMoveResponse {}

/// Parameters for `audio.buffer.clear`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct AudioBufferClearRequest(pub serde_json::Map<String, serde_json::Value>);

impl crate::Validate for AudioBufferClearRequest {}

/// Result of `audio.buffer.clear`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioBufferClearResponse {
    /// Number of buffered bytes removed.
    pub len: i64,
}

impl crate::Validate for AudioBufferClearResponse {}

/// A negotiated audio codec.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioCodec {
    /// Codec identifier such as `L16/8000/1`.
    pub id: String,
    /// Codec name such as `L16`.
    pub name: String,
    /// Sample rate in hertz.
    pub sample_rate: i64,
    /// Number of bits per sample.
    pub bit_depth: i64,
    /// Number of audio channels.
    pub channels: i64,
}

impl crate::Validate for AudioCodec {}

/// Data emitted by `audio.info` with read and write throughput counters.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioInfoEvent {
    /// Audio read from the telephony stream.
    pub read: AudioInfoItem,
    /// Audio written to the telephony stream.
    pub write: AudioInfoItem,
}

impl crate::Validate for AudioInfoEvent {}

/// Throughput counters for one audio direction.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioInfoItem {
    /// Bytes transferred during the last reporting interval.
    pub bytes: i64,
    /// Transfer rate during the last reporting interval.
    #[serde(serialize_with = "serialize_go_float64", deserialize_with = "deserialize_go_float64")]
    pub bytes_per_second: f64,
    /// Total bytes transferred since session start.
    pub bytes_total: i64,
}

impl crate::Validate for AudioInfoItem {}

/// Data emitted by `audio.speech.started` for barge-in signaling.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioSpeechStartedEvent {
    /// Side where speech began: `sender` or `receiver`.
    pub origin: String,
}

impl crate::Validate for AudioSpeechStartedEvent {}

/// Data emitted by `call.hangup` when the voice peer reports call termination.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallHangupEvent {
    /// Optional hangup reason.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl crate::Validate for CallHangupEvent {}

/// Parameters for terminal operation `call.hangup`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallHangupRequest {
    /// Reason the call should be hung up.
    pub reason: String,
}

impl crate::Validate for CallHangupRequest {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.reason.chars().count() < 1 {
            return Err(crate::ValidationError::new("reason must contain at least 1 character(s)"));
        }
        Ok(())
    }
}

/// Telephony call metadata supplied when a session starts.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallInfo {
    /// Call identifier.
    pub id: String,
    /// Session identifier owned by the voice peer.
    pub session_id: String,
    /// Caller address or number.
    pub from: String,
    /// Callee address or number.
    pub to: String,
}

impl crate::Validate for CallInfo {}

/// Data emitted by `dtmf` when the caller releases a key.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DtmfEvent {
    /// Monotonic event sequence number within the session.
    pub seq: i64,
    /// Epoch timestamp in milliseconds when the key was pressed.
    pub pressed_at: i64,
    /// Epoch timestamp in milliseconds when the key was released.
    pub released_at: i64,
    /// DTMF digit that was pressed.
    pub digit: String,
}

impl crate::Validate for DtmfEvent {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.seq < 0 {
            return Err(crate::ValidationError::new("seq must be at least 0"));
        }
        if self.pressed_at < 0 {
            return Err(crate::ValidationError::new("pressed_at must be at least 0"));
        }
        if self.released_at < 0 {
            return Err(crate::ValidationError::new("released_at must be at least 0"));
        }
        if self.digit.chars().count() < 1 {
            return Err(crate::ValidationError::new("digit must contain at least 1 character(s)"));
        }
        if self.pressed_at > self.released_at {
            return Err(crate::ValidationError::new("released_at must be greater than or equal to pressed_at"));
        }
        Ok(())
    }
}

/// Empty object returned by operations without result fields.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EmptyResponse(pub serde_json::Map<String, serde_json::Value>);

impl crate::Validate for EmptyResponse {}

/// Data emitted by `input.transcript` for one finalized caller utterance.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputTranscriptEvent {
    /// Complete caller transcript; the legacy wire field is named `delta`.
    pub delta: String,
}

impl crate::Validate for InputTranscriptEvent {}

/// Data emitted by `output.transcript.delta` for incremental agent speech text.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputTranscriptDeltaEvent {
    /// Incremental transcript text.
    pub delta: String,
}

impl crate::Validate for OutputTranscriptDeltaEvent {}

/// Data emitted by `output.transcript.done` when an agent utterance finishes.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputTranscriptDoneEvent {
    /// Optional complete text; absence means retain the accumulated deltas.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

impl crate::Validate for OutputTranscriptDoneEvent {}

/// Parameters for ordinary catalog operation `ping`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PingRequest {
    /// Sender timestamp in epoch milliseconds.
    pub t0: i64,
    /// Optional round-trip time measured by a previous ping.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rtt: Option<i64>,
    /// Optional arbitrary data echoed by the peer.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl crate::Validate for PingRequest {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.t0 == 0 {
            return Err(crate::ValidationError::new("t0 must be non-zero"));
        }
        Ok(())
    }
}

/// Result of ordinary catalog operation `ping`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PingResponse {
    /// Echo of the request sender timestamp.
    pub t0: i64,
    /// Transport receive timestamp in epoch milliseconds.
    pub t1: i64,
    /// Application handling timestamp in epoch milliseconds.
    pub t2: i64,
    /// Estimated one-way delay in milliseconds.
    pub owd: i64,
    /// Optional arbitrary data echoed from the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl crate::Validate for PingResponse {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.t0 == 0 {
            return Err(crate::ValidationError::new("t0 must be non-zero"));
        }
        if self.t1 == 0 {
            return Err(crate::ValidationError::new("t1 must be non-zero"));
        }
        if self.t2 == 0 {
            return Err(crate::ValidationError::new("t2 must be non-zero"));
        }
        Ok(())
    }
}

/// Parameters for `recording.start`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingStartRequest {
    /// Optional recording tags.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl crate::Validate for RecordingStartRequest {}

/// Result of `recording.start`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingStartResponse {
    /// New recording identifier.
    pub id: String,
}

impl crate::Validate for RecordingStartResponse {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.id.chars().count() < 1 {
            return Err(crate::ValidationError::new("id must contain at least 1 character(s)"));
        }
        Ok(())
    }
}

/// Parameters for `recording.stop`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingStopRequest {
    /// Recording identifier to stop.
    pub id: String,
}

impl crate::Validate for RecordingStopRequest {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.id.chars().count() < 1 {
            return Err(crate::ValidationError::new("id must contain at least 1 character(s)"));
        }
        Ok(())
    }
}

/// Parameters for `session.get`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionGetRequest {
    /// Keys to fetch; an empty list requests all variables.
    pub keys: Vec<String>,
}

impl crate::Validate for SessionGetRequest {}

/// Bare open-map result returned by `session.get`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionGetResponse(pub serde_json::Map<String, serde_json::Value>);

impl crate::Validate for SessionGetResponse {}

/// Parameters for `session.initialize`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionInitializeRequest {
    /// Application that owns the call flow.
    pub application: AppInfo,
    /// Call being bridged into the session.
    pub call: CallInfo,
    /// Audio codecs offered by the voice peer.
    pub audio_codec_offerings: Vec<AudioCodec>,
    /// Free-form session metadata; the field is present and may be `null`.
    pub metadata: Option<serde_json::Map<String, serde_json::Value>>,
}

impl crate::Validate for SessionInitializeRequest {}

/// Result of `session.initialize`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionInitializeResponse {
    /// Selected codec; the field is present and may be `null`.
    pub audio_codec: Option<AudioCodec>,
}

impl crate::Validate for SessionInitializeResponse {}

/// Parameters for `session.set`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionSetRequest {
    /// Session variables to set.
    pub data: serde_json::Map<String, serde_json::Value>,
}

impl crate::Validate for SessionSetRequest {}

/// Parameters for terminal operation `session.terminate`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionTerminateRequest {
    /// Reason the session is ending.
    pub reason: String,
}

impl crate::Validate for SessionTerminateRequest {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.reason.chars().count() < 1 {
            return Err(crate::ValidationError::new("reason must contain at least 1 character(s)"));
        }
        Ok(())
    }
}

/// Data emitted by `session.updated` when negotiated state changes.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionUpdatedEvent {
    /// Current codec; the field is present and may be `null`.
    pub audio_codec: Option<AudioCodec>,
}

impl crate::Validate for SessionUpdatedEvent {}

pub const METHOD_APPLICATION_MOVE: &str = "application.move";
pub const METHOD_AUDIO_BUFFER_CLEAR: &str = "audio.buffer.clear";
pub const METHOD_CALL_HANGUP: &str = "call.hangup";
pub const METHOD_PING: &str = "ping";
pub const METHOD_RECORDING_START: &str = "recording.start";
pub const METHOD_RECORDING_STOP: &str = "recording.stop";
pub const METHOD_SESSION_GET: &str = "session.get";
pub const METHOD_SESSION_INITIALIZE: &str = "session.initialize";
pub const METHOD_SESSION_SET: &str = "session.set";
pub const METHOD_SESSION_TERMINATE: &str = "session.terminate";
pub const EVENT_AGENT_TOOL_CALL: &str = "agent.tool.call";
pub const EVENT_AUDIO_INFO: &str = "audio.info";
pub const EVENT_AUDIO_SPEECH_STARTED: &str = "audio.speech.started";
pub const EVENT_CALL_HANGUP: &str = "call.hangup";
pub const EVENT_DTMF: &str = "dtmf";
pub const EVENT_INPUT_TRANSCRIPT: &str = "input.transcript";
pub const EVENT_OUTPUT_TRANSCRIPT_DELTA: &str = "output.transcript.delta";
pub const EVENT_OUTPUT_TRANSCRIPT_DONE: &str = "output.transcript.done";
pub const EVENT_SESSION_UPDATED: &str = "session.updated";

impl crate::NamedRequest for ApplicationMoveRequest {
    type Response = ApplicationMoveResponse;
    const METHOD: &'static str = METHOD_APPLICATION_MOVE;
}

impl crate::NamedRequest for AudioBufferClearRequest {
    type Response = AudioBufferClearResponse;
    const METHOD: &'static str = METHOD_AUDIO_BUFFER_CLEAR;
}

impl crate::NamedRequest for CallHangupRequest {
    type Response = EmptyResponse;
    const METHOD: &'static str = METHOD_CALL_HANGUP;
}

impl crate::NamedRequest for PingRequest {
    type Response = PingResponse;
    const METHOD: &'static str = METHOD_PING;
}

impl crate::NamedRequest for RecordingStartRequest {
    type Response = RecordingStartResponse;
    const METHOD: &'static str = METHOD_RECORDING_START;
}

impl crate::NamedRequest for RecordingStopRequest {
    type Response = EmptyResponse;
    const METHOD: &'static str = METHOD_RECORDING_STOP;
}

impl crate::NamedRequest for SessionGetRequest {
    type Response = SessionGetResponse;
    const METHOD: &'static str = METHOD_SESSION_GET;
}

impl crate::NamedRequest for SessionInitializeRequest {
    type Response = SessionInitializeResponse;
    const METHOD: &'static str = METHOD_SESSION_INITIALIZE;
}

impl crate::NamedRequest for SessionSetRequest {
    type Response = EmptyResponse;
    const METHOD: &'static str = METHOD_SESSION_SET;
}

impl crate::NamedRequest for SessionTerminateRequest {
    type Response = EmptyResponse;
    const METHOD: &'static str = METHOD_SESSION_TERMINATE;
}

impl crate::NamedEvent for AgentToolCallEvent {
    const EVENT: &'static str = EVENT_AGENT_TOOL_CALL;
}

impl crate::NamedEvent for AudioInfoEvent {
    const EVENT: &'static str = EVENT_AUDIO_INFO;
}

impl crate::NamedEvent for AudioSpeechStartedEvent {
    const EVENT: &'static str = EVENT_AUDIO_SPEECH_STARTED;
}

impl crate::NamedEvent for CallHangupEvent {
    const EVENT: &'static str = EVENT_CALL_HANGUP;
}

impl crate::NamedEvent for DtmfEvent {
    const EVENT: &'static str = EVENT_DTMF;
}

impl crate::NamedEvent for InputTranscriptEvent {
    const EVENT: &'static str = EVENT_INPUT_TRANSCRIPT;
}

impl crate::NamedEvent for OutputTranscriptDeltaEvent {
    const EVENT: &'static str = EVENT_OUTPUT_TRANSCRIPT_DELTA;
}

impl crate::NamedEvent for OutputTranscriptDoneEvent {
    const EVENT: &'static str = EVENT_OUTPUT_TRANSCRIPT_DONE;
}

impl crate::NamedEvent for SessionUpdatedEvent {
    const EVENT: &'static str = EVENT_SESSION_UPDATED;
}

#[allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::trivially_copy_pass_by_ref
)]
fn serialize_go_float64<S>(value: &f64, serializer: S) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    if value.is_finite()
        && value.fract() == 0.0
        && *value >= i64::MIN as f64
        && *value <= i64::MAX as f64
    {
        serializer.serialize_i64(*value as i64)
    } else {
        serializer.serialize_f64(*value)
    }
}

fn deserialize_go_float64<'de, D>(deserializer: D) -> Result<f64, D::Error>
where
    D: serde::Deserializer<'de>,
{
    f64::deserialize(deserializer)
}
