// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

use super::*;

#[test]
fn generated_role_metadata_is_complete() {
    assert_eq!(APPLICATION_HANDLER_METHODS.len(), 1);
    assert_eq!(VOICE_HANDLER_METHODS.len(), 0);
}

struct GeneratedApplicationHandler;

#[async_trait::async_trait]
impl ApplicationHandler for GeneratedApplicationHandler {
    async fn demo_echo(&self, _context: crate::HandlerContext, request: DemoEchoRequest) -> Result<DemoEchoResponse, crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"message\":\"hello from demo.v1\"}").unwrap();
        assert_eq!(serde_json::to_value(request).unwrap(), expected);
        Ok(serde_json::from_str("{\"message\":\"hello from demo.v1\"}").unwrap())
    }
}

#[tokio::test]
#[allow(clippy::too_many_lines)]
async fn generated_application_request_contract_is_executable() {
    let registrations = application_handlers(Arc::new(GeneratedApplicationHandler));
    let methods = registrations.iter().map(crate::RequestRegistration::method).collect::<Vec<_>>();
    assert_eq!(methods, APPLICATION_HANDLER_METHODS);
    {
        let registration = registrations.iter().find(|registration| registration.method() == METHOD_DEMO_ECHO).unwrap();
        let request = serde_json::from_str("{\"message\":\"hello from demo.v1\"}").unwrap();
        let reply = registration.handle(crate::HandlerContext::default(), request).await.unwrap();
        assert_eq!(reply.payload, serde_json::from_str::<serde_json::Value>("{\"message\":\"hello from demo.v1\"}").unwrap());
        assert!(!reply.terminal);
    }
}

struct GeneratedApplicationEventHandler;

#[async_trait::async_trait]
impl ApplicationEventHandler for GeneratedApplicationEventHandler {
}

#[tokio::test]
async fn generated_application_event_contract_is_executable() {
    let registrations = application_event_handlers(Arc::new(GeneratedApplicationEventHandler));
    assert_eq!(registrations.len(), 0);
}

struct GeneratedVoiceHandler;

#[async_trait::async_trait]
impl VoiceHandler for GeneratedVoiceHandler {
}

#[tokio::test]
#[allow(clippy::too_many_lines)]
async fn generated_voice_request_contract_is_executable() {
    let registrations = voice_handlers(Arc::new(GeneratedVoiceHandler));
    let methods = registrations.iter().map(crate::RequestRegistration::method).collect::<Vec<_>>();
    assert_eq!(methods, VOICE_HANDLER_METHODS);
}

struct GeneratedVoiceEventHandler;

#[async_trait::async_trait]
impl VoiceEventHandler for GeneratedVoiceEventHandler {
    async fn demo_observed(&self, _context: crate::HandlerContext, event: DemoObservedEvent) -> Result<(), crate::Error> {
        let expected = serde_json::from_str::<serde_json::Value>("{\"message\":\"hello from demo.v1\"}").unwrap();
        assert_eq!(serde_json::to_value(event).unwrap(), expected);
        Ok(())
    }
}

#[tokio::test]
async fn generated_voice_event_contract_is_executable() {
    let registrations = voice_event_handlers(Arc::new(GeneratedVoiceEventHandler));
    assert_eq!(registrations.len(), 1);
    {
        let registration = registrations.iter().find(|registration| registration.event() == EVENT_DEMO_OBSERVED).unwrap();
        let event = serde_json::from_str("{\"message\":\"hello from demo.v1\"}").unwrap();
        registration.handle(crate::HandlerContext::default(), event).await.unwrap();
    }
}
