// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

// Generated `demov1` catalog types.

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DemoEchoRequest {
    /// Text to echo through the application role.
    pub message: String,
}

impl crate::Validate for DemoEchoRequest {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.message.chars().count() < 1 {
            return Err(crate::ValidationError::new("message must contain at least 1 character(s)"));
        }
        Ok(())
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DemoEchoResponse {
    /// Text returned unchanged by the application role.
    pub message: String,
}

impl crate::Validate for DemoEchoResponse {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.message.chars().count() < 1 {
            return Err(crate::ValidationError::new("message must contain at least 1 character(s)"));
        }
        Ok(())
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DemoObservedEvent {
    /// Text observed after a completed echo.
    pub message: String,
}

impl crate::Validate for DemoObservedEvent {
    fn validate(&self) -> Result<(), crate::ValidationError> {
        if self.message.chars().count() < 1 {
            return Err(crate::ValidationError::new("message must contain at least 1 character(s)"));
        }
        Ok(())
    }
}

pub const METHOD_DEMO_ECHO: &str = "demo.echo";
pub const EVENT_DEMO_OBSERVED: &str = "demo.observed";

impl crate::NamedRequest for DemoEchoRequest {
    type Response = DemoEchoResponse;
    const METHOD: &'static str = METHOD_DEMO_ECHO;
}

impl crate::NamedEvent for DemoObservedEvent {
    const EVENT: &'static str = EVENT_DEMO_OBSERVED;
}
