// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

use std::sync::Arc;

use async_trait::async_trait;

/// Operations implemented by the local Application role.
#[async_trait]
pub trait ApplicationHandler: Send + Sync {
    async fn demo_echo(
        &self,
        context: crate::HandlerContext,
        request: DemoEchoRequest,
    ) -> Result<DemoEchoResponse, crate::Error>;
}

#[doc(hidden)]
pub const APPLICATION_HANDLER_METHODS: &[&str] = &[
    METHOD_DEMO_ECHO,
];

/// Convert a role implementation into runtime request registrations.
pub fn application_handlers(handler: Arc<dyn ApplicationHandler>) -> Vec<crate::RequestRegistration> {
    let mut registrations = Vec::new();
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::RequestRegistration::typed::<DemoEchoRequest, DemoEchoResponse, _, _>(
            METHOD_DEMO_ECHO,
            false,
            move |context, request| {
                let handler = Arc::clone(&handler);
                async move { handler.demo_echo(context, request).await }
            },
        ));
    }
    drop(handler);
    registrations
}

/// Operations implemented by the local Voice role.
#[async_trait]
pub trait VoiceHandler: Send + Sync {
}

#[doc(hidden)]
pub const VOICE_HANDLER_METHODS: &[&str] = &[
];

/// Convert a role implementation into runtime request registrations.
pub fn voice_handlers(handler: Arc<dyn VoiceHandler>) -> Vec<crate::RequestRegistration> {
    drop(handler);
    Vec::new()
}

/// Typed client for operations implemented by a peer in the Application role.
pub struct ApplicationPeer<R> {
    requester: R,
}

impl<R> ApplicationPeer<R> {
    #[must_use]
    pub const fn new(requester: R) -> Self { Self { requester } }

    /// Return the underlying raw requester.
    pub fn into_inner(self) -> R { self.requester }
}

impl<R: crate::Requester> ApplicationPeer<R> {
    /// Send the typed request through the underlying requester.
    ///
    /// # Errors
    ///
    /// Returns validation, transport, remote, or response-decoding failures.
    pub async fn demo_echo(&self, request: DemoEchoRequest) -> Result<DemoEchoResponse, crate::Error> {
        crate::request_peer(&self.requester, request).await
    }
}

/// Typed client for operations implemented by a peer in the Voice role.
pub struct VoicePeer<R> {
    requester: R,
}

impl<R> VoicePeer<R> {
    #[must_use]
    pub const fn new(requester: R) -> Self { Self { requester } }

    /// Return the underlying raw requester.
    pub fn into_inner(self) -> R { self.requester }
}

impl<R: crate::Requester> VoicePeer<R> {
}

/// Typed emitter for events owned by the Application role.
pub struct ApplicationEvents<N> {
    notifier: N,
}

impl<N> ApplicationEvents<N> {
    #[must_use]
    pub const fn new(notifier: N) -> Self { Self { notifier } }

    /// Return the underlying raw notifier.
    pub fn into_inner(self) -> N { self.notifier }
}

impl<N: crate::Notifier> ApplicationEvents<N> {
    /// Emit the typed event through the underlying notifier.
    ///
    /// # Errors
    ///
    /// Returns validation, encoding, or transport failures.
    pub async fn demo_observed(&self, event: DemoObservedEvent) -> Result<(), crate::Error> {
        crate::notify_event(&self.notifier, event).await
    }
}

/// Typed emitter for events owned by the Voice role.
pub struct VoiceEvents<N> {
    notifier: N,
}

impl<N> VoiceEvents<N> {
    #[must_use]
    pub const fn new(notifier: N) -> Self { Self { notifier } }

    /// Return the underlying raw notifier.
    pub fn into_inner(self) -> N { self.notifier }
}

impl<N: crate::Notifier> VoiceEvents<N> {
}

/// Peer events received by the local Application role.
#[async_trait]
pub trait ApplicationEventHandler: Send + Sync {
}

/// Convert a role event implementation into runtime event registrations.
pub fn application_event_handlers(handler: Arc<dyn ApplicationEventHandler>) -> Vec<crate::EventRegistration> {
    drop(handler);
    Vec::new()
}

/// Peer events received by the local Voice role.
#[async_trait]
pub trait VoiceEventHandler: Send + Sync {
    async fn demo_observed(
        &self,
        context: crate::HandlerContext,
        event: DemoObservedEvent,
    ) -> Result<(), crate::Error>;
}

/// Convert a role event implementation into runtime event registrations.
pub fn voice_event_handlers(handler: Arc<dyn VoiceEventHandler>) -> Vec<crate::EventRegistration> {
    let mut registrations = Vec::new();
    {
        let handler = Arc::clone(&handler);
        registrations.push(crate::EventRegistration::typed::<DemoObservedEvent, _, _>(
            EVENT_DEMO_OBSERVED,
            move |context, event| {
                let handler = Arc::clone(&handler);
                async move { handler.demo_observed(context, event).await }
            },
        ));
    }
    drop(handler);
    registrations
}
