[workspace]
resolver = "3"
members = [
    "src/rtvbp-spec",
    "src/rtvbp-sdk",
    "src/rtvbp-demo",
]

[workspace.dependencies]
rtvbp-spec = {path = "src/rtvbp-spec"}
rtvbp-sdk = {path = "src/rtvbp-sdk"}
