// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package demov1

import "errors"

// DemoEchoRequest is generated from the protocol catalog.
type DemoEchoRequest struct {
	// Message: Text to echo through the application role.
	Message string `json:"message"`
}

// Validate checks the semantic constraints declared for DemoEchoRequest.
func (value *DemoEchoRequest) Validate() error {
	if value == nil {
		return errors.New("DemoEchoRequest is nil")
	}
	if len(value.Message) < 1 {
		return errors.New("message must contain at least 1 character(s)")
	}
	return nil
}

// DemoEchoResponse is generated from the protocol catalog.
type DemoEchoResponse struct {
	// Message: Text returned unchanged by the application role.
	Message string `json:"message"`
}

// Validate checks the semantic constraints declared for DemoEchoResponse.
func (value *DemoEchoResponse) Validate() error {
	if value == nil {
		return errors.New("DemoEchoResponse is nil")
	}
	if len(value.Message) < 1 {
		return errors.New("message must contain at least 1 character(s)")
	}
	return nil
}

// DemoObservedEvent is generated from the protocol catalog.
type DemoObservedEvent struct {
	// Message: Text observed after a completed echo.
	Message string `json:"message"`
}

// Validate checks the semantic constraints declared for DemoObservedEvent.
func (value *DemoObservedEvent) Validate() error {
	if value == nil {
		return errors.New("DemoObservedEvent is nil")
	}
	if len(value.Message) < 1 {
		return errors.New("message must contain at least 1 character(s)")
	}
	return nil
}

const MethodDemoEcho = "demo.echo"
const EventDemoObserved = "demo.observed"

// MethodName returns MethodDemoEcho.
func (*DemoEchoRequest) MethodName() string { return MethodDemoEcho }

// EventName returns EventDemoObserved.
func (*DemoObservedEvent) EventName() string { return EventDemoObserved }
