// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package demov1

import (
	"context"
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/babelforce/rtvbp/sdk/go"
)

// Requester is the narrow request capability used by typed peer clients.
// Both *rtvbp.Session and rtvbp.SHC satisfy it.
type Requester interface {
	Request(context.Context, rtvbp.NamedRequest) (rtvbp.Response, error)
}

// Notifier is the narrow event capability used by role event emitters.
// rtvbp.SHC satisfies it.
type Notifier interface {
	Notify(context.Context, rtvbp.NamedEvent) error
}

// ApplicationHandler implements operations handled by the Application role.
type ApplicationHandler interface {
	DemoEcho(context.Context, rtvbp.SHC, *DemoEchoRequest) (*DemoEchoResponse, error)
}

// ApplicationHandlers adapts a ApplicationHandler for rtvbp.NewHandler.
func ApplicationHandlers(handler ApplicationHandler) []any {
	return []any{
		rtvbp.HandleRequest(handler.DemoEcho),
	}
}

// VoiceHandler implements operations handled by the Voice role.
type VoiceHandler interface {
}

// VoiceHandlers adapts a VoiceHandler for rtvbp.NewHandler.
func VoiceHandlers(handler VoiceHandler) []any {
	return []any{
	}
}

// ApplicationPeer is a typed client for operations offered by the Application role.
type ApplicationPeer struct {
	requester Requester
}

// NewApplicationPeer creates a typed Application peer client.
func NewApplicationPeer(requester Requester) *ApplicationPeer {
	return &ApplicationPeer{requester: requester}
}

// DemoEcho calls demo.echo.
func (peer *ApplicationPeer) DemoEcho(ctx context.Context, request *DemoEchoRequest) (*DemoEchoResponse, error) {
	return requestPeer[DemoEchoResponse](ctx, peer.requester, request)
}

// VoicePeer is a typed client for operations offered by the Voice role.
type VoicePeer struct {
	requester Requester
}

// NewVoicePeer creates a typed Voice peer client.
func NewVoicePeer(requester Requester) *VoicePeer {
	return &VoicePeer{requester: requester}
}

func requestPeer[Result any](ctx context.Context, requester Requester, request rtvbp.NamedRequest) (*Result, error) {
	if request == nil || reflect.ValueOf(request).Kind() == reflect.Pointer && reflect.ValueOf(request).IsNil() {
		return nil, fmt.Errorf("%w: request is nil", rtvbp.ErrRequestValidationFailed)
	}
	if validation, ok := request.(rtvbp.Validation); ok {
		if err := validation.Validate(); err != nil {
			return nil, fmt.Errorf("%w: request for %s: %w", rtvbp.ErrRequestValidationFailed, request.MethodName(), err)
		}
	}
	response, err := requester.Request(ctx, request)
	if err != nil {
		return nil, err
	}
	payload := response.Payload
	if len(payload) == 0 {
		payload = json.RawMessage("{}")
	}
	result := new(Result)
	if err := json.Unmarshal(payload, result); err != nil {
		return nil, fmt.Errorf("decode response for %s: %w", request.MethodName(), err)
	}
	if validation, ok := any(result).(rtvbp.Validation); ok {
		if err := validation.Validate(); err != nil {
			return nil, fmt.Errorf("validate response for %s: %w", request.MethodName(), err)
		}
	}
	return result, nil
}

func notifyEvent(ctx context.Context, notifier Notifier, event rtvbp.NamedEvent) error {
	if event == nil || reflect.ValueOf(event).Kind() == reflect.Pointer && reflect.ValueOf(event).IsNil() {
		return fmt.Errorf("%w: event is nil", rtvbp.ErrRequestValidationFailed)
	}
	if validation, ok := event.(rtvbp.Validation); ok {
		if err := validation.Validate(); err != nil {
			return fmt.Errorf("%w: event %s: %w", rtvbp.ErrRequestValidationFailed, event.EventName(), err)
		}
	}
	return notifier.Notify(ctx, event)
}

// ApplicationEvents emits events owned by the Application role.
type ApplicationEvents struct {
	notifier Notifier
}

// NewApplicationEvents creates a typed Application event emitter.
func NewApplicationEvents(notifier Notifier) *ApplicationEvents {
	return &ApplicationEvents{notifier: notifier}
}

// DemoObserved emits demo.observed.
func (events *ApplicationEvents) DemoObserved(ctx context.Context, event *DemoObservedEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// VoiceEvents emits events owned by the Voice role.
type VoiceEvents struct {
	notifier Notifier
}

// NewVoiceEvents creates a typed Voice event emitter.
func NewVoiceEvents(notifier Notifier) *VoiceEvents {
	return &VoiceEvents{notifier: notifier}
}

// ApplicationEventHandler receives events emitted by the peer role.
type ApplicationEventHandler interface {
}

// ApplicationEventHandlers adapts a ApplicationEventHandler for rtvbp.NewHandler.
func ApplicationEventHandlers(handler ApplicationEventHandler) []any {
	return []any{
	}
}

// VoiceEventHandler receives events emitted by the peer role.
type VoiceEventHandler interface {
	DemoObserved(context.Context, rtvbp.SHC, *DemoObservedEvent) error
}

// VoiceEventHandlers adapts a VoiceEventHandler for rtvbp.NewHandler.
func VoiceEventHandlers(handler VoiceEventHandler) []any {
	return []any{
		rtvbp.HandleEvent(handler.DemoObserved),
	}
}
