// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package demov1

import (
	"bytes"
	"encoding/json"
	"testing"
)

type goldenCase struct {
	name string

	golden []byte

	newValue func() any

	constructed any
}

var goldenCases = []goldenCase{
}

func TestGoldenPayloads(t *testing.T) {
	for _, tc := range goldenCases {
		t.Run(tc.name+"/round_trip", func(t *testing.T) {
			value := tc.newValue()
			if err := json.Unmarshal(tc.golden, value); err != nil {
				t.Fatal(err)
			}
			actual, err := json.Marshal(value)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(actual, tc.golden) {
				t.Fatalf("round-trip mismatch\nwant: %s\n got: %s", tc.golden, actual)
			}
		})
		t.Run(tc.name+"/construct", func(t *testing.T) {
			actual, err := json.Marshal(tc.constructed)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(actual, tc.golden) {
				t.Fatalf("constructed mismatch\nwant: %s\n got: %s", tc.golden, actual)
			}
		})
	}
}

func ptr[T any](value T) *T { return &value }
