// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package demov1

import (
	"context"
	"encoding/json"
	"errors"
	"testing"

	"github.com/babelforce/rtvbp/sdk/go"
)

var roleTestRequests = map[string]json.RawMessage{
	MethodDemoEcho: json.RawMessage("{\"message\":\"hello from demo.v1\"}"),
}

var roleTestResponses = map[string]json.RawMessage{
	MethodDemoEcho: json.RawMessage("{\"message\":\"hello from demo.v1\"}"),
}

var roleTestEvents = map[string]json.RawMessage{
	EventDemoObserved: json.RawMessage("{\"message\":\"hello from demo.v1\"}"),
}

var roleTestTerminal = map[string]bool{
	MethodDemoEcho: false,
}

var roleTestRejections = map[string]rtvbp.WireError{
}

func roleTestValue[T any](payload json.RawMessage) *T {
	value := new(T)
	if err := json.Unmarshal(payload, value); err != nil {
		panic(err)
	}
	return value
}

type applicationRoleTestHandler struct{}

func (*applicationRoleTestHandler) DemoEcho(context.Context, rtvbp.SHC, *DemoEchoRequest) (*DemoEchoResponse, error) {
	return roleTestValue[DemoEchoResponse](roleTestResponses[MethodDemoEcho]), nil
}

type applicationRoleTestEventHandler struct{}

type voiceRoleTestHandler struct{}

type voiceRoleTestEventHandler struct{}

func (*voiceRoleTestEventHandler) DemoObserved(context.Context, rtvbp.SHC, *DemoObservedEvent) error {
	return nil
}

type roleTestRequest struct{}

func (*roleTestRequest) MethodName() string { return "role.test" }

type roleTestInvalidRequest struct{}

func (*roleTestInvalidRequest) MethodName() string { return "role.invalid" }
func (*roleTestInvalidRequest) Validate() error    { return errors.New("invalid request") }

type roleTestInvalidEvent struct{}

func (*roleTestInvalidEvent) EventName() string { return "role.invalid" }
func (*roleTestInvalidEvent) Validate() error   { return errors.New("invalid event") }

type roleTestRequester struct {
	empty bool
	calls int
}

func (requester *roleTestRequester) Request(_ context.Context, request rtvbp.NamedRequest) (rtvbp.Response, error) {
	requester.calls++
	if requester.empty {
		return rtvbp.Response{}, nil
	}
	return rtvbp.Response{Payload: roleTestResponses[request.MethodName()]}, nil
}

type roleTestNotifier struct {
	names []string
}

func (notifier *roleTestNotifier) Notify(_ context.Context, event rtvbp.NamedEvent) error {
	notifier.names = append(notifier.names, event.EventName())
	return nil
}

func TestGeneratedRoleAdapters(t *testing.T) {
	tests := []struct {
		name string
		requests []any
		events []any
	}{
		{name: "application", requests: ApplicationHandlers(&applicationRoleTestHandler{}), events: ApplicationEventHandlers(&applicationRoleTestEventHandler{})},
		{name: "voice", requests: VoiceHandlers(&voiceRoleTestHandler{}), events: VoiceEventHandlers(&voiceRoleTestEventHandler{})},
	}
	for _, tc := range tests {
		t.Run(tc.name+"/requests", func(t *testing.T) {
			for _, registration := range tc.requests {
				handler := registration.(rtvbp.RequestHandler)
				shc := rtvbp.NewTestingSHC()
				err := handler.Handle(context.Background(), shc, rtvbp.Request{Method: handler.MethodName(), Payload: roleTestRequests[handler.MethodName()]})
				if rejection, ok := roleTestRejections[tc.name+"/"+handler.MethodName()]; ok {
					var handlerError *rtvbp.HandlerError
					if !errors.As(err, &handlerError) || handlerError.WireError.Code != rejection.Code || handlerError.WireError.Message != rejection.Message {
						t.Fatalf("%s rejection = %#v, want %#v", handler.MethodName(), err, rejection)
					}
					if got := shc.State(); got != rtvbp.SessionStateActive {
						t.Fatalf("%s rejection state = %s, want active", handler.MethodName(), got)
					}
					continue
				}
				if err != nil {
					t.Fatalf("%s: %v", handler.MethodName(), err)
				}
				want := rtvbp.SessionStateActive
				if roleTestTerminal[handler.MethodName()] {
					want = rtvbp.SessionStateClosed
				}
				if got := shc.State(); got != want {
					t.Fatalf("%s state = %s, want %s", handler.MethodName(), got, want)
				}
			}
		})
		t.Run(tc.name+"/events", func(t *testing.T) {
			for _, registration := range tc.events {
				handler := registration.(rtvbp.EventHandler)
				err := handler.Handle(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Event{Name: handler.EventName(), Payload: roleTestEvents[handler.EventName()]})
				if err != nil {
					t.Fatalf("%s: %v", handler.EventName(), err)
				}
			}
		})
	}
}

func TestGeneratedTypedPeers(t *testing.T) {
	ctx := context.Background()
	application := NewApplicationPeer(&roleTestRequester{})
	if _, err := application.DemoEcho(ctx, roleTestValue[DemoEchoRequest](roleTestRequests[MethodDemoEcho])); err != nil {
		t.Fatalf("Application.DemoEcho: %v", err)
	}
	empty, err := requestPeer[map[string]any](ctx, &roleTestRequester{empty: true}, &roleTestRequest{})
	if err != nil || empty == nil || len(*empty) != 0 {
		t.Fatalf("empty response = %#v, %v", empty, err)
	}
	boundary := &roleTestRequester{}
	if _, err := requestPeer[map[string]any](ctx, boundary, &roleTestInvalidRequest{}); !errors.Is(err, rtvbp.ErrRequestValidationFailed) || boundary.calls != 0 {
		t.Fatalf("invalid request error = %v, calls = %d", err, boundary.calls)
	}
}

func TestGeneratedRoleEventEmitters(t *testing.T) {
	ctx := context.Background()
	applicationNotifier := &roleTestNotifier{}
	application := NewApplicationEvents(applicationNotifier)
	if err := application.DemoObserved(ctx, roleTestValue[DemoObservedEvent](roleTestEvents[EventDemoObserved])); err != nil {
		t.Fatal(err)
	}
	voiceNotifier := &roleTestNotifier{}
	if got := len(applicationNotifier.names) + len(voiceNotifier.names); got != 1 {
		t.Fatalf("emitted event count = %d, want 1", got)
	}
	boundary := &roleTestNotifier{}
	if err := notifyEvent(ctx, boundary, &roleTestInvalidEvent{}); !errors.Is(err, rtvbp.ErrRequestValidationFailed) || len(boundary.names) != 0 {
		t.Fatalf("invalid event error = %v, notifications = %v", err, boundary.names)
	}
}

func TestGeneratedAdaptersPreserveUnknownHooks(t *testing.T) {
	registrations := ApplicationHandlers(&applicationRoleTestHandler{})
	registrations = append(registrations, ApplicationEventHandlers(&applicationRoleTestEventHandler{})...)
	defaultHandler := rtvbp.NewHandler(rtvbp.HandlerConfig{}, registrations...)
	err := defaultHandler.OnRequest(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Request{Method: "unknown.method"})
	var handlerError *rtvbp.HandlerError
	if !errors.As(err, &handlerError) || handlerError.WireError.Code != 501 {
		t.Fatalf("unknown method error = %#v", err)
	}
	if err := defaultHandler.OnEvent(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Event{Name: "unknown.event"}); err != nil {
		t.Fatalf("unknown event: %v", err)
	}

	methodHooked, eventHooked := false, false
	hooked := rtvbp.NewHandler(rtvbp.HandlerConfig{
		OnUnknownMethod: func(context.Context, rtvbp.SHC, rtvbp.Request) error { methodHooked = true; return rtvbp.NotImplemented("hooked") },
		OnUnknownEvent: func(context.Context, rtvbp.SHC, rtvbp.Event) error { eventHooked = true; return nil },
	}, registrations...)
	_ = hooked.OnRequest(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Request{Method: "unknown.method"})
	_ = hooked.OnEvent(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Event{Name: "unknown.event"})
	if !methodHooked || !eventHooked {
		t.Fatalf("hooks = method:%v event:%v", methodHooked, eventHooked)
	}
}
