// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package v1classic

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/babelforce/rtvbp/sdk/go"
)

const envelopeName = "classic.v1"

type constantSpec struct {
	name  string
	value string
}

type frameSpec struct {
	kind          rtvbp.Kind
	discriminator string
	id            string
	payload       string
	omitPayload   bool
	error         string
	omitError     bool
}

type errorSpec struct {
	code     string
	message  string
	data     string
	omitData bool
}

var constants = []constantSpec{
	{name: "version", value: "1"},
}

// Frame order is structural discrimination precedence.
var frames = []frameSpec{
	{kind: rtvbp.KindEvent, discriminator: "event", id: "id", payload: "data", omitPayload: true, error: "", omitError: true},
	{kind: rtvbp.KindRequest, discriminator: "method", id: "id", payload: "params", omitPayload: true, error: "", omitError: true},
	{kind: rtvbp.KindResponse, discriminator: "response", id: "", payload: "result", omitPayload: true, error: "error", omitError: true},
}

var wireError = errorSpec{
	code:     "code",
	message:  "message",
	data:     "any",
	omitData: true,
}

// Envelope implements the "classic.v1" envelope codec.
type Envelope struct{}

var _ rtvbp.Envelope = Envelope{}

// Name returns the envelope identifier.
func (Envelope) Name() string { return envelopeName }

// Encode projects one semantic frame into the envelope's ordered wire object.
// Raw payload and error-data JSON is preserved verbatim; fields irrelevant to Kind are ignored.
func (Envelope) Encode(frame rtvbp.ControlFrame) ([]byte, error) {
	shape, ok := frameForKind(frame.Kind)
	if !ok {
		return nil, fmt.Errorf("%s: unknown frame kind %d", envelopeName, frame.Kind)
	}

	fields := make([]wireField, 0, len(constants)+4)
	for _, constant := range constants {
		if err := appendValue(&fields, constant.name, constant.value); err != nil {
			return nil, err
		}
	}

	switch frame.Kind {
	case rtvbp.KindRequest, rtvbp.KindEvent:
		if frame.ID == "" {
			return nil, fmt.Errorf("%s: frame id is required", envelopeName)
		}
		if frame.Method == "" {
			return nil, fmt.Errorf("%s: frame method is required", envelopeName)
		}
		if err := appendValue(&fields, shape.id, frame.ID); err != nil {
			return nil, err
		}
		if err := appendValue(&fields, shape.discriminator, frame.Method); err != nil {
			return nil, err
		}
	case rtvbp.KindResponse:
		if frame.CorrelID == "" {
			return nil, fmt.Errorf("%s: response correlation id is required", envelopeName)
		}
		if err := appendValue(&fields, shape.discriminator, frame.CorrelID); err != nil {
			return nil, err
		}
	}

	if err := appendRaw(&fields, shape.payload, frame.Payload, shape.omitPayload); err != nil {
		return nil, err
	}
	if shape.error != "" {
		if frame.Err == nil {
			if err := appendRaw(&fields, shape.error, nil, shape.omitError); err != nil {
				return nil, err
			}
		} else {
			encoded, err := encodeError(frame.Err)
			if err != nil {
				return nil, err
			}
			if err := appendRaw(&fields, shape.error, encoded, shape.omitError); err != nil {
				return nil, err
			}
		}
	}
	return marshalObject(fields)
}

// Decode projects one envelope wire object into a semantic frame.
func (Envelope) Decode(data []byte) (rtvbp.ControlFrame, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil {
		return rtvbp.ControlFrame{}, fmt.Errorf("%s: invalid JSON: %w", envelopeName, err)
	}
	if object == nil {
		return rtvbp.ControlFrame{}, fmt.Errorf("%s: envelope must be an object", envelopeName)
	}
	for _, constant := range constants {
		value, err := requiredString(object, constant.name)
		if err != nil || value != constant.value {
			return rtvbp.ControlFrame{}, fmt.Errorf("%s: %s must equal %q", envelopeName, constant.name, constant.value)
		}
	}

	for _, shape := range frames {
		discriminator, ok := discriminatorString(object, shape.discriminator)
		if !ok {
			continue
		}
		frame := rtvbp.ControlFrame{Kind: shape.kind}
		if shape.kind == rtvbp.KindResponse {
			frame.CorrelID = discriminator
		} else {
			id, err := requiredString(object, shape.id)
			if err != nil {
				return rtvbp.ControlFrame{}, fmt.Errorf("%s: %w", envelopeName, err)
			}
			frame.ID = id
			frame.Method = discriminator
		}
		frame.Payload = optionalRaw(object, shape.payload)
		if shape.error != "" {
			raw, present := object[shape.error]
			if present && !bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
				decoded, err := decodeError(raw)
				if err != nil {
					return rtvbp.ControlFrame{}, err
				}
				frame.Err = decoded
			}
		}
		return frame, nil
	}
	return rtvbp.ControlFrame{}, fmt.Errorf("%s: envelope has no recognized frame discriminator", envelopeName)
}

type wireField struct {
	name  string
	value json.RawMessage
}

func frameForKind(kind rtvbp.Kind) (frameSpec, bool) {
	for _, frame := range frames {
		if frame.kind == kind {
			return frame, true
		}
	}
	return frameSpec{}, false
}

func appendValue(fields *[]wireField, name string, value any) error {
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Errorf("%s: encode %s: %w", envelopeName, name, err)
	}
	*fields = append(*fields, wireField{name: name, value: encoded})
	return nil
}

func appendRaw(fields *[]wireField, name string, value json.RawMessage, omitWhenNone bool) error {
	if value == nil {
		if omitWhenNone {
			return nil
		}
		value = json.RawMessage("null")
	}
	if len(value) == 0 || !json.Valid(value) {
		return fmt.Errorf("%s: %s contains invalid JSON", envelopeName, name)
	}
	*fields = append(*fields, wireField{name: name, value: value})
	return nil
}

func marshalObject(fields []wireField) ([]byte, error) {
	output := make([]byte, 0, 128)
	output = append(output, '{')
	for index, field := range fields {
		if index != 0 {
			output = append(output, ',')
		}
		name, err := json.Marshal(field.name)
		if err != nil {
			return nil, fmt.Errorf("%s: encode field name: %w", envelopeName, err)
		}
		output = append(output, name...)
		output = append(output, ':')
		output = append(output, field.value...)
	}
	output = append(output, '}')
	return output, nil
}

func encodeError(value *rtvbp.WireError) (json.RawMessage, error) {
	if value.Code == 0 {
		return nil, fmt.Errorf("%s: error code must be non-zero", envelopeName)
	}
	if value.Message == "" {
		return nil, fmt.Errorf("%s: error message is required", envelopeName)
	}
	fields := make([]wireField, 0, 3)
	if err := appendValue(&fields, wireError.code, value.Code); err != nil {
		return nil, err
	}
	if err := appendValue(&fields, wireError.message, value.Message); err != nil {
		return nil, err
	}
	if err := appendRaw(&fields, wireError.data, value.Data, wireError.omitData); err != nil {
		return nil, err
	}
	return marshalObject(fields)
}

func decodeError(data json.RawMessage) (*rtvbp.WireError, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err != nil || object == nil {
		return nil, fmt.Errorf("%s: error must be an object", envelopeName)
	}
	var code int
	encodedCode, ok := object[wireError.code]
	if !ok || json.Unmarshal(encodedCode, &code) != nil || code == 0 {
		return nil, fmt.Errorf("%s: error code must be a non-zero integer", envelopeName)
	}
	message, err := requiredString(object, wireError.message)
	if err != nil {
		return nil, fmt.Errorf("%s: error message is required", envelopeName)
	}
	return &rtvbp.WireError{
		Code:    code,
		Message: message,
		Data:    optionalRaw(object, wireError.data),
	}, nil
}

func requiredString(object map[string]json.RawMessage, name string) (string, error) {
	raw, ok := object[name]
	if !ok {
		return "", fmt.Errorf("%s is required", name)
	}
	var value string
	if err := json.Unmarshal(raw, &value); err != nil || value == "" {
		return "", fmt.Errorf("%s must be a non-empty string", name)
	}
	return value, nil
}

func discriminatorString(object map[string]json.RawMessage, name string) (string, bool) {
	raw, ok := object[name]
	if !ok {
		return "", false
	}
	var value string
	if json.Unmarshal(raw, &value) != nil || value == "" {
		return "", false
	}
	return value, true
}

func optionalRaw(object map[string]json.RawMessage, name string) json.RawMessage {
	raw, ok := object[name]
	if !ok {
		return nil
	}
	return append(json.RawMessage(nil), raw...)
}
