// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package v1classic

import (
	"bytes"
	"encoding/json"
	"reflect"
	"testing"
	"time"

	"github.com/babelforce/rtvbp/sdk/go"
)

var goldenFrames = []struct {
	name  string
	bytes []byte
	frame rtvbp.ControlFrame
}{
	{name: "envelope/classic.v1/event.json", bytes: []byte("{\"version\":\"1\",\"id\":\"event-1\",\"event\":\"dtmf\",\"data\":{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindEvent, ID: "event-1", Method: "dtmf", Payload: json.RawMessage("{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}")}},
	{name: "envelope/classic.v1/request-with-params.json", bytes: []byte("{\"version\":\"1\",\"id\":\"request-terminate-1\",\"method\":\"session.terminate\",\"params\":{\"reason\":\"completed\"}}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindRequest, ID: "request-terminate-1", Method: "session.terminate", Payload: json.RawMessage("{\"reason\":\"completed\"}")}},
	{name: "envelope/classic.v1/request.json", bytes: []byte("{\"version\":\"1\",\"id\":\"request-1\",\"method\":\"session.get\"}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindRequest, ID: "request-1", Method: "session.get", Payload: nil}},
	{name: "envelope/classic.v1/response-error-internal.json", bytes: []byte("{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":500,\"message\":\"internal failure\"}}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindResponse, CorrelID: "request-1", Payload: nil, Err: &rtvbp.WireError{Code: 500, Message: "internal failure", Data: nil}}},
	{name: "envelope/classic.v1/response-error-not-implemented.json", bytes: []byte("{\"version\":\"1\",\"response\":\"request-terminate-1\",\"error\":{\"code\":501,\"message\":\"session.terminate is not supported. please use application.move or call.hangup instead\"}}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindResponse, CorrelID: "request-terminate-1", Payload: nil, Err: &rtvbp.WireError{Code: 501, Message: "session.terminate is not supported. please use application.move or call.hangup instead", Data: nil}}},
	{name: "envelope/classic.v1/response-error-unknown.json", bytes: []byte("{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":-1,\"message\":\"unknown failure\"}}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindResponse, CorrelID: "request-1", Payload: nil, Err: &rtvbp.WireError{Code: -1, Message: "unknown failure", Data: nil}}},
	{name: "envelope/classic.v1/response-error.json", bytes: []byte("{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":400,\"message\":\"invalid request\",\"any\":{\"field\":\"reason\",\"retryable\":false}}}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindResponse, CorrelID: "request-1", Payload: nil, Err: &rtvbp.WireError{Code: 400, Message: "invalid request", Data: json.RawMessage("{\"field\":\"reason\",\"retryable\":false}")}}},
	{name: "envelope/classic.v1/response-ok-no-result.json", bytes: []byte("{\"version\":\"1\",\"response\":\"request-1\"}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindResponse, CorrelID: "request-1", Payload: nil, Err: nil}},
	{name: "envelope/classic.v1/response-ok-null-result.json", bytes: []byte("{\"version\":\"1\",\"response\":\"request-1\",\"result\":null}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindResponse, CorrelID: "request-1", Payload: json.RawMessage("null"), Err: nil}},
	{name: "envelope/classic.v1/response-ok.json", bytes: []byte("{\"version\":\"1\",\"response\":\"request-1\",\"result\":{}}"), frame: rtvbp.ControlFrame{Kind: rtvbp.KindResponse, CorrelID: "request-1", Payload: json.RawMessage("{}"), Err: nil}},
}

func TestGoldenFrames(t *testing.T) {
	envelope := Envelope{}
	if got := envelope.Name(); got != envelopeName {
		t.Fatalf("Name() = %q, want %q", got, envelopeName)
	}
	for _, tc := range goldenFrames {
		t.Run(tc.name+"/encode", func(t *testing.T) {
			actual, err := envelope.Encode(tc.frame)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(actual, tc.bytes) {
				t.Fatalf("encode mismatch\nwant: %s\n got: %s", tc.bytes, actual)
			}
		})
		t.Run(tc.name+"/decode", func(t *testing.T) {
			actual, err := envelope.Decode(tc.bytes)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(actual, tc.frame) {
				t.Fatalf("decode mismatch\nwant: %#v\n got: %#v", tc.frame, actual)
			}
		})
	}
}

func TestStructuralPrecedenceAndMalformedInput(t *testing.T) {
	envelope := Envelope{}
	frame, err := envelope.Decode([]byte("{\"version\":\"1\",\"id\":\"first-id\",\"event\":\"first\",\"method\":\"second\"}"))
	if err != nil {
		t.Fatal(err)
	}
	if frame.Kind != rtvbp.KindEvent || frame.Method != "first" {
		t.Fatalf("precedence decoded %#v", frame)
	}
	if _, err := envelope.Decode([]byte("not json")); err == nil {
		t.Fatal("malformed input decoded without error")
	}
}

func TestResponseAllowsResultAndError(t *testing.T) {
	envelope := Envelope{}
	wire := []byte("{\"version\":\"1\",\"response\":\"request-1\",\"result\":{},\"error\":{\"code\":500,\"message\":\"failed\"}}")
	frame, err := envelope.Decode(wire)
	if err != nil {
		t.Fatal(err)
	}
	if frame.Kind != rtvbp.KindResponse || string(frame.Payload) != "{}" || frame.Err == nil || frame.Err.Code != 500 {
		t.Fatalf("decoded %#v", frame)
	}
	encoded, err := envelope.Encode(frame)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(encoded, wire) {
		t.Fatalf("round-trip mismatch\nwant: %s\n got: %s", wire, encoded)
	}
}

func TestDiscriminatorFallbackAndDecodeValidation(t *testing.T) {
	envelope := Envelope{}
	event := testFrame(t, rtvbp.KindEvent)
	request := testFrame(t, rtvbp.KindRequest)
	response := testFrame(t, rtvbp.KindResponse)

	frame, err := envelope.Decode(testWire(t,
		wireField{name: event.discriminator, value: testJSON(t, 7)},
		wireField{name: request.id, value: testJSON(t, "request-1")},
		wireField{name: request.discriminator, value: testJSON(t, "ping")},
		wireField{name: response.discriminator, value: testJSON(t, "ignored")},
	))
	if err != nil {
		t.Fatal(err)
	}
	if frame.Kind != rtvbp.KindRequest || frame.Method != "ping" {
		t.Fatalf("non-string discriminator did not fall through: %#v", frame)
	}

	frame, err = envelope.Decode(testWire(t,
		wireField{name: request.id, value: testJSON(t, "request-1")},
		wireField{name: request.discriminator, value: testJSON(t, "ping")},
		wireField{name: response.discriminator, value: testJSON(t, "ignored")},
	))
	if err != nil || frame.Kind != rtvbp.KindRequest {
		t.Fatalf("request did not beat response: %#v, %v", frame, err)
	}

	invalid := [][]byte{
		[]byte("[]"),
		testWire(t),
		testWire(t, wireField{name: request.discriminator, value: testJSON(t, "ping")}),
	}
	if len(constants) != 0 {
		wrong := testBaseFields(t)
		wrong[0].value = testJSON(t, "wrong")
		invalid = append(invalid, testObject(t, wrong...))
		invalid = append(invalid, testObject(t,
			wireField{name: request.id, value: testJSON(t, "request-1")},
			wireField{name: request.discriminator, value: testJSON(t, "ping")},
		))
	}
	for _, wire := range invalid {
		if _, err := envelope.Decode(wire); err == nil {
			t.Fatalf("invalid envelope decoded: %s", wire)
		}
	}
}

func TestErrorNullDataAndValidation(t *testing.T) {
	envelope := Envelope{}
	response := testFrame(t, rtvbp.KindResponse)
	correlation := wireField{name: response.discriminator, value: testJSON(t, "request-1")}

	if response.omitPayload && response.omitError {
		withNull := testWire(t, correlation, wireField{name: response.error, value: json.RawMessage("null")})
		frame, err := envelope.Decode(withNull)
		if err != nil || frame.Err != nil {
			t.Fatalf("error:null decoded as %#v, %v", frame, err)
		}
		encoded, err := envelope.Encode(frame)
		if err != nil {
			t.Fatal(err)
		}
		if want := testWire(t, correlation); !bytes.Equal(encoded, want) {
			t.Fatalf("error:null normalization mismatch\nwant: %s\n got: %s", want, encoded)
		}
	}

	errorWithNullData := testObject(t,
		wireField{name: wireError.code, value: testJSON(t, 777)},
		wireField{name: wireError.message, value: testJSON(t, "extension")},
		wireField{name: wireError.data, value: json.RawMessage("null")},
	)
	wire := testWire(t, correlation, wireField{name: response.error, value: errorWithNullData})
	frame, err := envelope.Decode(wire)
	if err != nil || frame.Err == nil || frame.Err.Code != 777 || string(frame.Err.Data) != "null" {
		t.Fatalf("unknown error with null data decoded as %#v, %v", frame, err)
	}
	encoded, err := envelope.Encode(frame)
	if err != nil || !bytes.Equal(encoded, wire) {
		t.Fatalf("null error data round-trip mismatch: %s, %v", encoded, err)
	}

	invalidErrors := []json.RawMessage{
		json.RawMessage("[]"),
		testObject(t),
		testObject(t,
			wireField{name: wireError.code, value: testJSON(t, 0)},
			wireField{name: wireError.message, value: testJSON(t, "unset")},
		),
		testObject(t,
			wireField{name: wireError.code, value: testJSON(t, "bad")},
			wireField{name: wireError.message, value: testJSON(t, "failed")},
		),
		testObject(t, wireField{name: wireError.code, value: testJSON(t, 500)}),
		testObject(t,
			wireField{name: wireError.code, value: testJSON(t, 500)},
			wireField{name: wireError.message, value: testJSON(t, "")},
		),
		testObject(t,
			wireField{name: wireError.code, value: testJSON(t, 500)},
			wireField{name: wireError.message, value: testJSON(t, 7)},
		),
	}
	for _, invalidError := range invalidErrors {
		wire := testWire(t, correlation, wireField{name: response.error, value: invalidError})
		if _, err := envelope.Decode(wire); err == nil {
			t.Fatalf("invalid error decoded: %s", wire)
		}
	}
}

func TestEncodeValidationAndReceiveTimestamp(t *testing.T) {
	envelope := Envelope{}
	invalid := []rtvbp.ControlFrame{
		{},
		{Kind: rtvbp.KindRequest, Method: "ping"},
		{Kind: rtvbp.KindRequest, ID: "request-1"},
		{Kind: rtvbp.KindEvent, Method: "ready"},
		{Kind: rtvbp.KindResponse},
		{Kind: rtvbp.KindResponse, CorrelID: "request-1", Err: &rtvbp.WireError{Code: 0, Message: "unset"}},
		{Kind: rtvbp.KindResponse, CorrelID: "request-1", Err: &rtvbp.WireError{Code: 500}},
		{Kind: rtvbp.KindResponse, CorrelID: "request-1", Payload: json.RawMessage{}},
		{Kind: rtvbp.KindResponse, CorrelID: "request-1", Err: &rtvbp.WireError{Code: 500, Message: "failed", Data: json.RawMessage{}}},
	}
	for _, frame := range invalid {
		if _, err := envelope.Encode(frame); err == nil {
			t.Fatalf("invalid frame encoded: %#v", frame)
		}
	}

	if len(goldenFrames) != 0 {
		frame := goldenFrames[0].frame
		frame.ReceivedAt = time.Unix(123, 456)
		encoded, err := envelope.Encode(frame)
		if err != nil || !bytes.Equal(encoded, goldenFrames[0].bytes) {
			t.Fatalf("ReceivedAt changed encoding: %s, %v", encoded, err)
		}
	}
}

func testFrame(t *testing.T, kind rtvbp.Kind) frameSpec {
	t.Helper()
	frame, ok := frameForKind(kind)
	if !ok {
		t.Fatalf("missing frame kind %d", kind)
	}
	return frame
}

func testBaseFields(t *testing.T) []wireField {
	t.Helper()
	fields := make([]wireField, 0, len(constants))
	for _, constant := range constants {
		fields = append(fields, wireField{name: constant.name, value: testJSON(t, constant.value)})
	}
	return fields
}

func testWire(t *testing.T, fields ...wireField) []byte {
	t.Helper()
	all := append(testBaseFields(t), fields...)
	return testObject(t, all...)
}

func testObject(t *testing.T, fields ...wireField) json.RawMessage {
	t.Helper()
	wire, err := marshalObject(fields)
	if err != nil {
		t.Fatal(err)
	}
	return wire
}

func testJSON(t *testing.T, value any) json.RawMessage {
	t.Helper()
	wire, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	return wire
}
