# fly.toml app configuration file generated for babelforce-rtvbp-demo on 2025-06-18T09:19:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'babelforce-rtvbp-demo'
primary_region = 'fra'

[build]
  image = 'ghcr.io/babelforce/rtvbp:main'

[deploy]
  strategy = 'immediate'

[env]
  PORT = '8181'
  RUST_LOG = 'info'

[processes]
  app = 'server'

[http_service]
  internal_port = 8181
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    hard_limit = 10
    soft_limit = 5

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256'
  cpus = 1
