// Code generated by rtvbp-spec-gen from the typed profile registry. DO NOT EDIT.

package profile

const ProfileRtvbpV1 = "rtvbp.v1"
const ProfileRtvbpDemoV1 = "rtvbp.demo.v1"
const ProfileRtvbpWebrtcV1 = "rtvbp.webrtc.v1"
const SignalingTransportWebrtcOffer = "transport.webrtc.offer"
const Default = ProfileRtvbpV1
const Headerless = ProfileRtvbpV1

// Descriptor is the generated transport/envelope/catalog composition for one profile.
type Descriptor struct {
	ID        string
	Token     string
	Transport string
	Envelope  string
	Catalog   string
	Signaling []string
	Media     []Media
}

// Media is one generated profile media constraint.
type Media struct {
	Channel    string
	Carrier    string
	WireFormat string
	SDKFormat  string
}

var descriptors = []Descriptor{
	{ID: "rtvbp.v1", Token: "rtvbp.v1", Transport: "ws.v1", Envelope: "classic.v1", Catalog: "babelforce.v1", Signaling: []string{}, Media: []Media{{Channel: "audio", Carrier: "websocket-binary", WireFormat: "l16-8000-16-1-20ms", SDKFormat: "l16-8000-16-1-20ms"}}},
	{ID: "rtvbp.demo.v1", Token: "rtvbp.demo.v1", Transport: "ws.v1", Envelope: "classic.v1", Catalog: "demo.v1", Signaling: []string{}, Media: []Media{}},
	{ID: "rtvbp.webrtc.v1", Token: "rtvbp.webrtc.v1", Transport: "webrtcws.v1", Envelope: "classic.v1", Catalog: "babelforce.v1", Signaling: []string{"transport.webrtc.offer"}, Media: []Media{{Channel: "audio", Carrier: "webrtc-rtp", WireFormat: "pcmu-8000-8-1-20ms", SDKFormat: "l16-8000-16-1-20ms"}}},
}

// ServerPreference returns profile tokens in accepting-endpoint preference order.
func ServerPreference() []string {
	return []string{ProfileRtvbpV1, ProfileRtvbpDemoV1, ProfileRtvbpWebrtcV1}
}

// All returns a copy of every generated profile descriptor.
func All() []Descriptor {
	return append([]Descriptor(nil), descriptors...)
}
