// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

// Generated `classic.v1` envelope codec.

use serde::ser::{SerializeMap, Serializer};
use serde_json::Value;

#[derive(Clone, Copy)]
struct FieldSpec {
    name: &'static str,
    omit_when_none: bool,
}

#[derive(Clone, Copy)]
struct FrameSpec {
    kind: crate::FrameKind,
    discriminator: FieldSpec,
    id: Option<FieldSpec>,
    payload: FieldSpec,
    error: Option<FieldSpec>,
}

#[derive(Clone, Copy)]
struct ErrorSpec {
    code: FieldSpec,
    message: FieldSpec,
    data: FieldSpec,
}

const ENVELOPE_NAME: &str = "classic.v1";
const CONSTANTS: &[(&str, &str)] = &[
    ("version", "1"),
];
const FRAMES: &[FrameSpec] = &[
    FrameSpec { kind: crate::FrameKind::Event, discriminator: FieldSpec { name: "event", omit_when_none: false }, id: Some(FieldSpec { name: "id", omit_when_none: false }), payload: FieldSpec { name: "data", omit_when_none: true }, error: None },
    FrameSpec { kind: crate::FrameKind::Request, discriminator: FieldSpec { name: "method", omit_when_none: false }, id: Some(FieldSpec { name: "id", omit_when_none: false }), payload: FieldSpec { name: "params", omit_when_none: true }, error: None },
    FrameSpec { kind: crate::FrameKind::Response, discriminator: FieldSpec { name: "response", omit_when_none: false }, id: None, payload: FieldSpec { name: "result", omit_when_none: true }, error: Some(FieldSpec { name: "error", omit_when_none: true }) },
];
const ERROR: ErrorSpec = ErrorSpec { code: FieldSpec { name: "code", omit_when_none: false }, message: FieldSpec { name: "message", omit_when_none: false }, data: FieldSpec { name: "any", omit_when_none: true } };

/// The generated envelope implementation.
#[derive(Clone, Copy, Debug, Default)]
pub struct Envelope;

impl crate::Envelope for Envelope {
    fn name(&self) -> &'static str { ENVELOPE_NAME }

    fn encode(&self, frame: &crate::ControlFrame) -> Result<Vec<u8>, crate::Error> {
        validate_frame(frame)?;
        let mut bytes = Vec::new();
        let mut serializer = serde_json::Serializer::new(&mut bytes);
        let mut object = serializer
            .serialize_map(None)
            .map_err(crate::Error::envelope)?;
        for (name, value) in CONSTANTS {
            object.serialize_entry(name, value).map_err(crate::Error::envelope)?;
        }
        let shape = frame_spec(frame.kind)?;
        match frame.kind {
            crate::FrameKind::Request | crate::FrameKind::Event => {
                let id = shape.id.ok_or_else(|| crate::Error::envelope_message("frame id mapping is missing"))?;
                object.serialize_entry(id.name, &frame.id).map_err(crate::Error::envelope)?;
                object.serialize_entry(shape.discriminator.name, &frame.method).map_err(crate::Error::envelope)?;
                serialize_optional(&mut object, shape.payload, frame.payload.as_ref())?;
            }
            crate::FrameKind::Response => {
                object.serialize_entry(shape.discriminator.name, &frame.correlation_id).map_err(crate::Error::envelope)?;
                serialize_optional(&mut object, shape.payload, frame.payload.as_ref())?;
                let error_field = shape.error.ok_or_else(|| crate::Error::envelope_message("response error mapping is missing"))?;
                match frame.error.as_ref() {
                    Some(error) => {
                        validate_wire_error(error)?;
                        let mut encoded = serde_json::Map::new();
                        encoded.insert(ERROR.code.name.to_owned(), Value::from(error.code));
                        encoded.insert(ERROR.message.name.to_owned(), Value::from(error.message.clone()));
                        if let Some(data) = error.data.as_ref() {
                            encoded.insert(ERROR.data.name.to_owned(), data.clone());
                        } else if !ERROR.data.omit_when_none {
                            encoded.insert(ERROR.data.name.to_owned(), Value::Null);
                        }
                        object.serialize_entry(error_field.name, &encoded).map_err(crate::Error::envelope)?;
                    }
                    None if !error_field.omit_when_none => {
                        object.serialize_entry(error_field.name, &Value::Null).map_err(crate::Error::envelope)?;
                    }
                    None => {}
                }
            }
        }
        object.end().map_err(crate::Error::envelope)?;
        Ok(bytes)
    }

    fn decode(&self, bytes: &[u8]) -> Result<crate::ControlFrame, crate::Error> {
        let value: Value = serde_json::from_slice(bytes).map_err(crate::Error::envelope)?;
        let object = value
            .as_object()
            .ok_or_else(|| crate::Error::envelope_message("envelope must be an object"))?;
        for (name, expected) in CONSTANTS {
            if object.get(*name).and_then(Value::as_str) != Some(*expected) {
                return Err(crate::Error::envelope_message(format!("{name} must equal {expected:?}")));
            }
        }
        for shape in FRAMES {
            let Some(discriminator) = object
                .get(shape.discriminator.name)
                .and_then(Value::as_str)
                .filter(|value| !value.is_empty())
            else {
                continue;
            };
            return match shape.kind {
                crate::FrameKind::Request => Ok(crate::ControlFrame::request(
                    required_id(object, *shape, "request")?,
                    discriminator,
                    optional_value(object, shape.payload),
                )),
                crate::FrameKind::Event => Ok(crate::ControlFrame::event(
                    required_id(object, *shape, "event")?,
                    discriminator,
                    optional_value(object, shape.payload),
                )),
                crate::FrameKind::Response => Ok(crate::ControlFrame::response(
                    discriminator,
                    optional_value(object, shape.payload),
                    decode_error(object, *shape)?,
                )),
            };
        }
        Err(crate::Error::envelope_message(
            "envelope has no recognized frame discriminator",
        ))
    }
}

fn frame_spec(kind: crate::FrameKind) -> Result<FrameSpec, crate::Error> {
    FRAMES
        .iter()
        .copied()
        .find(|frame| frame.kind == kind)
        .ok_or_else(|| crate::Error::envelope_message("frame mapping is missing"))
}

fn validate_frame(frame: &crate::ControlFrame) -> Result<(), crate::Error> {
    match frame.kind {
        crate::FrameKind::Request | crate::FrameKind::Event => {
            if frame.id.is_empty() || frame.method.is_empty() {
                return Err(crate::Error::envelope_message("request/event id and method are required"));
            }
        }
        crate::FrameKind::Response if frame.correlation_id.is_empty() => {
            return Err(crate::Error::envelope_message("response correlation id is required"));
        }
        crate::FrameKind::Response => {}
    }
    Ok(())
}

fn validate_wire_error(error: &crate::WireError) -> Result<(), crate::Error> {
    if error.code == 0 || error.message.is_empty() {
        return Err(crate::Error::envelope_message("error code must be non-zero and message is required"));
    }
    Ok(())
}

fn serialize_optional<M>(
    object: &mut M,
    field: FieldSpec,
    value: Option<&Value>,
) -> Result<(), crate::Error>
where
    M: SerializeMap,
    M::Error: std::error::Error + Send + Sync + 'static,
{
    match value {
        Some(value) => object.serialize_entry(field.name, value).map_err(crate::Error::envelope),
        None if !field.omit_when_none => object.serialize_entry(field.name, &Value::Null).map_err(crate::Error::envelope),
        None => Ok(()),
    }
}

fn optional_value(object: &serde_json::Map<String, Value>, field: FieldSpec) -> Option<Value> {
    object.get(field.name).cloned()
}

fn required_id(
    object: &serde_json::Map<String, Value>,
    shape: FrameSpec,
    kind: &str,
) -> Result<String, crate::Error> {
    let field = shape.id.ok_or_else(|| crate::Error::envelope_message(format!("{kind} id mapping is missing")))?;
    object
        .get(field.name)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
        .map(str::to_owned)
        .ok_or_else(|| crate::Error::envelope_message(format!("{kind} id is required")))
}

fn decode_error(
    object: &serde_json::Map<String, Value>,
    shape: FrameSpec,
) -> Result<Option<crate::WireError>, crate::Error> {
    let Some(value) = shape.error.and_then(|field| object.get(field.name)) else {
        return Ok(None);
    };
    if value.is_null() {
        return Ok(None);
    }
    let error = value
        .as_object()
        .ok_or_else(|| crate::Error::envelope_message("error must be an object"))?;
    let code = error
        .get(ERROR.code.name)
        .and_then(Value::as_i64)
        .filter(|code| *code != 0)
        .ok_or_else(|| crate::Error::envelope_message("error code must be a non-zero integer"))?;
    let message = error
        .get(ERROR.message.name)
        .and_then(Value::as_str)
        .filter(|message| !message.is_empty())
        .ok_or_else(|| crate::Error::envelope_message("error message is required"))?;
    Ok(Some(crate::WireError {
        code,
        message: message.to_owned(),
        data: optional_value(error, ERROR.data),
    }))
}
