use std::collections::{BTreeMap, BTreeSet, HashSet, VecDeque};
use std::fmt::Write as _;
use std::path::PathBuf;

use rtvbp_spec_model::{EnvelopeSpec, FrameKind, Role, Scenario, ScenarioStep};
use serde_json::{Value, json};
use thiserror::Error;

use super::GeneratedFile;
use crate::resolve::{ResolvedCatalog, ResolvedEvent, ResolvedOperation};

const PAGE_BANNER: &str = "{/* Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT. */}\n\n";

#[derive(Debug, Error)]
pub enum DocsEmitError {
    #[error("documentation item name {name:?} cannot be used as a page name")]
    UnsafePageName { name: String },
    #[error("schema {schema:?}: {message}")]
    Schema { schema: String, message: String },
    #[error("scenario {scenario:?}: {message}")]
    Scenario { scenario: String, message: String },
    #[error("could not encode generated documentation metadata: {0}")]
    Json(#[from] serde_json::Error),
}

pub fn emit_docs(
    catalog: &ResolvedCatalog,
    envelopes: &[EnvelopeSpec],
) -> Result<Vec<GeneratedFile>, DocsEmitError> {
    let catalog_id = catalog.id.to_string();
    page_name(&catalog_id)?;
    let mut files = vec![GeneratedFile {
        path: PathBuf::from(&catalog_id).join("_category_.json"),
        bytes: category(&catalog_id)?.into_bytes(),
    }];

    for operation in &catalog.operations {
        page_name(&operation.method)?;
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("operations")
                .join(format!("{}.mdx", operation.method)),
            bytes: operation_page(catalog, operation)?.into_bytes(),
        });
    }
    for event in &catalog.events {
        page_name(&event.name)?;
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("events")
                .join(format!("{}.mdx", event.name)),
            bytes: event_page(catalog, event)?.into_bytes(),
        });
    }
    if !catalog.scenarios.is_empty() {
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("flows")
                .join("_category_.json"),
            bytes: flow_category(&catalog_id)?.into_bytes(),
        });
    }
    for scenario in &catalog.scenarios {
        page_name(&scenario.name)?;
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("flows")
                .join(format!("{}.mdx", scenario.name)),
            bytes: flow_page(catalog, scenario)?.into_bytes(),
        });
    }
    for role in [Role::Application, Role::Voice] {
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("roles")
                .join(format!("{role}.mdx")),
            bytes: role_page(catalog, role).into_bytes(),
        });
    }
    for envelope in envelopes {
        let slug = envelope.id.replace('.', "-");
        page_name(&slug)?;
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("envelopes")
                .join(format!("{slug}.mdx")),
            bytes: envelope_page(envelope).into_bytes(),
        });
    }
    Ok(files)
}

fn category(catalog_id: &str) -> Result<String, DocsEmitError> {
    let mut output = serde_json::to_string_pretty(&json!({
        "label": catalog_id,
        "link": {
            "type": "generated-index",
            "description": format!("Generated reference for the {catalog_id} payload catalog.")
        }
    }))?;
    output.push('\n');
    Ok(output)
}

fn flow_category(catalog_id: &str) -> Result<String, DocsEmitError> {
    let mut output = serde_json::to_string_pretty(&json!({
        "label": "Flows",
        "link": {
            "type": "generated-index",
            "description": format!(
                "Generated sequence diagrams for typed {catalog_id} conformance scenarios."
            )
        }
    }))?;
    output.push('\n');
    Ok(output)
}

fn operation_page(
    catalog: &ResolvedCatalog,
    operation: &ResolvedOperation,
) -> Result<String, DocsEmitError> {
    let mut output = page_header(&operation.method, &operation.method);
    let direction = direction_to_handler(operation.handled_by);
    writeln!(
        output,
        "<span className=\"badge badge--secondary\">{direction}</span>\n"
    )
    .unwrap();
    writeln!(output, "{}\n", escape_mdx(&operation.docs)).unwrap();
    if operation.terminal {
        output.push_str(
            "This is a terminal operation: after a successful response, the session closes.\n\n",
        );
    }

    render_schema_table(&mut output, catalog, &operation.request, "Parameters", 2)?;
    render_schema_table(&mut output, catalog, &operation.response, "Result", 2)?;
    render_referenced_types(
        &mut output,
        catalog,
        [&operation.request, &operation.response],
    )?;
    for example in &operation.examples {
        writeln!(output, "## Example: {}\n", escape_mdx(&example.name)).unwrap();
        output.push_str("### Parameters\n\n```json\n");
        output.push_str(&serde_json::to_string_pretty(&example.request)?);
        output.push_str("\n```\n\n### Result\n\n```json\n");
        output.push_str(&serde_json::to_string_pretty(&example.response)?);
        output.push_str("\n```\n\n");
    }
    Ok(finish(output))
}

fn event_page(catalog: &ResolvedCatalog, event: &ResolvedEvent) -> Result<String, DocsEmitError> {
    let mut output = page_header(&event.name, &event.name);
    let direction = direction_from_emitter(event.emitted_by);
    writeln!(
        output,
        "<span className=\"badge badge--secondary\">{direction}</span>\n"
    )
    .unwrap();
    writeln!(output, "{}\n", escape_mdx(&event.docs)).unwrap();
    render_schema_table(&mut output, catalog, &event.data, "Data", 2)?;
    render_referenced_types(&mut output, catalog, [&event.data])?;
    for example in &event.examples {
        writeln!(output, "## Example: {}\n", escape_mdx(&example.name)).unwrap();
        output.push_str("```json\n");
        output.push_str(&serde_json::to_string_pretty(&example.data)?);
        output.push_str("\n```\n\n");
    }
    Ok(finish(output))
}

fn flow_page(catalog: &ResolvedCatalog, scenario: &Scenario) -> Result<String, DocsEmitError> {
    let title = display_name(&scenario.name);
    let mut output = page_header(&title, &title);
    writeln!(output, "{}\n", escape_mdx(&scenario.description)).unwrap();

    let mut operations = BTreeSet::new();
    let mut events = BTreeSet::new();
    for case in &scenario.cases {
        writeln!(output, "## {}\n", display_name(&case.name)).unwrap();
        writeln!(output, "{}\n", escape_mdx(&case.description)).unwrap();
        output.push_str("```mermaid\nsequenceDiagram\n");
        output.push_str("    participant voice as Voice peer\n");
        output.push_str("    participant application as Application peer\n\n");

        let mut requests = BTreeMap::new();
        for step in &case.steps {
            match step {
                ScenarioStep::Request {
                    from, id, method, ..
                } => {
                    let sender = scenario_role(scenario, from)?;
                    let receiver = peer(sender);
                    writeln!(output, "    {sender}->>{receiver}: REQ {method}").unwrap();
                    requests.insert(id.as_str(), (method.as_str(), sender));
                    operations.insert(method.as_str());
                }
                ScenarioStep::Response {
                    from,
                    response,
                    error,
                    ..
                } => {
                    let sender = scenario_role(scenario, from)?;
                    let Some((method, requester)) = requests.remove(response.as_str()) else {
                        return Err(DocsEmitError::Scenario {
                            scenario: scenario.name.clone(),
                            message: format!(
                                "response references unknown request binding {response:?}"
                            ),
                        });
                    };
                    let label = if let Some(error) = error {
                        format!("ERR {method} ({})", error.code)
                    } else {
                        format!("RES {method}")
                    };
                    writeln!(output, "    {sender}-->>{requester}: {label}").unwrap();
                }
                ScenarioStep::Event { from, event, .. } => {
                    let sender = scenario_role(scenario, from)?;
                    let receiver = peer(sender);
                    writeln!(output, "    {sender}-->>{receiver}: EVT {event}").unwrap();
                    events.insert(event.as_str());
                }
            }
        }
        output.push_str("```\n\n");
    }

    output.push_str("## Messages\n\n");
    for method in operations {
        let description = catalog
            .operations
            .iter()
            .find(|operation| operation.method == method)
            .map_or("", |operation| operation.docs.as_str());
        writeln!(
            output,
            "- [`{method}`](../operations/{method}.mdx) — {}",
            escape_mdx(description)
        )
        .unwrap();
    }
    for event in events {
        let description = catalog
            .events
            .iter()
            .find(|item| item.name == event)
            .map_or("", |item| item.docs.as_str());
        writeln!(
            output,
            "- [`{event}`](../events/{event}.mdx) — {}",
            escape_mdx(description)
        )
        .unwrap();
    }
    Ok(finish(output))
}

fn scenario_role(scenario: &Scenario, peer_name: &str) -> Result<Role, DocsEmitError> {
    scenario
        .roles
        .get(peer_name)
        .copied()
        .ok_or_else(|| DocsEmitError::Scenario {
            scenario: scenario.name.clone(),
            message: format!("step references unknown peer {peer_name:?}"),
        })
}

fn role_page(catalog: &ResolvedCatalog, role: Role) -> String {
    let title = format!("{} role", title_case(&role.to_string()));
    let mut output = page_header(&title, &role.to_string());
    writeln!(
        output,
        "The **{role}** peer implements operations directed to it, may call operations implemented by its peer, emits its own events, and receives peer events.\n"
    )
    .unwrap();

    render_operation_links(
        &mut output,
        "Must implement",
        catalog
            .operations
            .iter()
            .filter(|item| role_owns(role, item.handled_by)),
    );
    render_operation_links(
        &mut output,
        "May call",
        catalog
            .operations
            .iter()
            .filter(|item| role_owns(peer(role), item.handled_by)),
    );
    render_event_links(
        &mut output,
        "Emits",
        catalog
            .events
            .iter()
            .filter(|item| role_owns(role, item.emitted_by)),
    );
    render_event_links(
        &mut output,
        "Receives",
        catalog
            .events
            .iter()
            .filter(|item| role_owns(peer(role), item.emitted_by)),
    );
    finish(output)
}

fn render_operation_links<'a>(
    output: &mut String,
    heading: &str,
    items: impl Iterator<Item = &'a ResolvedOperation>,
) {
    writeln!(output, "## {heading}\n").unwrap();
    let mut empty = true;
    for item in items {
        empty = false;
        writeln!(
            output,
            "- [`{}`](../operations/{}.mdx) — {}",
            item.method,
            item.method,
            escape_mdx(&item.docs)
        )
        .unwrap();
    }
    if empty {
        output.push_str("_None._\n");
    }
    output.push('\n');
}

fn render_event_links<'a>(
    output: &mut String,
    heading: &str,
    items: impl Iterator<Item = &'a ResolvedEvent>,
) {
    writeln!(output, "## {heading}\n").unwrap();
    let mut empty = true;
    for item in items {
        empty = false;
        writeln!(
            output,
            "- [`{}`](../events/{}.mdx) — {}",
            item.name,
            item.name,
            escape_mdx(&item.docs)
        )
        .unwrap();
    }
    if empty {
        output.push_str("_None._\n");
    }
    output.push('\n');
}

fn render_schema_table(
    output: &mut String,
    catalog: &ResolvedCatalog,
    schema_name: &str,
    heading: &str,
    heading_level: usize,
) -> Result<(), DocsEmitError> {
    writeln!(output, "{} {heading}\n", "#".repeat(heading_level)).unwrap();
    output.push_str("| Field | Type | Presence | Constraints | Description |\n| --- | --- | --- | --- | --- |\n");
    let schema = catalog
        .schemas
        .get(schema_name)
        .ok_or_else(|| DocsEmitError::Schema {
            schema: schema_name.to_owned(),
            message: "schema is missing from the resolved registry".to_owned(),
        })?;
    let object = schema.as_object().ok_or_else(|| DocsEmitError::Schema {
        schema: schema_name.to_owned(),
        message: "schema root is not an object".to_owned(),
    })?;
    let Some(properties) = object.get("properties").and_then(Value::as_object) else {
        output.push_str("| _(value)_ | `");
        output.push_str(&schema_type(schema));
        output.push_str("` | required | — | — |\n\n");
        return Ok(());
    };
    if properties.is_empty() {
        output.push_str("| _(none)_ | — | — | — | Empty object. |\n\n");
        return Ok(());
    }
    let required = object
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<HashSet<_>>();
    for (name, field) in properties {
        let presence = field_presence(field, required.contains(name.as_str()));
        let description = field
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or("—");
        let constraints = field_constraints(field);
        writeln!(
            output,
            "| `{}` | `{}` | {} | {} | {} |",
            escape_table(name),
            escape_table(&schema_type(field)),
            presence,
            constraints,
            escape_table(description)
        )
        .unwrap();
    }
    output.push('\n');
    if let Some(orders) = object.get("x-rtvbp-field-order").and_then(Value::as_array) {
        output.push_str("**Cross-field constraints:** ");
        let constraints = orders
            .iter()
            .filter_map(|order| {
                Some(format!(
                    "`{}` ≤ `{}`",
                    order.get("lower")?.as_str()?,
                    order.get("upper")?.as_str()?
                ))
            })
            .collect::<Vec<_>>();
        output.push_str(&constraints.join(", "));
        output.push_str(".\n\n");
    }
    Ok(())
}

fn render_referenced_types<'a>(
    output: &mut String,
    catalog: &ResolvedCatalog,
    roots: impl IntoIterator<Item = &'a String>,
) -> Result<(), DocsEmitError> {
    let mut queued = VecDeque::new();
    for root in roots {
        let schema = catalog
            .schemas
            .get(root)
            .ok_or_else(|| DocsEmitError::Schema {
                schema: root.clone(),
                message: "schema is missing from the resolved registry".to_owned(),
            })?;
        collect_direct_references(schema, &mut queued);
    }
    let mut references = BTreeSet::new();
    while let Some(name) = queued.pop_front() {
        if !references.insert(name.clone()) {
            continue;
        }
        let schema = catalog
            .schemas
            .get(&name)
            .ok_or_else(|| DocsEmitError::Schema {
                schema: name.clone(),
                message: "referenced schema is missing from the resolved registry".to_owned(),
            })?;
        collect_direct_references(schema, &mut queued);
    }
    if references.is_empty() {
        return Ok(());
    }

    output.push_str("## Referenced types\n\n");
    for name in references {
        render_schema_table(output, catalog, &name, &format!("`{name}`"), 3)?;
    }
    Ok(())
}

fn collect_direct_references(schema: &Value, references: &mut VecDeque<String>) {
    match schema {
        Value::Object(object) => {
            if let Some(reference) = object.get("$ref").and_then(Value::as_str)
                && let Some(name) = reference.strip_prefix("#/schemas/")
            {
                references.push_back(name.replace("~1", "/").replace("~0", "~"));
            }
            for value in object.values() {
                collect_direct_references(value, references);
            }
        }
        Value::Array(values) => {
            for value in values {
                collect_direct_references(value, references);
            }
        }
        _ => {}
    }
}

fn field_constraints(schema: &Value) -> String {
    let mut constraints = Vec::new();
    if let Some(length) = schema.get("minLength").and_then(Value::as_u64) {
        constraints.push(format!("length ≥ {length}"));
    }
    if let Some(minimum) = schema.get("minimum").and_then(Value::as_number) {
        constraints.push(format!("≥ {minimum}"));
    }
    if schema.get("x-rtvbp-nonzero") == Some(&Value::Bool(true)) {
        constraints.push("non-zero".to_owned());
    }
    if constraints.is_empty() {
        "—".to_owned()
    } else {
        constraints.join("; ")
    }
}

fn envelope_page(envelope: &EnvelopeSpec) -> String {
    let mut output = page_header(&envelope.id, &envelope.id);
    output.push_str(
        "This envelope maps semantic requests, responses, and events onto a flat JSON object.\n\n",
    );
    if !envelope.constants.is_empty() {
        output.push_str("## Constants\n\n| Field | Value |\n| --- | --- |\n");
        for constant in &envelope.constants {
            writeln!(output, "| `{}` | `{}` |", constant.name, constant.value).unwrap();
        }
        output.push('\n');
    }

    output.push_str("## Frame shapes\n\n| Kind | Discriminator | ID / correlation | Payload | Error |\n| --- | --- | --- | --- | --- |\n");
    for frame in &envelope.frames {
        let id = frame.id.as_ref().map_or("—", |field| field.name.as_str());
        let error = frame
            .error
            .as_ref()
            .map_or("—", |field| field.name.as_str());
        writeln!(
            output,
            "| {} | `{}` | `{}` | `{}` | `{}` |",
            frame_kind(frame.kind),
            frame.discriminator.name,
            id,
            frame.payload.name,
            error
        )
        .unwrap();
    }
    output.push('\n');
    let precedence = envelope
        .frames
        .iter()
        .map(|frame| frame_kind(frame.kind))
        .collect::<Vec<_>>()
        .join(" → ");
    writeln!(
        output,
        "Structural discrimination follows declaration order: **{precedence}**.\n"
    )
    .unwrap();

    output.push_str("## Errors\n\nThe error code space accepts **any non-zero integer**. These values are conventions minted by the deployed implementation:\n\n| Name | Code | Description |\n| --- | --- | --- |\n");
    for error in &envelope.error_codes {
        writeln!(
            output,
            "| `{}` | `{}` | {} |",
            error.name,
            error.code,
            escape_table(&error.description)
        )
        .unwrap();
    }
    writeln!(
        output,
        "\nError objects use `{}`, `{}`, and the optional `{}` data field.\n",
        envelope.error.code.name, envelope.error.message.name, envelope.error.data.name
    )
    .unwrap();

    if let Some(response) = envelope
        .frames
        .iter()
        .find(|frame| frame.kind == FrameKind::Response)
        && response.payload.omit_when_none
        && response
            .error
            .as_ref()
            .is_some_and(|field| field.omit_when_none)
    {
        output.push_str("For frozen compatibility, a response may contain both `result` and `error`, or neither field. When both are present, the error determines the semantic outcome.\n\n");
    }
    finish(output)
}

fn page_header(title: &str, sidebar_label: &str) -> String {
    format!(
        "---\ntitle: {}\nsidebar_label: {}\n---\n\n{PAGE_BANNER}",
        yaml_string(title),
        yaml_string(sidebar_label)
    )
}

fn field_presence(schema: &Value, required: bool) -> &'static str {
    if required && accepts_null(schema) {
        "nullable"
    } else if required {
        "required"
    } else {
        "optional"
    }
}

fn schema_type(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference.rsplit('/').next().unwrap_or(reference).to_owned();
    }
    if let Some(branch) = non_null_branch(schema) {
        return schema_type(branch);
    }
    let type_name = schema.get("type").and_then(|value| {
        value.as_str().or_else(|| {
            value
                .as_array()?
                .iter()
                .find_map(Value::as_str)
                .filter(|name| *name != "null")
        })
    });
    match type_name {
        Some("array") => format!(
            "{}[]",
            schema
                .get("items")
                .map(schema_type)
                .unwrap_or_else(|| "any".to_owned())
        ),
        Some("object") if schema.get("additionalProperties").is_some() => "object".to_owned(),
        Some(value) => value.to_owned(),
        None => "any".to_owned(),
    }
}

fn accepts_null(schema: &Value) -> bool {
    schema
        .get("type")
        .and_then(Value::as_array)
        .is_some_and(|types| types.iter().any(|value| value == "null"))
        || schema
            .get("anyOf")
            .and_then(Value::as_array)
            .is_some_and(|branches| branches.iter().any(|branch| branch["type"] == "null"))
}

fn non_null_branch(schema: &Value) -> Option<&Value> {
    schema
        .get("anyOf")
        .and_then(Value::as_array)?
        .iter()
        .find(|branch| branch["type"] != "null")
}

fn role_owns(role: Role, declared: Role) -> bool {
    role == declared || declared == Role::Both
}

fn peer(role: Role) -> Role {
    match role {
        Role::Application => Role::Voice,
        Role::Voice => Role::Application,
        Role::Both => Role::Both,
    }
}

fn direction_to_handler(role: Role) -> &'static str {
    match role {
        Role::Application => "voice → application",
        Role::Voice => "application → voice",
        Role::Both => "application ↔ voice",
    }
}

fn direction_from_emitter(role: Role) -> &'static str {
    match role {
        Role::Application => "application → voice",
        Role::Voice => "voice → application",
        Role::Both => "application ↔ voice",
    }
}

fn frame_kind(kind: FrameKind) -> &'static str {
    match kind {
        FrameKind::Request => "request",
        FrameKind::Response => "response",
        FrameKind::Event => "event",
    }
}

fn title_case(value: &str) -> String {
    let mut characters = value.chars();
    characters
        .next()
        .map(|first| first.to_uppercase().collect::<String>() + characters.as_str())
        .unwrap_or_default()
}

fn display_name(value: &str) -> String {
    value
        .split(['-', '_'])
        .enumerate()
        .map(|(index, word)| match word {
            "dtmf" => "DTMF".to_owned(),
            "rtvbp" => "RTVBP".to_owned(),
            _ if index == 0 => title_case(word),
            _ => word.to_owned(),
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn page_name(name: &str) -> Result<(), DocsEmitError> {
    if !name.is_empty()
        && name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
    {
        Ok(())
    } else {
        Err(DocsEmitError::UnsafePageName {
            name: name.to_owned(),
        })
    }
}

fn yaml_string(value: &str) -> String {
    serde_json::to_string(value).unwrap()
}

fn escape_mdx(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('{', "&#123;")
        .replace('}', "&#125;")
}

fn escape_table(value: &str) -> String {
    escape_mdx(value).replace('|', "\\|").replace('\n', " ")
}

fn finish(mut output: String) -> String {
    while output.ends_with('\n') {
        output.pop();
    }
    output.push('\n');
    output
}
