use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::PathBuf;

use serde_json::Value;
use thiserror::Error;

use super::GeneratedFile;
use crate::resolve::{ResolvedCatalog, ResolvedFixture};

mod envelope;
pub use envelope::emit_go_envelope;

const GO_BANNER: &str =
    "// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.\n\n";

#[derive(Debug, Error)]
pub enum GoEmitError {
    #[error("schema {schema:?}: {message}")]
    Schema { schema: String, message: String },
    #[error("fixture {path:?}: {message}")]
    Fixture { path: String, message: String },
    #[error("envelope {envelope:?}: {message}")]
    Envelope { envelope: String, message: String },
    #[error("could not encode generated Go literal: {0}")]
    Json(#[from] serde_json::Error),
}

#[derive(Debug)]
struct GoCatalog<'a> {
    package: String,
    declarations: Vec<GoDeclaration>,
    catalog: &'a ResolvedCatalog,
}

#[derive(Debug)]
struct GoDeclaration {
    name: String,
    docs: String,
    kind: GoDeclarationKind,
}

#[derive(Debug)]
enum GoDeclarationKind {
    Struct(Vec<GoField>),
    Defined(String),
}

#[derive(Debug)]
struct GoField {
    name: String,
    wire_name: String,
    docs: String,
    go_type: String,
    schema: Value,
    optional: bool,
    pointer: bool,
}

pub fn emit_go(catalog: &ResolvedCatalog) -> Result<Vec<GeneratedFile>, GoEmitError> {
    let model = GoCatalog::resolve(catalog)?;
    let package_dir = format!(
        "{}v{}",
        sanitize_package(&catalog.id.name),
        catalog.id.major
    );
    Ok(vec![
        GeneratedFile {
            path: PathBuf::from("catalog")
                .join(&package_dir)
                .join("zz_generated.types.go"),
            bytes: render_types(&model).into_bytes(),
        },
        GeneratedFile {
            path: PathBuf::from("catalog")
                .join(package_dir)
                .join("zz_generated.golden_test.go"),
            bytes: render_golden_tests(&model)?.into_bytes(),
        },
    ])
}

impl<'a> GoCatalog<'a> {
    fn resolve(catalog: &'a ResolvedCatalog) -> Result<Self, GoEmitError> {
        let mut declarations = Vec::with_capacity(catalog.schemas.len());
        for (name, schema) in &catalog.schemas {
            validate_identifier(name).map_err(|message| schema_error(name, message))?;
            let object = schema.as_object().ok_or_else(|| {
                schema_error(name, "schema root must be a JSON object".to_owned())
            })?;
            let docs = object
                .get("description")
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_owned();
            let kind = if let Some(properties) = object.get("properties").and_then(Value::as_object)
            {
                let required = object
                    .get("required")
                    .and_then(Value::as_array)
                    .into_iter()
                    .flatten()
                    .filter_map(Value::as_str)
                    .collect::<HashSet<_>>();
                let mut fields = Vec::with_capacity(properties.len());
                let mut field_names = HashSet::new();
                for (wire_name, field_schema) in properties {
                    let field = resolve_field(
                        name,
                        wire_name,
                        field_schema,
                        required.contains(wire_name.as_str()),
                        &catalog.schemas,
                    )?;
                    if !field_names.insert(field.name.clone()) {
                        return Err(schema_error(
                            name,
                            format!("multiple fields resolve to Go identifier {}", field.name),
                        ));
                    }
                    fields.push(field);
                }
                GoDeclarationKind::Struct(fields)
            } else {
                GoDeclarationKind::Defined(go_type(name, schema, &catalog.schemas)?)
            };
            declarations.push(GoDeclaration {
                name: name.clone(),
                docs,
                kind,
            });
        }
        Ok(Self {
            package: format!(
                "{}v{}",
                sanitize_package(&catalog.id.name),
                catalog.id.major
            ),
            declarations,
            catalog,
        })
    }
}

fn resolve_field(
    owner: &str,
    wire_name: &str,
    schema: &Value,
    required: bool,
    schemas: &std::collections::BTreeMap<String, Value>,
) -> Result<GoField, GoEmitError> {
    let object = schema.as_object().ok_or_else(|| {
        schema_error(
            owner,
            format!("field {wire_name:?} is not an object schema"),
        )
    })?;
    let marker = object.get("x-rtvbp-presence").and_then(Value::as_str);
    if object.contains_key("x-rtvbp-presence") && marker != Some("nullable") {
        return Err(schema_error(
            owner,
            format!("field {wire_name:?} has an unknown presence marker"),
        ));
    }
    let nullable = marker == Some("nullable");
    if nullable && !required {
        return Err(schema_error(
            owner,
            format!("field {wire_name:?} is nullable but not required"),
        ));
    }
    let optional = !required;
    let optional_pointer = object.get("x-go-type").and_then(Value::as_str) == Some("*string");
    if optional_pointer && !optional {
        return Err(schema_error(
            owner,
            format!("field {wire_name:?} uses *string but is not optional"),
        ));
    }
    let normalized = if optional || nullable {
        remove_null(schema).unwrap_or_else(|| schema.clone())
    } else {
        if contains_null(schema) {
            return Err(schema_error(
                owner,
                format!("required field {wire_name:?} accepts null without nullable presence"),
            ));
        }
        schema.clone()
    };
    let mut field_type = go_type(owner, &normalized, schemas)?;
    if nullable {
        field_type.insert(0, '*');
    }
    Ok(GoField {
        name: go_field_name(wire_name)
            .map_err(|message| schema_error(owner, format!("field {wire_name:?}: {message}")))?,
        wire_name: wire_name.to_owned(),
        docs: object
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_owned(),
        go_type: field_type,
        schema: normalized,
        optional,
        pointer: nullable || optional_pointer,
    })
}

fn go_type(
    owner: &str,
    schema: &Value,
    schemas: &std::collections::BTreeMap<String, Value>,
) -> Result<String, GoEmitError> {
    let object = schema
        .as_object()
        .ok_or_else(|| schema_error(owner, "type schema is not an object".to_owned()))?;
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        let name = schema_ref_name(reference)
            .ok_or_else(|| schema_error(owner, format!("unsupported reference {reference:?}")))?;
        if !schemas.contains_key(&name) {
            return Err(schema_error(
                owner,
                format!("dangling reference {reference:?}"),
            ));
        }
        return Ok(name);
    }
    if object.contains_key("oneOf") || object.contains_key("anyOf") {
        return Err(schema_error(owner, "unsupported union schema".to_owned()));
    }
    let type_name = object.get("type").and_then(Value::as_str);
    let hint = object.get("x-go-type").and_then(Value::as_str);
    if hint.is_some()
        && !matches!(
            (type_name, hint),
            (Some("integer"), Some("int")) | (Some("string"), Some("*string"))
        )
    {
        return Err(schema_error(
            owner,
            "invalid x-go-type extension".to_owned(),
        ));
    }
    match type_name {
        Some("string") if hint == Some("*string") => Ok("*string".to_owned()),
        Some("string") => Ok("string".to_owned()),
        Some("boolean") => Ok("bool".to_owned()),
        Some("integer") if hint == Some("int") => Ok("int".to_owned()),
        Some("integer") => Ok("int64".to_owned()),
        Some("number") => Ok("float64".to_owned()),
        Some("array") => {
            let items = object
                .get("items")
                .ok_or_else(|| schema_error(owner, "array has no items schema".to_owned()))?;
            Ok(format!("[]{}", go_type(owner, items, schemas)?))
        }
        Some("object") if object.contains_key("properties") => Err(schema_error(
            owner,
            "inline object schemas are not supported; name the shared type".to_owned(),
        )),
        Some("object") => match object.get("additionalProperties") {
            None | Some(Value::Bool(false)) => Ok("struct{}".to_owned()),
            Some(Value::Bool(true)) => Ok("map[string]any".to_owned()),
            Some(schema) => Ok(format!("map[string]{}", go_type(owner, schema, schemas)?)),
        },
        None if object.keys().all(|key| key == "description") => Ok("any".to_owned()),
        Some(other) => Err(schema_error(
            owner,
            format!("unsupported JSON type {other:?}"),
        )),
        None => Err(schema_error(
            owner,
            "schema has no supported type".to_owned(),
        )),
    }
}

fn render_types(model: &GoCatalog<'_>) -> String {
    let mut output = String::from(GO_BANNER);
    writeln!(output, "package {}\n", model.package).unwrap();
    for declaration in &model.declarations {
        write_doc(&mut output, &declaration.name, &declaration.docs);
        match &declaration.kind {
            GoDeclarationKind::Struct(fields) => {
                writeln!(output, "type {} struct {{", declaration.name).unwrap();
                for field in fields {
                    write_field_doc(&mut output, &field.name, &field.docs);
                    let omit = if field.optional { ",omitempty" } else { "" };
                    writeln!(
                        output,
                        "\t{} {} `json:\"{}{}\"`",
                        field.name, field.go_type, field.wire_name, omit
                    )
                    .unwrap();
                }
                writeln!(output, "}}\n").unwrap();
            }
            GoDeclarationKind::Defined(go_type) => {
                writeln!(output, "type {} {}\n", declaration.name, go_type).unwrap();
            }
        }
    }

    for operation in &model.catalog.operations {
        writeln!(
            output,
            "const {} = {:?}",
            operation_constant(&operation.method),
            operation.method
        )
        .unwrap();
    }
    for event in &model.catalog.events {
        writeln!(
            output,
            "const {} = {:?}",
            event_constant(&event.name),
            event.name
        )
        .unwrap();
    }
    output.push('\n');

    for operation in &model.catalog.operations {
        let constant = operation_constant(&operation.method);
        writeln!(
            output,
            "// MethodName returns {constant}.\nfunc (*{}) MethodName() string {{ return {constant} }}\n",
            operation.request
        )
        .unwrap();
    }
    for event in &model.catalog.events {
        let constant = event_constant(&event.name);
        writeln!(
            output,
            "// EventName returns {constant}.\nfunc (*{}) EventName() string {{ return {constant} }}\n",
            event.data
        )
        .unwrap();
    }
    while output.ends_with("\n\n") {
        output.pop();
    }
    output
}

fn render_golden_tests(model: &GoCatalog<'_>) -> Result<String, GoEmitError> {
    let mut output = String::from(GO_BANNER);
    writeln!(output, "package {}\n", model.package).unwrap();
    output.push_str("import (\n\t\"bytes\"\n\t\"encoding/json\"\n\t\"testing\"\n)\n\n");
    output.push_str("type goldenCase struct {\n\tname string\n\n\tgolden []byte\n\n\tnewValue func() any\n\n\tconstructed any\n}\n\n");
    output.push_str("var goldenCases = []goldenCase{\n");
    for fixture in &model.catalog.fixtures {
        let literal = render_fixture_literal(model, fixture)?;
        let bytes = String::from_utf8(fixture.bytes.clone()).map_err(|_| GoEmitError::Fixture {
            path: fixture.path.clone(),
            message: "fixture is not UTF-8".to_owned(),
        })?;
        writeln!(
            output,
            "\t{{name: {:?}, golden: []byte({}), newValue: func() any {{ return new({}) }}, constructed: {}}},",
            fixture.path,
            serde_json::to_string(&bytes)?,
            fixture.payload,
            literal
        )
        .unwrap();
    }
    output.push_str("}\n\n");
    output.push_str(
        "func TestGoldenPayloads(t *testing.T) {\n\tfor _, tc := range goldenCases {\n\t\tt.Run(tc.name+\"/round_trip\", func(t *testing.T) {\n\t\t\tvalue := tc.newValue()\n\t\t\tif err := json.Unmarshal(tc.golden, value); err != nil {\n\t\t\t\tt.Fatal(err)\n\t\t\t}\n\t\t\tactual, err := json.Marshal(value)\n\t\t\tif err != nil {\n\t\t\t\tt.Fatal(err)\n\t\t\t}\n\t\t\tif !bytes.Equal(actual, tc.golden) {\n\t\t\t\tt.Fatalf(\"round-trip mismatch\\nwant: %s\\n got: %s\", tc.golden, actual)\n\t\t\t}\n\t\t})\n\t\tt.Run(tc.name+\"/construct\", func(t *testing.T) {\n\t\t\tactual, err := json.Marshal(tc.constructed)\n\t\t\tif err != nil {\n\t\t\t\tt.Fatal(err)\n\t\t\t}\n\t\t\tif !bytes.Equal(actual, tc.golden) {\n\t\t\t\tt.Fatalf(\"constructed mismatch\\nwant: %s\\n got: %s\", tc.golden, actual)\n\t\t\t}\n\t\t})\n\t}\n}\n\nfunc ptr[T any](value T) *T { return &value }\n",
    );
    Ok(output)
}

fn render_fixture_literal(
    model: &GoCatalog<'_>,
    fixture: &ResolvedFixture,
) -> Result<String, GoEmitError> {
    let schema =
        model
            .catalog
            .schemas
            .get(&fixture.payload)
            .ok_or_else(|| GoEmitError::Fixture {
                path: fixture.path.clone(),
                message: format!("missing schema {}", fixture.payload),
            })?;
    let value = render_value(
        &fixture.payload,
        schema,
        &fixture.value,
        &model.catalog.schemas,
        Some(&fixture.payload),
    )?;
    Ok(format!("ptr({value})"))
}

fn render_value(
    owner: &str,
    schema: &Value,
    value: &Value,
    schemas: &std::collections::BTreeMap<String, Value>,
    named: Option<&str>,
) -> Result<String, GoEmitError> {
    let object = schema
        .as_object()
        .ok_or_else(|| schema_error(owner, "literal schema is not an object".to_owned()))?;
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        let name = schema_ref_name(reference)
            .ok_or_else(|| schema_error(owner, format!("unsupported reference {reference:?}")))?;
        let target = schemas
            .get(&name)
            .ok_or_else(|| schema_error(owner, format!("dangling reference {reference:?}")))?;
        return render_value(owner, target, value, schemas, Some(&name));
    }
    if value.is_null() {
        return Ok("nil".to_owned());
    }
    let type_name = object.get("type").and_then(Value::as_str);
    match type_name {
        Some("object")
            if object
                .get("properties")
                .and_then(Value::as_object)
                .is_some() =>
        {
            let properties = object["properties"].as_object().unwrap();
            let required = object
                .get("required")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect::<HashSet<_>>();
            let data = value
                .as_object()
                .ok_or_else(|| schema_error(owner, "fixture value is not an object".to_owned()))?;
            let literal_type = named.ok_or_else(|| {
                schema_error(owner, "inline struct literal has no named type".to_owned())
            })?;
            let mut fields = Vec::new();
            for (wire_name, field_schema) in properties {
                let Some(field_value) = data.get(wire_name) else {
                    continue;
                };
                let field = resolve_field(
                    owner,
                    wire_name,
                    field_schema,
                    required.contains(wire_name.as_str()),
                    schemas,
                )?;
                let mut rendered = render_value(owner, &field.schema, field_value, schemas, None)?;
                if field.pointer && !field_value.is_null() {
                    rendered = format!("ptr({rendered})");
                }
                fields.push(format!("{}: {}", field.name, rendered));
            }
            Ok(format!("{literal_type}{{{}}}", fields.join(", ")))
        }
        Some("object") => {
            let data = value.as_object().ok_or_else(|| {
                schema_error(owner, "fixture map value is not an object".to_owned())
            })?;
            let value_schema = object.get("additionalProperties");
            let map_type = named
                .map(str::to_owned)
                .unwrap_or(go_type(owner, schema, schemas)?);
            let mut entries = Vec::new();
            for (key, item) in data {
                let rendered = match value_schema {
                    Some(Value::Bool(true)) | None => render_any(item)?,
                    Some(schema) => render_value(owner, schema, item, schemas, None)?,
                };
                entries.push(format!("{}: {rendered}", serde_json::to_string(key)?));
            }
            Ok(format!("{map_type}{{{}}}", entries.join(", ")))
        }
        Some("array") => {
            let values = value
                .as_array()
                .ok_or_else(|| schema_error(owner, "fixture value is not an array".to_owned()))?;
            let items = object
                .get("items")
                .ok_or_else(|| schema_error(owner, "array has no items schema".to_owned()))?;
            let literal_type = named
                .map(str::to_owned)
                .unwrap_or(go_type(owner, schema, schemas)?);
            let rendered = values
                .iter()
                .map(|value| render_value(owner, items, value, schemas, None))
                .collect::<Result<Vec<_>, _>>()?;
            Ok(format!("{literal_type}{{{}}}", rendered.join(", ")))
        }
        Some("string") => Ok(serde_json::to_string(value.as_str().ok_or_else(|| {
            schema_error(owner, "fixture value is not a string".to_owned())
        })?)?),
        Some("boolean") => Ok(value
            .as_bool()
            .ok_or_else(|| schema_error(owner, "fixture value is not a boolean".to_owned()))?
            .to_string()),
        Some("integer") | Some("number") => value
            .as_number()
            .map(ToString::to_string)
            .ok_or_else(|| schema_error(owner, "fixture value is not a number".to_owned())),
        None if object.keys().all(|key| key == "description") => render_any(value),
        _ => Err(schema_error(
            owner,
            "unsupported fixture literal schema".to_owned(),
        )),
    }
}

fn render_any(value: &Value) -> Result<String, GoEmitError> {
    match value {
        Value::Null => Ok("nil".to_owned()),
        Value::Bool(value) => Ok(value.to_string()),
        Value::Number(value) => {
            if value.is_i64() || value.is_u64() {
                Ok(format!("int64({value})"))
            } else {
                Ok(format!("float64({value})"))
            }
        }
        Value::String(value) => Ok(serde_json::to_string(value)?),
        Value::Array(values) => Ok(format!(
            "[]any{{{}}}",
            values
                .iter()
                .map(render_any)
                .collect::<Result<Vec<_>, _>>()?
                .join(", ")
        )),
        Value::Object(object) => {
            let mut entries = Vec::new();
            for (key, value) in object {
                entries.push(format!(
                    "{}: {}",
                    serde_json::to_string(key)?,
                    render_any(value)?
                ));
            }
            Ok(format!("map[string]any{{{}}}", entries.join(", ")))
        }
    }
}

fn remove_null(schema: &Value) -> Option<Value> {
    let mut normalized = schema.clone();
    let object = normalized.as_object_mut()?;
    let single_type = if let Some(Value::Array(types)) = object.get_mut("type") {
        types.retain(|value| value.as_str() != Some("null"));
        if types.len() == 1 {
            Some(types[0].clone())
        } else {
            None
        }
    } else {
        None
    };
    if let Some(single_type) = single_type {
        object.insert("type".to_owned(), single_type);
        return Some(normalized);
    }
    if let Some(Value::Array(branches)) = object.get("anyOf") {
        let non_null = branches
            .iter()
            .filter(|branch| branch["type"] != "null")
            .cloned()
            .collect::<Vec<_>>();
        if non_null.len() == 1 && non_null.len() + 1 == branches.len() {
            let mut branch = non_null.into_iter().next().unwrap();
            if let (Some(branch), Some(outer)) = (branch.as_object_mut(), schema.as_object()) {
                for (key, value) in outer {
                    if key != "anyOf" && key != "x-rtvbp-presence" && key != "description" {
                        branch.entry(key.clone()).or_insert_with(|| value.clone());
                    }
                }
            }
            return Some(branch);
        }
    }
    None
}

fn contains_null(schema: &Value) -> bool {
    schema
        .get("type")
        .and_then(Value::as_array)
        .is_some_and(|types| types.iter().any(|value| value == "null"))
        || schema
            .get("anyOf")
            .and_then(Value::as_array)
            .is_some_and(|branches| branches.iter().any(|branch| branch["type"] == "null"))
}

fn schema_ref_name(reference: &str) -> Option<String> {
    reference
        .strip_prefix("#/schemas/")
        .map(|name| name.replace("~1", "/").replace("~0", "~"))
}

fn go_field_name(wire_name: &str) -> Result<String, String> {
    if wire_name.is_empty() {
        return Err("wire name is empty".to_owned());
    }
    let mut output = String::new();
    for part in wire_name.split('_') {
        if part.is_empty() {
            return Err("wire name contains an empty segment".to_owned());
        }
        output.push_str(match part {
            "id" => "ID",
            "rtt" => "RTT",
            "owd" => "OWD",
            _ => {
                let mut chars = part.chars();
                let first = chars.next().unwrap().to_ascii_uppercase();
                output.push(first);
                output.push_str(chars.as_str());
                continue;
            }
        });
    }
    validate_identifier(&output)?;
    Ok(output)
}

fn operation_constant(name: &str) -> String {
    format!("Method{}", pascal_wire_name(name))
}

fn event_constant(name: &str) -> String {
    format!("Event{}", pascal_wire_name(name))
}

fn pascal_wire_name(name: &str) -> String {
    name.split(['.', '_'])
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| format!("{}{}", first.to_ascii_uppercase(), chars.as_str()))
                .unwrap_or_default()
        })
        .collect()
}

fn sanitize_package(name: &str) -> String {
    name.chars()
        .filter(char::is_ascii_alphanumeric)
        .flat_map(char::to_lowercase)
        .collect()
}

fn validate_identifier(name: &str) -> Result<(), String> {
    let mut chars = name.chars();
    if !chars
        .next()
        .is_some_and(|first| first == '_' || first.is_ascii_alphabetic())
        || !chars.all(|character| character == '_' || character.is_ascii_alphanumeric())
    {
        return Err(format!("{name:?} is not a Go identifier"));
    }
    Ok(())
}

fn write_doc(output: &mut String, name: &str, docs: &str) {
    writeln!(output, "// {name} is generated from the protocol catalog.").unwrap();
    if !docs.is_empty() {
        output.push_str("//\n");
        for line in docs.lines() {
            writeln!(output, "// {line}").unwrap();
        }
    }
}

fn write_field_doc(output: &mut String, name: &str, docs: &str) {
    if docs.is_empty() {
        return;
    }
    for (index, line) in docs.lines().enumerate() {
        if index == 0 {
            writeln!(output, "\t// {name}: {line}").unwrap();
        } else {
            writeln!(output, "\t// {line}").unwrap();
        }
    }
}

fn schema_error(schema: &str, message: String) -> GoEmitError {
    GoEmitError::Schema {
        schema: schema.to_owned(),
        message,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::collections::BTreeMap;

    #[test]
    fn pointer_string_hint_is_restricted_to_optional_string_fields() {
        let schemas = BTreeMap::new();
        let required = json!({"type": "string", "x-go-type": "*string"});
        let error = resolve_field("Payload", "text", &required, true, &schemas).unwrap_err();
        assert!(
            error
                .to_string()
                .contains("uses *string but is not optional")
        );

        let nullable = json!({
            "type": ["string", "null"],
            "x-go-type": "*string",
            "x-rtvbp-presence": "nullable"
        });
        let error = resolve_field("Payload", "text", &nullable, true, &schemas).unwrap_err();
        assert!(
            error
                .to_string()
                .contains("uses *string but is not optional")
        );

        let wrong_type = json!({"type": ["boolean", "null"], "x-go-type": "*string"});
        let error = resolve_field("Payload", "text", &wrong_type, false, &schemas).unwrap_err();
        assert!(error.to_string().contains("invalid x-go-type extension"));
    }
}
