use std::fmt::Write as _;
use std::path::PathBuf;

use rtvbp_spec_model::{MediaCarrier, ProfileRegistry, ProfileSpec};
use serde::Serialize;
use serde_json::json;
use thiserror::Error;

use super::GeneratedFile;

const NOTICE: &str =
    "Code generated by rtvbp-spec-gen from the typed profile registry. DO NOT EDIT.";

#[derive(Debug, Error)]
pub enum ProfileEmitError {
    #[error("could not serialize profile output: {0}")]
    Json(#[from] serde_json::Error),
    #[error("profile registry has no headerless profile")]
    MissingHeaderlessProfile,
    #[error("profile {0:?} has no declaration")]
    MissingProfile(String),
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ProfileManifest<'a> {
    #[serde(rename = "_generated")]
    generated: &'static str,
    format_version: u32,
    #[serde(flatten)]
    registry: &'a ProfileRegistry,
}

pub fn emit_profile_manifest(
    registry: &ProfileRegistry,
) -> Result<Vec<GeneratedFile>, ProfileEmitError> {
    let mut bytes = serde_json::to_vec_pretty(&ProfileManifest {
        generated: NOTICE,
        format_version: 1,
        registry,
    })?;
    bytes.push(b'\n');
    Ok(vec![GeneratedFile {
        path: PathBuf::from("rtvbp.profiles.json"),
        bytes,
    }])
}

pub fn emit_go_profiles(
    registry: &ProfileRegistry,
) -> Result<Vec<GeneratedFile>, ProfileEmitError> {
    let mut source = format!("// {NOTICE}\n\npackage profile\n\n");
    for profile in &registry.profiles {
        writeln!(
            source,
            "const {} = {}",
            go_constant(&profile.id),
            quoted(&profile.negotiation_token)?
        )
        .unwrap();
    }
    for signal in &registry.signaling {
        writeln!(
            source,
            "const {} = {}",
            go_signaling_constant(&signal.method),
            quoted(&signal.method)?
        )
        .unwrap();
    }
    writeln!(
        source,
        "const Default = {}",
        go_constant(&registry.negotiation.default_profile)
    )
    .unwrap();
    let headerless = registry
        .negotiation
        .headerless_profile
        .as_deref()
        .ok_or(ProfileEmitError::MissingHeaderlessProfile)?;
    writeln!(source, "const Headerless = {}", go_constant(headerless)).unwrap();
    source.push('\n');
    source.push_str(
        "// Descriptor is the generated transport/envelope/catalog composition for one profile.\n\
         type Descriptor struct {\n\
         \tID        string\n\
         \tToken     string\n\
         \tTransport string\n\
         \tEnvelope  string\n\
         \tCatalog   string\n\
         \tSignaling []string\n\
         \tMedia     []Media\n\
         }\n\n\
         // Media is one generated profile media constraint.\n\
         type Media struct {\n\
         \tChannel    string\n\
         \tCarrier    string\n\
         \tWireFormat string\n\
         \tSDKFormat  string\n\
         }\n\n",
    );
    source.push_str("var descriptors = []Descriptor{\n");
    for profile in &registry.profiles {
        writeln!(
            source,
            "\t{{ID: {}, Token: {}, Transport: {}, Envelope: {}, Catalog: {}, Signaling: {}, Media: {}}},",
            quoted(&profile.id)?,
            quoted(&profile.negotiation_token)?,
            quoted(&profile.transport)?,
            quoted(&profile.envelope)?,
            quoted(&profile.catalog.to_string())?,
            go_strings(&profile.signaling)?,
            go_media(profile)?
        )
        .unwrap();
    }
    source.push_str("}\n\n");
    source.push_str(
        "// ServerPreference returns profile tokens in accepting-endpoint preference order.\n",
    );
    source.push_str("func ServerPreference() []string {\n\treturn []string{");
    for (index, id) in registry.negotiation.server_preference.iter().enumerate() {
        let profile = find_profile(registry, id)?;
        if index != 0 {
            source.push_str(", ");
        }
        write!(source, "{}", go_constant(&profile.id)).unwrap();
    }
    source.push_str("}\n}\n\n");
    source.push_str("// All returns a copy of every generated profile descriptor.\n");
    source.push_str(
        "func All() []Descriptor {\n\treturn append([]Descriptor(nil), descriptors...)\n}\n",
    );

    Ok(vec![GeneratedFile {
        path: PathBuf::from("profile/zz_generated.profiles.go"),
        bytes: source.into_bytes(),
    }])
}

pub fn emit_rust_profiles(
    registry: &ProfileRegistry,
) -> Result<Vec<GeneratedFile>, ProfileEmitError> {
    let mut source = format!("// {NOTICE}\n\n");
    source.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct Media {\n    pub channel: &'static str,\n    pub carrier: &'static str,\n    pub wire_format: &'static str,\n    pub sdk_format: &'static str,\n}\n\n");
    source.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct Descriptor {\n    pub id: &'static str,\n    pub token: &'static str,\n    pub transport: &'static str,\n    pub envelope: &'static str,\n    pub catalog: &'static str,\n    pub signaling: &'static [&'static str],\n    pub media: &'static [Media],\n}\n\n");
    for profile in &registry.profiles {
        writeln!(
            source,
            "pub const {}: &str = {};",
            rust_constant(&profile.id),
            quoted(&profile.negotiation_token)?
        )
        .unwrap();
    }
    for signal in &registry.signaling {
        writeln!(
            source,
            "pub const {}: &str = {};",
            rust_signaling_constant(&signal.method),
            quoted(&signal.method)?
        )
        .unwrap();
    }
    writeln!(
        source,
        "pub const DEFAULT: &str = {};",
        rust_constant(&registry.negotiation.default_profile)
    )
    .unwrap();
    let headerless = registry
        .negotiation
        .headerless_profile
        .as_deref()
        .ok_or(ProfileEmitError::MissingHeaderlessProfile)?;
    writeln!(
        source,
        "pub const HEADERLESS: &str = {};",
        rust_constant(headerless)
    )
    .unwrap();
    source.push_str("\npub static SERVER_PREFERENCE: &[&str] = &[\n");
    for id in &registry.negotiation.server_preference {
        writeln!(source, "    {},", rust_constant(id)).unwrap();
    }
    source.push_str("];\n\npub static PROFILES: &[Descriptor] = &[\n");
    for profile in &registry.profiles {
        writeln!(source, "    Descriptor {{").unwrap();
        writeln!(source, "        id: {},", quoted(&profile.id)?).unwrap();
        writeln!(source, "        token: {},", rust_constant(&profile.id)).unwrap();
        writeln!(
            source,
            "        transport: {},",
            quoted(&profile.transport)?
        )
        .unwrap();
        writeln!(source, "        envelope: {},", quoted(&profile.envelope)?).unwrap();
        writeln!(
            source,
            "        catalog: {},",
            quoted(&profile.catalog.to_string())?
        )
        .unwrap();
        write!(source, "        signaling: &[").unwrap();
        for (index, signal) in profile.signaling.iter().enumerate() {
            if index != 0 {
                source.push_str(", ");
            }
            write!(source, "{}", quoted(signal)?).unwrap();
        }
        source.push_str("],\n");
        render_rust_media(&mut source, profile)?;
        source.push_str("    },\n");
    }
    source.push_str("];\n");

    Ok(vec![GeneratedFile {
        path: PathBuf::from("src/profile/zz_generated_profiles.rs"),
        bytes: source.into_bytes(),
    }])
}

pub fn emit_typescript_profiles(
    registry: &ProfileRegistry,
) -> Result<Vec<GeneratedFile>, ProfileEmitError> {
    let mut source = format!("// {NOTICE}\n\n");
    source.push_str("export interface ProfileMedia { readonly channel: string; readonly carrier: string; readonly wireFormat: string; readonly sdkFormat: string; }\n");
    source.push_str("export interface ProfileDescriptor { readonly id: string; readonly token: string; readonly transport: string; readonly envelope: string; readonly catalog: string; readonly signaling: readonly string[]; readonly media: readonly ProfileMedia[]; }\n\n");
    for profile in &registry.profiles {
        writeln!(
            source,
            "export const {} = {} as const;",
            typescript_constant(&profile.id),
            quoted(&profile.negotiation_token)?
        )
        .unwrap();
    }
    for signal in &registry.signaling {
        writeln!(
            source,
            "export const {} = {} as const;",
            rust_signaling_constant(&signal.method),
            quoted(&signal.method)?
        )
        .unwrap();
    }
    writeln!(
        source,
        "export const DEFAULT_PROFILE = {};",
        typescript_constant(&registry.negotiation.default_profile)
    )
    .unwrap();
    let headerless = registry
        .negotiation
        .headerless_profile
        .as_deref()
        .ok_or(ProfileEmitError::MissingHeaderlessProfile)?;
    writeln!(
        source,
        "export const HEADERLESS_PROFILE = {};",
        typescript_constant(headerless)
    )
    .unwrap();
    source.push_str("export const SERVER_PREFERENCE = [");
    for id in &registry.negotiation.server_preference {
        write!(source, "{},", typescript_constant(id)).unwrap();
    }
    source.push_str("] as const;\n\nexport const PROFILES = [\n");
    for profile in &registry.profiles {
        writeln!(source, "  {{").unwrap();
        writeln!(source, "    id: {},", quoted(&profile.id)?).unwrap();
        writeln!(source, "    token: {},", typescript_constant(&profile.id)).unwrap();
        writeln!(source, "    transport: {},", quoted(&profile.transport)?).unwrap();
        writeln!(source, "    envelope: {},", quoted(&profile.envelope)?).unwrap();
        writeln!(
            source,
            "    catalog: {},",
            quoted(&profile.catalog.to_string())?
        )
        .unwrap();
        writeln!(
            source,
            "    signaling: {},",
            serde_json::to_string(&profile.signaling)?
        )
        .unwrap();
        source.push_str("    media: [\n");
        for media in &profile.media {
            writeln!(
                source,
                "      {{ channel: {}, carrier: {}, wireFormat: {}, sdkFormat: {} }},",
                quoted(&media.channel)?,
                quoted(media_carrier(media.carrier))?,
                quoted(&media.wire_format)?,
                quoted(&media.sdk_format)?
            )
            .unwrap();
        }
        source.push_str("    ],\n  },\n");
    }
    source.push_str("] as const satisfies readonly ProfileDescriptor[];\n");

    Ok(vec![GeneratedFile {
        path: PathBuf::from("src/generated/zz_generated_profiles.ts"),
        bytes: source.into_bytes(),
    }])
}

pub fn emit_profile_docs(
    registry: &ProfileRegistry,
) -> Result<Vec<GeneratedFile>, ProfileEmitError> {
    let mut docs = format!("{{/* {NOTICE} */}}\n\n# Profile registry\n\n");
    docs.push_str("Profiles are declared once in the executable specification. Preference is accepting-endpoint order.\n\n");
    docs.push_str("| Preference | Profile / token | Transport | Envelope | Catalog | Headerless |\n|---:|---|---|---|---|---|\n");
    for (index, id) in registry.negotiation.server_preference.iter().enumerate() {
        let profile = find_profile(registry, id)?;
        let headerless = registry.negotiation.headerless_profile.as_deref() == Some(id.as_str());
        writeln!(
            docs,
            "| {} | `{}` | `{}` | `{}` | `{}` | {} |",
            index + 1,
            profile.negotiation_token,
            profile.transport,
            profile.envelope,
            profile.catalog,
            if headerless {
                "yes — effective without echo"
            } else {
                "no"
            }
        )
        .unwrap();
    }
    docs.push_str("\n## Media constraints\n\n| Profile | Channel | Carrier | Wire format | SDK format |\n|---|---|---|---|---|\n");
    for profile in &registry.profiles {
        if profile.media.is_empty() {
            writeln!(docs, "| `{}` | — | — | — | — |", profile.id).unwrap();
        }
        for media in &profile.media {
            writeln!(
                docs,
                "| `{}` | `{}` | `{}` | `{}` | `{}` |",
                profile.id,
                media.channel,
                media_carrier(media.carrier),
                media.wire_format,
                media.sdk_format
            )
            .unwrap();
        }
    }
    docs.push_str("\n## Formats\n\n| Id | Encoding | Rate | Bits | Channels | Packet time |\n|---|---|---:|---:|---:|---:|\n");
    for format in &registry.media_formats {
        writeln!(
            docs,
            "| `{}` | `{}` | {} Hz | {} | {} | {} ms |",
            format.id,
            format.encoding,
            format.sample_rate,
            format.bit_depth,
            format.channels,
            format.packet_time_ms
        )
        .unwrap();
    }
    docs.push_str("\n## Reserved signaling\n\n");
    if registry.signaling.is_empty() {
        docs.push_str("_None._\n");
    }
    for signal in &registry.signaling {
        writeln!(
            docs,
            "- `{}` on `{}` — {}",
            signal.method, signal.transport, signal.description
        )
        .unwrap();
    }

    let category = serde_json::to_vec_pretty(&json!({
        "label": "Profiles",
        "position": 0,
    }))?;
    let mut category = category;
    category.push(b'\n');
    Ok(vec![
        GeneratedFile {
            path: PathBuf::from("profiles/_category_.json"),
            bytes: category,
        },
        GeneratedFile {
            path: PathBuf::from("profiles/index.mdx"),
            bytes: docs.into_bytes(),
        },
    ])
}

pub fn emit_profile_vectors(
    registry: &ProfileRegistry,
) -> Result<Vec<GeneratedFile>, ProfileEmitError> {
    let mut valid = Vec::new();
    if let Some(headerless) = &registry.negotiation.headerless_profile {
        valid.push(json!({
            "name": "headerless-default",
            "offered": [],
            "selectedToken": null,
            "effectiveProfile": headerless,
        }));
    }
    for profile in &registry.profiles {
        valid.push(json!({
            "name": format!("explicit-{}", profile.id),
            "offered": [profile.negotiation_token],
            "selectedToken": profile.negotiation_token,
            "effectiveProfile": profile.id,
        }));
    }
    let reversed = registry
        .negotiation
        .server_preference
        .iter()
        .rev()
        .map(|id| find_profile(registry, id).map(|profile| profile.negotiation_token.clone()))
        .collect::<Result<Vec<_>, _>>()?;
    if let Some(selected) = registry.negotiation.server_preference.first() {
        let selected_profile = find_profile(registry, selected)?;
        valid.push(json!({
            "name": "server-preference",
            "offered": reversed,
            "selectedToken": selected_profile.negotiation_token,
            "effectiveProfile": selected_profile.id,
        }));
    }
    let invalid = vec![
        json!({
            "name": "unsupported-token",
            "offered": ["rtvbp.unsupported.v999"],
            "error": "unsupported-profile",
        }),
        json!({
            "name": "empty-token",
            "offered": [""],
            "error": "invalid-token",
        }),
    ];
    let mut bytes = serde_json::to_vec_pretty(&json!({
        "_generated": NOTICE,
        "negotiation": registry.negotiation.transport,
        "valid": valid,
        "invalid": invalid,
    }))?;
    bytes.push(b'\n');
    Ok(vec![GeneratedFile {
        path: PathBuf::from("profiles/negotiation.json"),
        bytes,
    }])
}

fn find_profile<'a>(
    registry: &'a ProfileRegistry,
    id: &str,
) -> Result<&'a ProfileSpec, ProfileEmitError> {
    registry
        .profiles
        .iter()
        .find(|profile| profile.id == id)
        .ok_or_else(|| ProfileEmitError::MissingProfile(id.to_owned()))
}

fn go_media(profile: &ProfileSpec) -> Result<String, ProfileEmitError> {
    let mut source = String::from("[]Media{");
    for (index, media) in profile.media.iter().enumerate() {
        if index != 0 {
            source.push_str(", ");
        }
        write!(
            source,
            "{{Channel: {}, Carrier: {}, WireFormat: {}, SDKFormat: {}}}",
            quoted(&media.channel)?,
            quoted(media_carrier(media.carrier))?,
            quoted(&media.wire_format)?,
            quoted(&media.sdk_format)?
        )
        .unwrap();
    }
    source.push('}');
    Ok(source)
}

fn render_rust_media(source: &mut String, profile: &ProfileSpec) -> Result<(), ProfileEmitError> {
    match profile.media.as_slice() {
        [] => source.push_str("        media: &[],\n"),
        [media] => {
            source.push_str("        media: &[Media {\n");
            writeln!(source, "            channel: {},", quoted(&media.channel)?).unwrap();
            writeln!(
                source,
                "            carrier: {},",
                quoted(media_carrier(media.carrier))?
            )
            .unwrap();
            writeln!(
                source,
                "            wire_format: {},",
                quoted(&media.wire_format)?
            )
            .unwrap();
            writeln!(
                source,
                "            sdk_format: {},",
                quoted(&media.sdk_format)?
            )
            .unwrap();
            source.push_str("        }],\n");
        }
        media => {
            source.push_str("        media: &[\n");
            for item in media {
                source.push_str("            Media {\n");
                writeln!(
                    source,
                    "                channel: {},",
                    quoted(&item.channel)?
                )
                .unwrap();
                writeln!(
                    source,
                    "                carrier: {},",
                    quoted(media_carrier(item.carrier))?
                )
                .unwrap();
                writeln!(
                    source,
                    "                wire_format: {},",
                    quoted(&item.wire_format)?
                )
                .unwrap();
                writeln!(
                    source,
                    "                sdk_format: {},",
                    quoted(&item.sdk_format)?
                )
                .unwrap();
                source.push_str("            },\n");
            }
            source.push_str("        ],\n");
        }
    }
    Ok(())
}

fn go_strings(values: &[String]) -> Result<String, ProfileEmitError> {
    let mut source = String::from("[]string{");
    for (index, value) in values.iter().enumerate() {
        if index != 0 {
            source.push_str(", ");
        }
        write!(source, "{}", quoted(value)?).unwrap();
    }
    source.push('}');
    Ok(source)
}

fn media_carrier(carrier: MediaCarrier) -> &'static str {
    match carrier {
        MediaCarrier::Memory => "memory",
        MediaCarrier::WebSocketBinary => "websocket-binary",
        MediaCarrier::WebRtcRtp => "webrtc-rtp",
    }
}

fn quoted(value: &str) -> Result<String, serde_json::Error> {
    serde_json::to_string(value)
}

fn words(value: &str) -> Vec<String> {
    value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(str::to_ascii_lowercase)
        .collect()
}

fn go_constant(value: &str) -> String {
    format!("Profile{}", pascal_words(value))
}

fn go_signaling_constant(value: &str) -> String {
    format!("Signaling{}", pascal_words(value))
}

fn rust_constant(value: &str) -> String {
    format!("PROFILE_{}", words(value).join("_").to_ascii_uppercase())
}

fn rust_signaling_constant(value: &str) -> String {
    format!("SIGNALING_{}", words(value).join("_").to_ascii_uppercase())
}

fn typescript_constant(value: &str) -> String {
    rust_constant(value)
}

fn pascal_words(value: &str) -> String {
    words(value)
        .into_iter()
        .map(|word| {
            let mut characters = word.chars();
            match characters.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + characters.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
