use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;
use std::path::PathBuf;

use rtvbp_spec_model::EnvelopeSpec;
use serde_json::Value;
use thiserror::Error;

use super::GeneratedFile;
use crate::resolve::{ResolvedCatalog, ResolvedFixture};

mod envelope;
pub use envelope::emit_rust_envelope;
mod roles;

const RUST_BANNER: &str =
    "// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.\n\n";

#[derive(Debug, Error)]
pub enum RustEmitError {
    #[error("schema {schema:?}: {message}")]
    Schema { schema: String, message: String },
    #[error("fixture {path:?}: {message}")]
    Fixture { path: String, message: String },
    #[error("envelope {envelope:?}: {message}")]
    Envelope { envelope: String, message: String },
    #[error(
        "generated Rust role surface {surface:?} maps both {first:?} and {second:?} to method {method:?}"
    )]
    RoleMethodCollision {
        surface: String,
        method: String,
        first: String,
        second: String,
    },
    #[error("could not encode generated Rust literal: {0}")]
    Json(#[from] serde_json::Error),
}

#[derive(Debug)]
struct RustCatalog<'a> {
    module: String,
    declarations: Vec<RustDeclaration>,
    catalog: &'a ResolvedCatalog,
}

#[derive(Debug)]
struct RustDeclaration {
    name: String,
    docs: String,
    schema: Value,
    kind: RustDeclarationKind,
}

#[derive(Debug)]
enum RustDeclarationKind {
    Struct(Vec<RustField>),
    Defined(String),
}

#[derive(Debug)]
struct RustField {
    name: String,
    wire_name: String,
    docs: String,
    rust_type: String,
    schema: Value,
    optional: bool,
    nullable: bool,
}

pub fn emit_rust(catalog: &ResolvedCatalog) -> Result<Vec<GeneratedFile>, RustEmitError> {
    let model = RustCatalog::resolve(catalog)?;
    let package_dir = format!("{}v{}", sanitize_module(&catalog.id.name), catalog.id.major);
    Ok(vec![
        GeneratedFile {
            path: PathBuf::from("src")
                .join("catalog")
                .join(&package_dir)
                .join("zz_generated_types.rs"),
            bytes: render_types(&model).into_bytes(),
        },
        GeneratedFile {
            path: PathBuf::from("src")
                .join("catalog")
                .join(&package_dir)
                .join("zz_generated_golden_tests.rs"),
            bytes: render_golden_tests(&model)?.into_bytes(),
        },
        GeneratedFile {
            path: PathBuf::from("src")
                .join("catalog")
                .join(&package_dir)
                .join("zz_generated_roles.rs"),
            bytes: roles::render(catalog)?.into_bytes(),
        },
        GeneratedFile {
            path: PathBuf::from("src")
                .join("catalog")
                .join(package_dir)
                .join("zz_generated_roles_tests.rs"),
            bytes: roles::render_tests(catalog).into_bytes(),
        },
    ])
}

impl<'a> RustCatalog<'a> {
    fn resolve(catalog: &'a ResolvedCatalog) -> Result<Self, RustEmitError> {
        let mut declarations = Vec::with_capacity(catalog.schemas.len());
        for (name, schema) in &catalog.schemas {
            validate_type_identifier(name).map_err(|message| schema_error(name, message))?;
            let object = schema.as_object().ok_or_else(|| {
                schema_error(name, "schema root must be a JSON object".to_owned())
            })?;
            let docs = object
                .get("description")
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_owned();
            let kind = if let Some(properties) = object.get("properties").and_then(Value::as_object)
            {
                let required = object
                    .get("required")
                    .and_then(Value::as_array)
                    .into_iter()
                    .flatten()
                    .filter_map(Value::as_str)
                    .collect::<HashSet<_>>();
                let mut fields = Vec::with_capacity(properties.len());
                let mut field_names = HashSet::new();
                for (wire_name, field_schema) in properties {
                    let field = resolve_field(
                        name,
                        wire_name,
                        field_schema,
                        required.contains(wire_name.as_str()),
                        &catalog.schemas,
                    )?;
                    if !field_names.insert(field.name.clone()) {
                        return Err(schema_error(
                            name,
                            format!("multiple fields resolve to Rust identifier {}", field.name),
                        ));
                    }
                    fields.push(field);
                }
                RustDeclarationKind::Struct(fields)
            } else {
                RustDeclarationKind::Defined(rust_type(name, schema, &catalog.schemas)?)
            };
            declarations.push(RustDeclaration {
                name: name.clone(),
                docs,
                schema: schema.clone(),
                kind,
            });
        }
        Ok(Self {
            module: format!("{}v{}", sanitize_module(&catalog.id.name), catalog.id.major),
            declarations,
            catalog,
        })
    }
}

fn resolve_field(
    owner: &str,
    wire_name: &str,
    schema: &Value,
    required: bool,
    schemas: &BTreeMap<String, Value>,
) -> Result<RustField, RustEmitError> {
    let object = schema.as_object().ok_or_else(|| {
        schema_error(
            owner,
            format!("field {wire_name:?} is not an object schema"),
        )
    })?;
    let marker = object.get("x-rtvbp-presence").and_then(Value::as_str);
    if object.contains_key("x-rtvbp-presence") && marker != Some("nullable") {
        return Err(schema_error(
            owner,
            format!("field {wire_name:?} has an unknown presence marker"),
        ));
    }
    let nullable = marker == Some("nullable");
    if nullable && !required {
        return Err(schema_error(
            owner,
            format!("field {wire_name:?} is nullable but not required"),
        ));
    }
    let optional = !required;
    let normalized = if optional || nullable {
        remove_null(schema).unwrap_or_else(|| schema.clone())
    } else {
        if contains_null(schema) {
            return Err(schema_error(
                owner,
                format!("required field {wire_name:?} accepts null without nullable presence"),
            ));
        }
        schema.clone()
    };
    let base_type = rust_type(owner, &normalized, schemas)?;
    let rust_type = if optional || nullable {
        format!("Option<{base_type}>")
    } else {
        base_type
    };
    Ok(RustField {
        name: rust_field_name(wire_name)
            .map_err(|message| schema_error(owner, format!("field {wire_name:?}: {message}")))?,
        wire_name: wire_name.to_owned(),
        docs: object
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_owned(),
        rust_type,
        schema: normalized,
        optional,
        nullable,
    })
}

fn rust_type(
    owner: &str,
    schema: &Value,
    schemas: &BTreeMap<String, Value>,
) -> Result<String, RustEmitError> {
    let object = schema
        .as_object()
        .ok_or_else(|| schema_error(owner, "type schema is not an object".to_owned()))?;
    if let Some(reference) = object.get("$ref") {
        let reference = reference
            .as_str()
            .ok_or_else(|| schema_error(owner, "$ref is not a string".to_owned()))?;
        let name = schema_ref_name(reference)
            .ok_or_else(|| schema_error(owner, format!("unsupported reference {reference:?}")))?;
        if !schemas.contains_key(&name) {
            return Err(schema_error(
                owner,
                format!("dangling reference {reference:?}"),
            ));
        }
        return Ok(name);
    }
    if object.contains_key("oneOf") || object.contains_key("anyOf") {
        return Err(schema_error(owner, "unsupported union schema".to_owned()));
    }
    match object.get("type").and_then(Value::as_str) {
        Some("string") => Ok("String".to_owned()),
        Some("boolean") => Ok("bool".to_owned()),
        Some("integer") => Ok("i64".to_owned()),
        Some("number") => Ok("f64".to_owned()),
        Some("array") => {
            let items = object
                .get("items")
                .ok_or_else(|| schema_error(owner, "array has no items schema".to_owned()))?;
            Ok(format!("Vec<{}>", rust_type(owner, items, schemas)?))
        }
        Some("object") if object.contains_key("properties") => Err(schema_error(
            owner,
            "inline object schemas are not supported; name the shared type".to_owned(),
        )),
        Some("object") => match object.get("additionalProperties") {
            None | Some(Value::Bool(false)) => {
                Ok("serde_json::Map<String, serde_json::Value>".to_owned())
            }
            Some(Value::Bool(true)) => Ok("serde_json::Map<String, serde_json::Value>".to_owned()),
            Some(schema) => Ok(format!(
                "std::collections::BTreeMap<String, {}>",
                rust_type(owner, schema, schemas)?
            )),
        },
        None if object.keys().all(|key| key == "description") => Ok("serde_json::Value".to_owned()),
        Some(other) => Err(schema_error(
            owner,
            format!("unsupported JSON type {other:?}"),
        )),
        None => Err(schema_error(
            owner,
            "schema has no supported type".to_owned(),
        )),
    }
}

fn render_types(model: &RustCatalog<'_>) -> String {
    let mut output = String::from(RUST_BANNER);
    writeln!(output, "// Generated `{}` catalog types.\n", model.module).unwrap();
    output.push_str("use serde::{Deserialize, Serialize};\n\n");
    for declaration in &model.declarations {
        write_doc(&mut output, &declaration.docs);
        match &declaration.kind {
            RustDeclarationKind::Struct(fields) => {
                output.push_str("#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n");
                writeln!(output, "pub struct {} {{", declaration.name).unwrap();
                for field in fields {
                    write_field_doc(&mut output, &field.docs);
                    if field.name.trim_start_matches("r#") != field.wire_name {
                        writeln!(output, "    #[serde(rename = {:?})]", field.wire_name).unwrap();
                    }
                    if field.optional {
                        output
                            .push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
                    }
                    if field.schema.get("type").and_then(Value::as_str) == Some("number") {
                        if field.optional || field.nullable {
                            output.push_str(
                                "    #[serde(serialize_with = \"serialize_optional_go_float64\", deserialize_with = \"deserialize_optional_go_float64\")]\n",
                            );
                        } else {
                            output.push_str(
                                "    #[serde(serialize_with = \"serialize_go_float64\", deserialize_with = \"deserialize_go_float64\")]\n",
                            );
                        }
                    }
                    writeln!(output, "    pub {}: {},", field.name, field.rust_type).unwrap();
                }
                output.push_str("}\n\n");
                render_validation(&mut output, declaration, fields);
            }
            RustDeclarationKind::Defined(rust_type) => {
                output.push_str(
                    "#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n#[serde(transparent)]\n",
                );
                writeln!(
                    output,
                    "pub struct {}(pub {});\n",
                    declaration.name, rust_type
                )
                .unwrap();
            }
        }
        if !has_validation(declaration) {
            writeln!(
                output,
                "impl crate::Validate for {} {{}}\n",
                declaration.name
            )
            .unwrap();
        }
    }

    for operation in &model.catalog.operations {
        writeln!(
            output,
            "pub const {}: &str = {:?};",
            operation_constant(&operation.method),
            operation.method
        )
        .unwrap();
    }
    for event in &model.catalog.events {
        writeln!(
            output,
            "pub const {}: &str = {:?};",
            event_constant(&event.name),
            event.name
        )
        .unwrap();
    }
    output.push('\n');

    for operation in &model.catalog.operations {
        writeln!(
            output,
            "impl crate::NamedRequest for {} {{\n    type Response = {};\n    const METHOD: &'static str = {};\n}}\n",
            operation.request,
            operation.response,
            operation_constant(&operation.method)
        )
        .unwrap();
    }
    for event in &model.catalog.events {
        writeln!(
            output,
            "impl crate::NamedEvent for {} {{\n    const EVENT: &'static str = {};\n}}\n",
            event.data,
            event_constant(&event.name)
        )
        .unwrap();
    }
    let has_float = model.declarations.iter().any(|declaration| {
        matches!(&declaration.kind, RustDeclarationKind::Struct(fields) if fields.iter().any(|field| field.schema.get("type").and_then(Value::as_str) == Some("number")))
    });
    let has_optional_float = model.declarations.iter().any(|declaration| {
        matches!(&declaration.kind, RustDeclarationKind::Struct(fields) if fields.iter().any(|field| (field.optional || field.nullable) && field.schema.get("type").and_then(Value::as_str) == Some("number")))
    });
    if has_float {
        output.push_str(GO_FLOAT64_HELPERS);
    }
    if has_optional_float {
        output.push_str(OPTIONAL_GO_FLOAT64_HELPERS);
    }
    finish(output)
}

const GO_FLOAT64_HELPERS: &str = r#"#[allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::trivially_copy_pass_by_ref
)]
fn serialize_go_float64<S>(value: &f64, serializer: S) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    if value.is_finite()
        && value.fract() == 0.0
        && *value >= i64::MIN as f64
        && *value <= i64::MAX as f64
    {
        serializer.serialize_i64(*value as i64)
    } else {
        serializer.serialize_f64(*value)
    }
}

fn deserialize_go_float64<'de, D>(deserializer: D) -> Result<f64, D::Error>
where
    D: serde::Deserializer<'de>,
{
    f64::deserialize(deserializer)
}

"#;

const OPTIONAL_GO_FLOAT64_HELPERS: &str = r#"#[allow(clippy::ref_option)]
fn serialize_optional_go_float64<S>(value: &Option<f64>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    match value {
        Some(value) => serialize_go_float64(value, serializer),
        None => serializer.serialize_none(),
    }
}

fn deserialize_optional_go_float64<'de, D>(deserializer: D) -> Result<Option<f64>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    Option::<f64>::deserialize(deserializer)
}

"#;

fn has_validation(declaration: &RustDeclaration) -> bool {
    let RustDeclarationKind::Struct(fields) = &declaration.kind else {
        return false;
    };
    declaration.schema.get("x-rtvbp-field-order").is_some()
        || fields.iter().any(|field| {
            field.schema.get("minLength").is_some()
                || field.schema.get("minimum").is_some()
                || field.schema.get("x-rtvbp-nonzero") == Some(&Value::Bool(true))
        })
}

fn render_validation(output: &mut String, declaration: &RustDeclaration, fields: &[RustField]) {
    if !has_validation(declaration) {
        return;
    }
    writeln!(output, "impl crate::Validate for {} {{", declaration.name).unwrap();
    output.push_str("    fn validate(&self) -> Result<(), crate::ValidationError> {\n");
    for field in fields {
        if let Some(min_length) = field.schema.get("minLength").and_then(Value::as_u64) {
            let condition = if field.optional || field.nullable {
                format!(
                    "self.{}.as_ref().is_some_and(|value| value.chars().count() < {min_length})",
                    field.name
                )
            } else {
                format!("self.{}.chars().count() < {min_length}", field.name)
            };
            render_validation_error(
                output,
                &condition,
                &format!(
                    "{} must contain at least {} character(s)",
                    field.wire_name, min_length
                ),
            );
        }
        if let Some(minimum) = field.schema.get("minimum").and_then(Value::as_number) {
            let condition = if field.optional || field.nullable {
                format!(
                    "self.{}.as_ref().is_some_and(|value| *value < {minimum})",
                    field.name
                )
            } else {
                format!("self.{} < {minimum}", field.name)
            };
            render_validation_error(
                output,
                &condition,
                &format!("{} must be at least {minimum}", field.wire_name),
            );
        }
        if field.schema.get("x-rtvbp-nonzero") == Some(&Value::Bool(true)) {
            let condition = if field.optional || field.nullable {
                format!(
                    "self.{}.as_ref().is_some_and(|value| *value == 0)",
                    field.name
                )
            } else {
                format!("self.{} == 0", field.name)
            };
            render_validation_error(
                output,
                &condition,
                &format!("{} must be non-zero", field.wire_name),
            );
        }
    }
    if let Some(orders) = declaration
        .schema
        .get("x-rtvbp-field-order")
        .and_then(Value::as_array)
    {
        for order in orders {
            let lower_wire = order.get("lower").and_then(Value::as_str).unwrap();
            let upper_wire = order.get("upper").and_then(Value::as_str).unwrap();
            let lower = fields
                .iter()
                .find(|field| field.wire_name == lower_wire)
                .unwrap();
            let upper = fields
                .iter()
                .find(|field| field.wire_name == upper_wire)
                .unwrap();
            let condition = match (
                lower.optional || lower.nullable,
                upper.optional || upper.nullable,
            ) {
                (true, true) => format!(
                    "matches!((&self.{}, &self.{}), (Some(lower), Some(upper)) if lower > upper)",
                    lower.name, upper.name
                ),
                (true, false) => format!(
                    "self.{}.as_ref().is_some_and(|lower| lower > &self.{})",
                    lower.name, upper.name
                ),
                (false, true) => format!(
                    "self.{}.as_ref().is_some_and(|upper| &self.{} > upper)",
                    upper.name, lower.name
                ),
                (false, false) => format!("self.{} > self.{}", lower.name, upper.name),
            };
            render_validation_error(
                output,
                &condition,
                &format!("{upper_wire} must be greater than or equal to {lower_wire}"),
            );
        }
    }
    output.push_str("        Ok(())\n    }\n}\n\n");
}

fn render_validation_error(output: &mut String, condition: &str, message: &str) {
    writeln!(
        output,
        "        if {condition} {{\n            return Err(crate::ValidationError::new({message:?}));\n        }}"
    )
    .unwrap();
}

fn render_golden_tests(model: &RustCatalog<'_>) -> Result<String, RustEmitError> {
    let mut output = String::from(RUST_BANNER);
    if model.catalog.fixtures.is_empty() {
        output.push_str("#[test]\nfn generated_catalog_has_no_golden_payloads() {}\n");
        return Ok(finish(output));
    }
    output.push_str("use super::*;\nuse serde::{de::DeserializeOwned, Serialize};\n\n");
    output.push_str(
        "fn assert_round_trip<T>(name: &str, golden: &str)\nwhere\n    T: DeserializeOwned + Serialize,\n{\n    let value: T = serde_json::from_str(golden).unwrap_or_else(|error| panic!(\"{name}: {error}\"));\n    let actual = serde_json::to_string(&value).unwrap();\n    assert_eq!(actual, golden, \"{name}\");\n}\n\n",
    );
    output.push_str(
        "#[test]\n#[allow(clippy::manual_string_new, clippy::too_many_lines, clippy::unreadable_literal)]\nfn generated_golden_payloads_round_trip_exact_bytes() {\n",
    );
    for fixture in &model.catalog.fixtures {
        let bytes =
            String::from_utf8(fixture.bytes.clone()).map_err(|_| RustEmitError::Fixture {
                path: fixture.path.clone(),
                message: "fixture is not UTF-8".to_owned(),
            })?;
        writeln!(
            output,
            "    assert_round_trip::<{}>({:?}, {:?});\n    {{\n        let constructed = {};\n        let actual = serde_json::to_string(&constructed).unwrap();\n        assert_eq!(actual, {:?}, {:?});\n    }}",
            fixture.payload,
            format!("{}/round_trip", fixture.path),
            bytes,
            render_fixture_literal(model, fixture)?,
            bytes,
            format!("{}/construct", fixture.path)
        )
        .unwrap();
    }
    output.push_str("}\n");
    Ok(finish(output))
}

fn render_fixture_literal(
    model: &RustCatalog<'_>,
    fixture: &ResolvedFixture,
) -> Result<String, RustEmitError> {
    let schema =
        model
            .catalog
            .schemas
            .get(&fixture.payload)
            .ok_or_else(|| RustEmitError::Fixture {
                path: fixture.path.clone(),
                message: format!("missing schema {}", fixture.payload),
            })?;
    render_value(
        &fixture.payload,
        schema,
        &fixture.value,
        &model.catalog.schemas,
        Some(&fixture.payload),
    )
}

fn render_value(
    owner: &str,
    schema: &Value,
    value: &Value,
    schemas: &BTreeMap<String, Value>,
    named: Option<&str>,
) -> Result<String, RustEmitError> {
    let object = schema
        .as_object()
        .ok_or_else(|| schema_error(owner, "literal schema is not an object".to_owned()))?;
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        let name = schema_ref_name(reference)
            .ok_or_else(|| schema_error(owner, format!("unsupported reference {reference:?}")))?;
        let target = schemas
            .get(&name)
            .ok_or_else(|| schema_error(owner, format!("dangling reference {reference:?}")))?;
        return render_value(owner, target, value, schemas, Some(&name));
    }

    let wrap = |inner: String| named.map_or(inner.clone(), |name| format!("{name}({inner})"));
    match object.get("type").and_then(Value::as_str) {
        Some("object")
            if object
                .get("properties")
                .and_then(Value::as_object)
                .is_some() =>
        {
            let properties = object["properties"].as_object().unwrap();
            let required = object
                .get("required")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect::<HashSet<_>>();
            let data = value
                .as_object()
                .ok_or_else(|| schema_error(owner, "fixture value is not an object".to_owned()))?;
            let literal_type = named.ok_or_else(|| {
                schema_error(owner, "inline struct literal has no named type".to_owned())
            })?;
            let mut fields = Vec::new();
            for (wire_name, field_schema) in properties {
                let field = resolve_field(
                    owner,
                    wire_name,
                    field_schema,
                    required.contains(wire_name.as_str()),
                    schemas,
                )?;
                let Some(field_value) = data.get(wire_name) else {
                    if field.optional {
                        fields.push(format!("{}: None", field.name));
                        continue;
                    }
                    return Err(schema_error(
                        owner,
                        format!("fixture is missing required field {wire_name:?}"),
                    ));
                };
                let rendered = if field.optional || field.nullable {
                    if field_value.is_null() {
                        "None".to_owned()
                    } else {
                        format!(
                            "Some({})",
                            render_value(owner, &field.schema, field_value, schemas, None)?
                        )
                    }
                } else {
                    render_value(owner, &field.schema, field_value, schemas, None)?
                };
                fields.push(format!("{}: {rendered}", field.name));
            }
            Ok(format!("{literal_type} {{ {} }}", fields.join(", ")))
        }
        Some("object") => {
            let data = value.as_object().ok_or_else(|| {
                schema_error(owner, "fixture map value is not an object".to_owned())
            })?;
            let value_schema = object.get("additionalProperties");
            let mut entries = Vec::new();
            for (key, item) in data {
                let rendered = match value_schema {
                    Some(Value::Bool(true)) | None => render_any(item)?,
                    Some(Value::Bool(false)) => {
                        return Err(schema_error(
                            owner,
                            "closed object fixture contains a value".to_owned(),
                        ));
                    }
                    Some(schema) => render_value(owner, schema, item, schemas, None)?,
                };
                entries.push(format!("({:?}.to_owned(), {rendered})", key));
            }
            let map = match value_schema {
                Some(Value::Bool(true)) | Some(Value::Bool(false)) | None => {
                    format!("serde_json::Map::from_iter([{}])", entries.join(", "))
                }
                Some(_) => format!("std::collections::BTreeMap::from([{}])", entries.join(", ")),
            };
            Ok(wrap(map))
        }
        Some("array") => {
            let values = value
                .as_array()
                .ok_or_else(|| schema_error(owner, "fixture value is not an array".to_owned()))?;
            let items = object
                .get("items")
                .ok_or_else(|| schema_error(owner, "array has no items schema".to_owned()))?;
            let rendered = values
                .iter()
                .map(|value| render_value(owner, items, value, schemas, None))
                .collect::<Result<Vec<_>, _>>()?;
            Ok(wrap(format!("vec![{}]", rendered.join(", "))))
        }
        Some("string") => Ok(wrap(format!(
            "{:?}.to_owned()",
            value.as_str().ok_or_else(|| {
                schema_error(owner, "fixture value is not a string".to_owned())
            })?
        ))),
        Some("boolean") => Ok(wrap(
            value
                .as_bool()
                .ok_or_else(|| schema_error(owner, "fixture value is not a boolean".to_owned()))?
                .to_string(),
        )),
        Some("integer") => Ok(wrap(
            value
                .as_i64()
                .ok_or_else(|| schema_error(owner, "fixture value is not an i64".to_owned()))?
                .to_string(),
        )),
        Some("number") => {
            let number = value
                .as_number()
                .ok_or_else(|| schema_error(owner, "fixture value is not a number".to_owned()))?;
            let rendered = if number.is_i64() || number.is_u64() {
                format!("{number}.0")
            } else {
                number.to_string()
            };
            Ok(wrap(rendered))
        }
        None if object.keys().all(|key| key == "description") => Ok(wrap(render_any(value)?)),
        _ => Err(schema_error(
            owner,
            "unsupported fixture literal schema".to_owned(),
        )),
    }
}

fn render_any(value: &Value) -> Result<String, RustEmitError> {
    Ok(format!(
        "serde_json::json!({})",
        serde_json::to_string(value)?
    ))
}

fn remove_null(schema: &Value) -> Option<Value> {
    let mut normalized = schema.clone();
    let object = normalized.as_object_mut()?;
    let single_type = if let Some(Value::Array(types)) = object.get_mut("type") {
        types.retain(|value| value.as_str() != Some("null"));
        if types.len() == 1 {
            Some(types[0].clone())
        } else {
            None
        }
    } else {
        None
    };
    if let Some(single_type) = single_type {
        object.insert("type".to_owned(), single_type);
        return Some(normalized);
    }
    if let Some(Value::Array(branches)) = object.get("anyOf") {
        let non_null = branches
            .iter()
            .filter(|branch| branch.get("type").and_then(Value::as_str) != Some("null"))
            .cloned()
            .collect::<Vec<_>>();
        if non_null.len() == 1 && non_null.len() + 1 == branches.len() {
            let mut branch = non_null.into_iter().next().unwrap();
            if let (Some(branch), Some(outer)) = (branch.as_object_mut(), schema.as_object()) {
                for (key, value) in outer {
                    if key != "anyOf" && key != "x-rtvbp-presence" && key != "description" {
                        branch.entry(key.clone()).or_insert_with(|| value.clone());
                    }
                }
            }
            return Some(branch);
        }
    }
    None
}

fn contains_null(schema: &Value) -> bool {
    let Some(object) = schema.as_object() else {
        return false;
    };
    match object.get("type") {
        Some(Value::String(value)) => value == "null",
        Some(Value::Array(values)) => values.iter().any(|value| value.as_str() == Some("null")),
        _ => object
            .get("anyOf")
            .and_then(Value::as_array)
            .is_some_and(|branches| branches.iter().any(contains_null)),
    }
}

fn schema_ref_name(reference: &str) -> Option<String> {
    reference
        .strip_prefix("#/schemas/")
        .map(|name| name.replace("~1", "/").replace("~0", "~"))
}

fn schema_error(schema: &str, message: String) -> RustEmitError {
    RustEmitError::Schema {
        schema: schema.to_owned(),
        message,
    }
}

fn validate_type_identifier(value: &str) -> Result<(), String> {
    let mut chars = value.chars();
    if !chars
        .next()
        .is_some_and(|character| character.is_ascii_uppercase())
        || !chars.all(|character| character.is_ascii_alphanumeric() || character == '_')
    {
        return Err(format!("invalid Rust type identifier {value:?}"));
    }
    Ok(())
}

fn rust_field_name(value: &str) -> Result<String, String> {
    let name = snake_wire_name(value);
    if name.is_empty()
        || !name
            .chars()
            .next()
            .is_some_and(|character| character.is_ascii_alphabetic() || character == '_')
    {
        return Err("wire name does not produce a Rust identifier".to_owned());
    }
    if RUST_KEYWORDS.contains(&name.as_str()) {
        Ok(format!("r#{name}"))
    } else {
        Ok(name)
    }
}

fn snake_wire_name(value: &str) -> String {
    let mut output = String::new();
    let mut previous_was_separator = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if character.is_ascii_uppercase() && !previous_was_separator && !output.ends_with('_') {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !previous_was_separator && !output.is_empty() {
            output.push('_');
            previous_was_separator = true;
        }
    }
    while output.ends_with('_') {
        output.pop();
    }
    output
}

fn screaming_wire_name(value: &str) -> String {
    snake_wire_name(value).to_ascii_uppercase()
}

fn operation_constant(method: &str) -> String {
    format!("METHOD_{}", screaming_wire_name(method))
}

fn event_constant(event: &str) -> String {
    format!("EVENT_{}", screaming_wire_name(event))
}

fn sanitize_module(value: &str) -> String {
    snake_wire_name(value).replace('_', "")
}

fn write_doc(output: &mut String, docs: &str) {
    for line in docs.lines() {
        writeln!(output, "/// {line}").unwrap();
    }
}

fn write_field_doc(output: &mut String, docs: &str) {
    for line in docs.lines() {
        writeln!(output, "    /// {line}").unwrap();
    }
}

fn finish(mut output: String) -> String {
    while output.ends_with('\n') {
        output.pop();
    }
    output.push('\n');
    output
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
    "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
    "unsafe", "use", "where", "while",
];

#[allow(dead_code)]
fn _assert_envelope_type(_: &EnvelopeSpec) {}
