use std::collections::{BTreeMap, HashMap, HashSet};
use std::fmt::Write as _;
use std::path::PathBuf;

use rtvbp_spec_model::{CatalogId, ControlFrame, EnvelopeSpec, FrameKind, Role};
use serde_json::{Map, Value, json};
use thiserror::Error;

use super::GeneratedFile;
use crate::resolve::{ResolvedCatalog, ResolvedFixture, ResolvedOperation};

const BANNER: &str =
    "// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.\n\n";

#[derive(Debug, Error)]
pub enum TypeScriptEmitError {
    #[error("schema {schema:?}: {message}")]
    Schema { schema: String, message: String },
    #[error("fixture {path:?}: {message}")]
    Fixture { path: String, message: String },
    #[error("envelope {envelope:?}: {message}")]
    Envelope { envelope: String, message: String },
    #[error(
        "generated TypeScript role surface {surface:?} maps both {first:?} and {second:?} to method {method:?}"
    )]
    RoleMethodCollision {
        surface: String,
        method: String,
        first: String,
        second: String,
    },
    #[error("could not encode generated TypeScript literal: {0}")]
    Json(#[from] serde_json::Error),
}

#[derive(Clone, Copy)]
enum LocalRole {
    Application,
    Voice,
}

impl LocalRole {
    const ALL: [Self; 2] = [Self::Application, Self::Voice];

    const fn name(self) -> &'static str {
        match self {
            Self::Application => "Application",
            Self::Voice => "Voice",
        }
    }

    const fn lower(self) -> &'static str {
        match self {
            Self::Application => "application",
            Self::Voice => "voice",
        }
    }

    const fn spec_role(self) -> Role {
        match self {
            Self::Application => Role::Application,
            Self::Voice => Role::Voice,
        }
    }

    const fn owns(self, role: Role) -> bool {
        matches!(
            (self, role),
            (Self::Application, Role::Application) | (Self::Voice, Role::Voice) | (_, Role::Both)
        )
    }

    const fn receives(self, emitted_by: Role) -> bool {
        matches!(
            (self, emitted_by),
            (Self::Application, Role::Voice) | (Self::Voice, Role::Application) | (_, Role::Both)
        )
    }
}

pub fn emit_typescript(
    catalog: &ResolvedCatalog,
) -> Result<Vec<GeneratedFile>, TypeScriptEmitError> {
    validate_catalog(catalog)?;
    let module = catalog_module(&catalog.id);
    Ok(vec![
        GeneratedFile {
            path: PathBuf::from(format!("src/generated/zz_generated_{module}_types.ts")),
            bytes: render_types(catalog)?.into_bytes(),
        },
        GeneratedFile {
            path: PathBuf::from(format!("src/generated/zz_generated_{module}_roles.ts")),
            bytes: render_roles(catalog)?.into_bytes(),
        },
        GeneratedFile {
            path: PathBuf::from(format!("src/generated/zz_generated_{module}.ts")),
            bytes: render_catalog_barrel(&module).into_bytes(),
        },
        GeneratedFile {
            path: PathBuf::from(format!("test/zz_generated_{module}.test.ts")),
            bytes: render_catalog_tests(catalog)?.into_bytes(),
        },
    ])
}

pub fn emit_typescript_envelope(
    envelope: &EnvelopeSpec,
) -> Result<Vec<GeneratedFile>, TypeScriptEmitError> {
    let module = envelope_module(&envelope.id);
    Ok(vec![
        GeneratedFile {
            path: PathBuf::from(format!("src/generated/zz_generated_{module}_envelope.ts")),
            bytes: render_envelope(envelope)?.into_bytes(),
        },
        GeneratedFile {
            path: PathBuf::from(format!("test/zz_generated_{module}_envelope.test.ts")),
            bytes: render_envelope_tests(envelope)?.into_bytes(),
        },
    ])
}

pub fn emit_typescript_index(
    catalogs: &[CatalogId],
    envelopes: &[EnvelopeSpec],
) -> Vec<GeneratedFile> {
    let mut output = String::from(BANNER);
    output.push_str("export * as profiles from \"./zz_generated_profiles.ts\";\n");
    for catalog in catalogs {
        let module = catalog_module(catalog);
        let namespace = lower_camel(&format!("{} v{}", catalog.name, catalog.major));
        writeln!(
            output,
            "export * as {namespace} from \"./zz_generated_{module}.ts\";"
        )
        .unwrap();
    }
    for envelope in envelopes {
        let module = envelope_module(&envelope.id);
        let namespace = lower_camel(&envelope.id);
        writeln!(
            output,
            "export * as {namespace} from \"./zz_generated_{module}_envelope.ts\";"
        )
        .unwrap();
    }
    vec![GeneratedFile {
        path: PathBuf::from("src/generated/zz_generated_index.ts"),
        bytes: finish(output).into_bytes(),
    }]
}

fn render_types(catalog: &ResolvedCatalog) -> Result<String, TypeScriptEmitError> {
    let mut output = String::from(BANNER);
    output.push_str(
        "import { decodeWireJson, encodeWireJson, type WireEncodable, type WireJsonValue } from \"../wire.ts\";\n",
    );
    output.push_str(
        "import { assertCatalogValue, serializeCatalogValue, validateCatalogValue, type SchemaRegistry, type ValidationIssue } from \"../validation.ts\";\n\n",
    );
    let prefix = catalog_prefix(&catalog.id);
    writeln!(
        output,
        "export const {prefix}_CATALOG_ID = {:?} as const;\n",
        catalog.id.to_string()
    )
    .unwrap();
    writeln!(output, "export const {prefix}_SCHEMAS =").unwrap();
    let schemas = serde_json::to_string_pretty(&catalog.schemas)?;
    output.push_str(&indent(&schemas, 0));
    output.push_str(" as const satisfies SchemaRegistry;\n\n");

    for (name, schema) in &catalog.schemas {
        render_declaration(&mut output, name, schema, &catalog.schemas)?;
    }

    for operation in &catalog.operations {
        writeln!(
            output,
            "export const {} = {:?} as const;",
            operation_constant(&operation.method),
            operation.method
        )
        .unwrap();
    }
    if !catalog.operations.is_empty() {
        output.push('\n');
    }
    for event in &catalog.events {
        writeln!(
            output,
            "export const {} = {:?} as const;",
            event_constant(&event.name),
            event.name
        )
        .unwrap();
    }
    if !catalog.events.is_empty() {
        output.push('\n');
    }

    for name in catalog.schemas.keys() {
        writeln!(
            output,
            "export function validate{name}(value: unknown): readonly ValidationIssue[] {{\n  return validateCatalogValue(value, {name:?}, {prefix}_SCHEMAS);\n}}\n"
        )
        .unwrap();
        writeln!(
            output,
            "export function assert{name}(value: unknown): asserts value is {name} {{\n  assertCatalogValue(value, {name:?}, {prefix}_SCHEMAS);\n}}\n"
        )
        .unwrap();
        writeln!(
            output,
            "export function serialize{name}(value: {name}): WireEncodable {{\n  return serializeCatalogValue(value, {name:?}, {prefix}_SCHEMAS);\n}}\n"
        )
        .unwrap();
        writeln!(
            output,
            "export function encode{name}(value: {name}): string {{\n  return encodeWireJson(serialize{name}(value));\n}}\n"
        )
        .unwrap();
        writeln!(
            output,
            "export function decode{name}(bytes: string): {name} {{\n  const value: WireJsonValue = decodeWireJson(bytes);\n  assert{name}(value);\n  return value as {name};\n}}\n"
        )
        .unwrap();
    }
    Ok(finish(output))
}

fn render_declaration(
    output: &mut String,
    name: &str,
    schema: &Value,
    schemas: &BTreeMap<String, Value>,
) -> Result<(), TypeScriptEmitError> {
    let object = schema
        .as_object()
        .ok_or_else(|| schema_error(name, "schema root must be an object"))?;
    if let Some(description) = object.get("description").and_then(Value::as_str) {
        writeln!(output, "/** {} */", one_line(description)).unwrap();
    }
    if let Some(properties) = object.get("properties").and_then(Value::as_object) {
        let required = required_fields(object);
        writeln!(output, "export interface {name} {{").unwrap();
        for (wire_name, field_schema) in properties {
            let field = field_schema.as_object().ok_or_else(|| {
                schema_error(
                    name,
                    &format!("field {wire_name:?} is not an object schema"),
                )
            })?;
            if let Some(description) = field.get("description").and_then(Value::as_str) {
                writeln!(output, "  /** {} */", one_line(description)).unwrap();
            }
            let optional = !required.contains(wire_name.as_str());
            let nullable =
                field.get("x-rtvbp-presence").and_then(Value::as_str) == Some("nullable");
            let normalized = if optional || nullable {
                remove_null(field_schema).unwrap_or_else(|| field_schema.clone())
            } else {
                field_schema.clone()
            };
            let mut field_type = ts_type(name, &normalized, schemas)?;
            if nullable {
                field_type.push_str(" | null");
            }
            writeln!(
                output,
                "  readonly {wire_name:?}{}: {field_type};",
                if optional { "?" } else { "" }
            )
            .unwrap();
        }
        output.push_str("}\n\n");
    } else {
        writeln!(
            output,
            "export type {name} = {};\n",
            ts_type(name, schema, schemas)?
        )
        .unwrap();
    }
    Ok(())
}

fn ts_type(
    owner: &str,
    schema: &Value,
    schemas: &BTreeMap<String, Value>,
) -> Result<String, TypeScriptEmitError> {
    let object = schema
        .as_object()
        .ok_or_else(|| schema_error(owner, "type schema is not an object"))?;
    if let Some(reference) = object.get("$ref") {
        let reference = reference
            .as_str()
            .ok_or_else(|| schema_error(owner, "$ref is not a string"))?;
        let name = reference
            .strip_prefix("#/schemas/")
            .map(|name| name.replace("~1", "/").replace("~0", "~"))
            .ok_or_else(|| schema_error(owner, &format!("unsupported reference {reference:?}")))?;
        if !schemas.contains_key(&name) {
            return Err(schema_error(
                owner,
                &format!("dangling reference {reference:?}"),
            ));
        }
        return Ok(name);
    }
    if contains_null(schema)
        && let Some(normalized) = remove_null(schema)
    {
        return Ok(format!("{} | null", ts_type(owner, &normalized, schemas)?));
    }
    match object.get("type").and_then(Value::as_str) {
        Some("string") => Ok("string".to_owned()),
        Some("boolean") => Ok("boolean".to_owned()),
        Some("integer" | "number") => Ok("number".to_owned()),
        Some("null") => Ok("null".to_owned()),
        Some("array") => {
            let items = object
                .get("items")
                .ok_or_else(|| schema_error(owner, "array has no items schema"))?;
            Ok(format!(
                "readonly {}[]",
                parenthesize_union(ts_type(owner, items, schemas)?)
            ))
        }
        Some("object") => {
            if let Some(properties) = object.get("properties").and_then(Value::as_object) {
                if properties.is_empty() {
                    return Ok("Readonly<Record<string, never>>".to_owned());
                }
                let required = required_fields(object);
                let mut fields = Vec::new();
                for (name, child) in properties {
                    let optional = !required.contains(name.as_str());
                    let normalized = if optional {
                        remove_null(child).unwrap_or_else(|| child.clone())
                    } else {
                        child.clone()
                    };
                    fields.push(format!(
                        "readonly {name:?}{}: {}",
                        if optional { "?" } else { "" },
                        ts_type(owner, &normalized, schemas)?
                    ));
                }
                Ok(format!("Readonly<{{ {} }}>", fields.join("; ")))
            } else {
                Ok(
                    if object.get("additionalProperties") == Some(&Value::Bool(true)) {
                        "Readonly<Record<string, WireJsonValue>>".to_owned()
                    } else {
                        "Readonly<Record<string, never>>".to_owned()
                    },
                )
            }
        }
        None if object.keys().all(|key| {
            matches!(
                key.as_str(),
                "description" | "format" | "x-go-type" | "x-rtvbp-presence"
            )
        }) =>
        {
            Ok("WireJsonValue".to_owned())
        }
        other => Err(schema_error(
            owner,
            &format!("unsupported schema type {other:?}"),
        )),
    }
}

fn render_roles(catalog: &ResolvedCatalog) -> Result<String, TypeScriptEmitError> {
    validate_role_names(catalog)?;
    let module = catalog_module(&catalog.id);
    let mut output = String::from(BANNER);
    writeln!(
        output,
        "import * as types from \"./zz_generated_{module}_types.ts\";"
    )
    .unwrap();
    output.push_str("import { ProtocolHandlerError, type EventRegistration, type HandlerContext, type MaybePromise, type Notifier, type NotifyOptions, type Requester, type RequestOptions, type RequestRegistration, type RoleAdapter, type UnknownHooks } from \"../protocol.ts\";\n\n");

    for role in LocalRole::ALL {
        render_handler(&mut output, catalog, role);
        render_event_handler(&mut output, catalog, role);
        render_adapter(&mut output, catalog, role);
        render_peer(&mut output, catalog, role);
        render_events(&mut output, catalog, role);
    }
    Ok(finish(output))
}

fn render_handler(output: &mut String, catalog: &ResolvedCatalog, role: LocalRole) {
    let name = role.name();
    writeln!(
        output,
        "/** Operations implemented by the local {name} role. */\nexport interface {name}Handler {{"
    )
    .unwrap();
    for operation in catalog
        .operations
        .iter()
        .filter(|operation| role.owns(operation.handled_by))
    {
        writeln!(
            output,
            "  {}(context: HandlerContext, request: types.{}): MaybePromise<types.{}>;",
            member_name(&operation.method),
            operation.request,
            operation.response
        )
        .unwrap();
    }
    output.push_str("}\n\n");

    let const_name = format!("{}_HANDLER_METHODS", role.lower().to_ascii_uppercase());
    writeln!(output, "export const {const_name} = [").unwrap();
    for operation in catalog
        .operations
        .iter()
        .filter(|operation| role.owns(operation.handled_by))
    {
        writeln!(output, "  types.{},", operation_constant(&operation.method)).unwrap();
    }
    for (operation, _) in rejections(catalog, role) {
        writeln!(output, "  types.{},", operation_constant(&operation.method)).unwrap();
    }
    output.push_str("] as const;\n\n");

    writeln!(output, "export function {}RequestHandlers(handler: {name}Handler): readonly RequestRegistration[] {{\n  return [", role.lower()).unwrap();
    for operation in catalog
        .operations
        .iter()
        .filter(|operation| role.owns(operation.handled_by))
    {
        let function = member_name(&operation.method);
        writeln!(
            output,
            "    {{\n      method: types.{},\n      terminal: {},\n      async handle(context, payload) {{\n        types.assert{}(payload);\n        const response = await handler.{function}(context, payload);\n        return types.serialize{}(response);\n      }},\n    }},",
            operation_constant(&operation.method),
            operation.terminal,
            operation.request,
            operation.response,
        )
        .unwrap();
    }
    for (operation, rejection) in rejections(catalog, role) {
        writeln!(
            output,
            "    {{\n      method: types.{},\n      terminal: false,\n      async handle() {{\n        throw new ProtocolHandlerError({{ code: {}, message: {:?} }});\n      }},\n    }},",
            operation_constant(&operation.method),
            rejection.code,
            rejection.message
        )
        .unwrap();
    }
    output.push_str("  ];\n}\n\n");
}

fn render_event_handler(output: &mut String, catalog: &ResolvedCatalog, role: LocalRole) {
    let name = role.name();
    writeln!(output, "/** Peer events received by the local {name} role. */\nexport interface {name}EventHandler {{").unwrap();
    for event in catalog
        .events
        .iter()
        .filter(|event| role.receives(event.emitted_by))
    {
        writeln!(
            output,
            "  {}(context: HandlerContext, event: types.{}): MaybePromise<void>;",
            member_name(&event.name),
            event.data
        )
        .unwrap();
    }
    output.push_str("}\n\n");
    writeln!(output, "export function {}EventHandlers(handler: {name}EventHandler): readonly EventRegistration[] {{\n  return [", role.lower()).unwrap();
    for event in catalog
        .events
        .iter()
        .filter(|event| role.receives(event.emitted_by))
    {
        let function = member_name(&event.name);
        writeln!(
            output,
            "    {{\n      event: types.{},\n      async handle(context, data) {{\n        types.assert{}(data);\n        await handler.{function}(context, data);\n      }},\n    }},",
            event_constant(&event.name),
            event.data
        )
        .unwrap();
    }
    output.push_str("  ];\n}\n\n");
}

fn render_adapter(output: &mut String, _catalog: &ResolvedCatalog, role: LocalRole) {
    let name = role.name();
    let lower = role.lower();
    writeln!(
        output,
        "/** Assemble generated dispatch and explicit unknown-message hooks for the {name} role. */\nexport function {lower}Adapter(\n  handler: {name}Handler,\n  eventHandler: {name}EventHandler,\n  unknown: UnknownHooks = {{}},\n): RoleAdapter {{\n  return {{\n    requests: {lower}RequestHandlers(handler),\n    events: {lower}EventHandlers(eventHandler),\n    unknown,\n  }};\n}}\n"
    )
    .unwrap();
}

fn render_peer(output: &mut String, catalog: &ResolvedCatalog, role: LocalRole) {
    let name = role.name();
    writeln!(output, "/** Typed client for operations implemented by a peer in the {name} role. */\nexport class {name}Peer {{\n  private readonly requester: Requester;\n\n  constructor(requester: Requester) {{\n    this.requester = requester;\n  }}\n").unwrap();
    for operation in catalog
        .operations
        .iter()
        .filter(|operation| role.owns(operation.handled_by))
    {
        let function = member_name(&operation.method);
        writeln!(
            output,
            "  async {function}(request: types.{}, options: RequestOptions = {{}}): Promise<types.{}> {{\n    const payload = types.serialize{}(request);\n    const response = await this.requester.request(types.{}, payload, {{ ...options, terminal: {} }});\n    const value = response ?? {{}};\n    types.assert{}(value);\n    return value;\n  }}\n",
            operation.request,
            operation.response,
            operation.request,
            operation_constant(&operation.method),
            operation.terminal,
            operation.response,
        )
        .unwrap();
    }
    output.push_str("}\n\n");
}

fn render_events(output: &mut String, catalog: &ResolvedCatalog, role: LocalRole) {
    let name = role.name();
    writeln!(output, "/** Typed emitter for events owned by the {name} role. */\nexport class {name}Events {{\n  private readonly notifier: Notifier;\n\n  constructor(notifier: Notifier) {{\n    this.notifier = notifier;\n  }}\n").unwrap();
    for event in catalog
        .events
        .iter()
        .filter(|event| role.owns(event.emitted_by))
    {
        let function = member_name(&event.name);
        writeln!(
            output,
            "  async {function}(event: types.{}, options: NotifyOptions = {{}}): Promise<void> {{\n    await this.notifier.notify(types.{}, types.serialize{}(event), options);\n  }}\n",
            event.data,
            event_constant(&event.name),
            event.data,
        )
        .unwrap();
    }
    output.push_str("}\n\n");
}

fn render_catalog_barrel(module: &str) -> String {
    finish(format!(
        "{BANNER}export * from \"./zz_generated_{module}_types.ts\";\nexport * from \"./zz_generated_{module}_roles.ts\";\n"
    ))
}

fn render_catalog_tests(catalog: &ResolvedCatalog) -> Result<String, TypeScriptEmitError> {
    let module = catalog_module(&catalog.id);
    let mut output = String::from(BANNER);
    output.push_str(
        "import assert from \"node:assert/strict\";\nimport test from \"node:test\";\n\n",
    );
    writeln!(
        output,
        "import * as catalog from \"../src/generated/zz_generated_{module}_types.ts\";\n"
    )
    .unwrap();
    writeln!(
        output,
        "import * as roles from \"../src/generated/zz_generated_{module}_roles.ts\";"
    )
    .unwrap();
    output.push_str("import { ProtocolHandlerError, type HandlerContext } from \"../src/protocol.ts\";\nimport { encodeWireJson } from \"../src/wire.ts\";\n\nconst CONTEXT = { signal: new AbortController().signal } as HandlerContext;\n\n");
    for fixture in &catalog.fixtures {
        render_fixture_tests(&mut output, fixture)?;
    }
    for operation in &catalog.operations {
        render_invalid_tests(&mut output, catalog, operation)?;
    }
    for role in LocalRole::ALL {
        render_generated_role_tests(&mut output, catalog, role)?;
    }
    Ok(finish(output))
}

fn render_generated_role_tests(
    output: &mut String,
    catalog: &ResolvedCatalog,
    role: LocalRole,
) -> Result<(), TypeScriptEmitError> {
    let name = role.name();
    let lower = role.lower();
    let owned = catalog
        .operations
        .iter()
        .filter(|operation| role.owns(operation.handled_by))
        .collect::<Vec<_>>();
    writeln!(
        output,
        "test({:?}, async () => {{\n  const handler: roles.{name}Handler = {{",
        format!("generated {lower} request adapter preserves payloads and terminal metadata")
    )
    .unwrap();
    for operation in &owned {
        let example = operation.examples.first().expect("validated example");
        writeln!(
            output,
            "    {}(_context, request) {{\n      assert.deepEqual(request, {});\n      return {};\n    }},",
            member_name(&operation.method),
            serde_json::to_string(&example.request)?,
            serde_json::to_string(&example.response)?
        )
        .unwrap();
    }
    writeln!(
        output,
        "  }};\n  const registrations = roles.{lower}RequestHandlers(handler);\n  assert.deepEqual(\n    registrations.map((registration) => [registration.method, registration.terminal]),\n    ["
    )
    .unwrap();
    for operation in &owned {
        writeln!(
            output,
            "      [catalog.{}, {}],",
            operation_constant(&operation.method),
            operation.terminal
        )
        .unwrap();
    }
    for (operation, _) in rejections(catalog, role) {
        writeln!(
            output,
            "      [catalog.{}, false],",
            operation_constant(&operation.method)
        )
        .unwrap();
    }
    output.push_str("    ],\n  );\n");
    for operation in &owned {
        let example = operation.examples.first().expect("validated example");
        let request = serde_json::to_string(&example.request)?;
        let response = serde_json::to_string(&example.response)?;
        writeln!(
            output,
            "  {{\n    const registration = registrations.find((candidate) => candidate.method === catalog.{})!;\n    const reply = await registration.handle(CONTEXT, catalog.decode{}({request:?}));\n    assert.equal(encodeWireJson(reply), {response:?});\n  }}",
            operation_constant(&operation.method),
            operation.request,
        )
        .unwrap();
    }
    for (operation, rejection) in rejections(catalog, role) {
        let example = operation.examples.first().expect("validated example");
        let request = serde_json::to_string(&example.request)?;
        writeln!(
            output,
            "  await assert.rejects(\n    registrations.find((candidate) => candidate.method === catalog.{})!.handle(CONTEXT, catalog.decode{}({request:?})),\n    (error: unknown) => {{\n      assert.ok(error instanceof ProtocolHandlerError);\n      assert.equal(error.wire.code, {});\n      assert.equal(error.wire.message, {:?});\n      return true;\n    }},\n  );",
            operation_constant(&operation.method),
            operation.request,
            rejection.code,
            rejection.message,
        )
        .unwrap();
    }
    writeln!(output, "}});\n").unwrap();

    for operation in &owned {
        let example = operation.examples.first().expect("validated example");
        let request = serde_json::to_string(&example.request)?;
        let response = serde_json::to_string(&example.response)?;
        writeln!(
            output,
            "test({:?}, async () => {{\n  const peer = new roles.{name}Peer({{\n    async request(method, params, options) {{\n      assert.equal(method, catalog.{});\n      assert.equal(encodeWireJson(params), {request:?});\n      assert.equal(options?.terminal, {});\n      return catalog.decode{}({response:?});\n    }},\n  }});\n  assert.deepEqual(await peer.{}({}), {});\n}});\n",
            format!("generated {lower} peer calls {}", operation.method),
            operation_constant(&operation.method),
            operation.terminal,
            operation.response,
            member_name(&operation.method),
            request,
            response,
        )
        .unwrap();
    }

    let received = catalog
        .events
        .iter()
        .filter(|event| role.receives(event.emitted_by))
        .collect::<Vec<_>>();
    writeln!(
        output,
        "test({:?}, async () => {{\n  const handler: roles.{name}EventHandler = {{",
        format!("generated {lower} event adapter validates every peer event")
    )
    .unwrap();
    for event in &received {
        let example = event.examples.first().expect("validated example");
        writeln!(
            output,
            "    {}(_context, event) {{ assert.deepEqual(event, {}); }},",
            member_name(&event.name),
            serde_json::to_string(&example.data)?
        )
        .unwrap();
    }
    writeln!(
        output,
        "  }};\n  const registrations = roles.{lower}EventHandlers(handler);"
    )
    .unwrap();
    for event in &received {
        let example = event.examples.first().expect("validated example");
        let data = serde_json::to_string(&example.data)?;
        writeln!(
            output,
            "  await registrations.find((candidate) => candidate.event === catalog.{})!.handle(CONTEXT, catalog.decode{}({data:?}));",
            event_constant(&event.name),
            event.data
        )
        .unwrap();
    }
    output.push_str("  const unknown = { request: async () => {}, event: async () => {} };\n");
    writeln!(
        output,
        "  assert.equal(roles.{lower}Adapter(handler as unknown as roles.{name}Handler, handler, unknown).unknown, unknown);\n}});\n"
    )
    .unwrap();

    for event in catalog
        .events
        .iter()
        .filter(|event| role.owns(event.emitted_by))
    {
        let example = event.examples.first().expect("validated example");
        let data = serde_json::to_string(&example.data)?;
        writeln!(
            output,
            "test({:?}, async () => {{\n  const events = new roles.{name}Events({{\n    async notify(event, payload) {{\n      assert.equal(event, catalog.{});\n      assert.equal(encodeWireJson(payload), {data:?});\n    }},\n  }});\n  await events.{}({});\n}});\n",
            format!("generated {lower} event emitter sends {}", event.name),
            event_constant(&event.name),
            member_name(&event.name),
            data,
        )
        .unwrap();
    }
    Ok(())
}

fn render_fixture_tests(
    output: &mut String,
    fixture: &ResolvedFixture,
) -> Result<(), TypeScriptEmitError> {
    let bytes = std::str::from_utf8(&fixture.bytes).map_err(|_| TypeScriptEmitError::Fixture {
        path: fixture.path.clone(),
        message: "fixture is not UTF-8".to_owned(),
    })?;
    let literal = serde_json::to_string(&fixture.value)?;
    writeln!(
        output,
        "test({:?}, () => {{\n  const decoded = catalog.decode{}({bytes:?});\n  assert.equal(catalog.encode{}(decoded), {bytes:?});\n}});\n",
        format!("{}/round_trip", fixture.path),
        fixture.payload,
        fixture.payload
    )
    .unwrap();
    writeln!(
        output,
        "test({:?}, () => {{\n  const constructed: catalog.{} = {literal};\n  assert.equal(catalog.encode{}(constructed), {bytes:?});\n}});\n",
        format!("{}/construct", fixture.path),
        fixture.payload,
        fixture.payload,
    )
    .unwrap();
    Ok(())
}

fn render_invalid_tests(
    output: &mut String,
    catalog: &ResolvedCatalog,
    operation: &ResolvedOperation,
) -> Result<(), TypeScriptEmitError> {
    for (direction, schema_name, canonical) in [
        (
            "request",
            &operation.request,
            &operation
                .examples
                .first()
                .expect("validated example")
                .request,
        ),
        (
            "response",
            &operation.response,
            &operation
                .examples
                .first()
                .expect("validated example")
                .response,
        ),
    ] {
        let schema = catalog
            .schemas
            .get(schema_name)
            .ok_or_else(|| schema_error(schema_name, "missing schema"))?;
        writeln!(
            output,
            "test({:?}, () => {{\n  assert.throws(() => catalog.decode{}(\"{{\"));\n}});\n",
            format!("{}/{direction}/malformed_json", operation.method),
            schema_name
        )
        .unwrap();
        for (name, invalid) in semantic_invalid_cases(schema, canonical) {
            let encoded = serde_json::to_string(&invalid)?;
            writeln!(
                output,
                "test({:?}, () => {{\n  assert.throws(() => catalog.decode{}({encoded:?}), (error: unknown) => {{\n    assert.equal((error as Error).name, \"ProtocolValidationError\");\n    return true;\n  }});\n}});\n",
                format!("{}/{direction}/{name}", operation.method),
                schema_name
            )
            .unwrap();
        }
    }
    Ok(())
}

fn semantic_invalid_cases(schema: &Value, canonical: &Value) -> Vec<(String, Value)> {
    let mut cases = Vec::new();
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        return cases;
    };
    for (field, rule) in properties {
        if rule.get("minLength").is_some() {
            push_invalid(
                &mut cases,
                canonical,
                field,
                Value::String(String::new()),
                "min_length",
            );
        }
        if let Some(minimum) = rule.get("minimum").and_then(Value::as_i64)
            && let Some(below) = minimum.checked_sub(1)
        {
            push_invalid(&mut cases, canonical, field, Value::from(below), "minimum");
        }
        if rule.get("x-rtvbp-nonzero") == Some(&Value::Bool(true)) {
            push_invalid(&mut cases, canonical, field, Value::from(0), "nonzero");
        }
    }
    if let Some(orderings) = schema.get("x-rtvbp-field-order").and_then(Value::as_array) {
        for ordering in orderings {
            let (Some(lower), Some(upper)) = (
                ordering.get("lower").and_then(Value::as_str),
                ordering.get("upper").and_then(Value::as_str),
            ) else {
                continue;
            };
            let mut invalid = canonical.clone();
            if let Some(object) = invalid.as_object_mut() {
                object.insert(lower.to_owned(), json!(2));
                object.insert(upper.to_owned(), json!(1));
                cases.push((format!("field_order_{lower}_{upper}"), invalid));
            }
        }
    }
    cases
}

fn push_invalid(
    cases: &mut Vec<(String, Value)>,
    canonical: &Value,
    field: &str,
    value: Value,
    rule: &str,
) {
    let mut invalid = canonical.clone();
    if let Some(object) = invalid.as_object_mut() {
        object.insert(field.to_owned(), value);
        cases.push((format!("{field}_{rule}"), invalid));
    }
}

fn render_envelope(envelope: &EnvelopeSpec) -> Result<String, TypeScriptEmitError> {
    let mut output = String::from(BANNER);
    output.push_str(
        "import { createEnvelopeCodec, type EnvelopeDescriptor } from \"../envelope.ts\";\n\n",
    );
    let prefix = envelope_prefix(&envelope.id);
    for error in &envelope.error_codes {
        writeln!(
            output,
            "/** {} */\nexport const {prefix}_ERROR_{} = {};",
            one_line(&error.description),
            screaming(&error.name),
            error.code
        )
        .unwrap();
    }
    if !envelope.error_codes.is_empty() {
        output.push('\n');
    }
    writeln!(output, "export const {prefix}_DESCRIPTOR = {{").unwrap();
    writeln!(output, "  id: {:?},", envelope.id).unwrap();
    output.push_str("  constants: [\n");
    for constant in &envelope.constants {
        writeln!(output, "    [{:?}, {:?}],", constant.name, constant.value).unwrap();
    }
    output.push_str("  ],\n  frames: [\n");
    for frame in &envelope.frames {
        write!(
            output,
            "    {{ kind: {:?}, discriminator: {}, ",
            frame_kind(frame.kind),
            field_literal(&frame.discriminator)
        )
        .unwrap();
        if let Some(id) = &frame.id {
            write!(output, "id: {}, ", field_literal(id)).unwrap();
        }
        write!(output, "payload: {}", field_literal(&frame.payload)).unwrap();
        if let Some(error) = &frame.error {
            write!(output, ", error: {}", field_literal(error)).unwrap();
        }
        output.push_str(" },\n");
    }
    output.push_str("  ],\n  error: {\n");
    writeln!(output, "    code: {},", field_literal(&envelope.error.code)).unwrap();
    writeln!(
        output,
        "    message: {},",
        field_literal(&envelope.error.message)
    )
    .unwrap();
    writeln!(output, "    data: {},", field_literal(&envelope.error.data)).unwrap();
    output.push_str("  },\n} as const satisfies EnvelopeDescriptor;\n\n");
    let variable = format!("{}Envelope", lower_camel(&envelope.id));
    writeln!(
        output,
        "export const {variable} = createEnvelopeCodec({prefix}_DESCRIPTOR);"
    )
    .unwrap();
    Ok(finish(output))
}

fn render_envelope_tests(envelope: &EnvelopeSpec) -> Result<String, TypeScriptEmitError> {
    let mut output = String::from(BANNER);
    let module = envelope_module(&envelope.id);
    let variable = format!("{}Envelope", lower_camel(&envelope.id));
    output.push_str(
        "import assert from \"node:assert/strict\";\nimport test from \"node:test\";\n\n",
    );
    writeln!(
        output,
        "import {{ {variable} }} from \"../src/generated/zz_generated_{module}_envelope.ts\";\n"
    )
    .unwrap();
    for fixture in &envelope.fixtures {
        let bytes =
            std::str::from_utf8(&fixture.bytes).map_err(|_| TypeScriptEmitError::Envelope {
                envelope: envelope.id.clone(),
                message: format!("fixture {:?} is not UTF-8", fixture.path),
            })?;
        let frame = frame_literal(&fixture.frame)?;
        writeln!(
            output,
            "test({:?}, () => {{\n  const frame = {frame} as const;\n  assert.equal({variable}.encode(frame), {bytes:?});\n  assert.deepEqual({variable}.decode({bytes:?}), frame);\n}});\n",
            fixture.path
        )
        .unwrap();
    }
    let precedence = precedence_bytes(envelope)?;
    let expected =
        envelope
            .decode(precedence.as_bytes())
            .map_err(|error| TypeScriptEmitError::Envelope {
                envelope: envelope.id.clone(),
                message: error.to_string(),
            })?;
    writeln!(
        output,
        "test(\"structural discriminator precedence is generated\", () => {{\n  assert.deepEqual({variable}.decode({precedence:?}), {});\n}});\n",
        frame_literal(&expected)?
    )
    .unwrap();
    let constants_only = constants_object(envelope);
    let constants_bytes = serde_json::to_string(&Value::Object(constants_only.clone()))?;
    writeln!(
        output,
        "test(\"response result and error are independently optional\", () => {{\n  const response = {{ ...{}, {:?}: \"correlation-1\" }};\n  assert.deepEqual({variable}.decode(JSON.stringify(response)), {{ kind: \"response\", correlationId: \"correlation-1\" }});\n}});\n",
        constants_bytes,
        frame_for(envelope, FrameKind::Response)?.discriminator.name
    )
    .unwrap();
    let response = frame_for(envelope, FrameKind::Response)?;
    let error_field = response
        .error
        .as_ref()
        .ok_or_else(|| TypeScriptEmitError::Envelope {
            envelope: envelope.id.clone(),
            message: "response error mapping is missing".to_owned(),
        })?;
    writeln!(
        output,
        "test(\"a null wire error normalizes to no semantic error\", () => {{\n  const response = {{ ...{}, {:?}: \"correlation-1\", {:?}: null }};\n  assert.deepEqual({variable}.decode(JSON.stringify(response)), {{ kind: \"response\", correlationId: \"correlation-1\" }});\n}});\n",
        constants_bytes,
        response.discriminator.name,
        error_field.name
    )
    .unwrap();
    writeln!(
        output,
        "test(\"malformed envelopes fail without coercion\", () => {{\n  for (const bytes of [\"{{\", \"[]\", {constants_bytes:?}]) assert.throws(() => {variable}.decode(bytes));\n}});\n"
    )
    .unwrap();
    Ok(finish(output))
}

fn frame_literal(frame: &ControlFrame) -> Result<String, TypeScriptEmitError> {
    let value = match frame {
        ControlFrame::Request { id, method, params } => {
            let mut value = Map::new();
            value.insert("kind".to_owned(), json!("request"));
            value.insert("id".to_owned(), json!(id));
            value.insert("method".to_owned(), json!(method));
            if let Some(params) = params {
                value.insert("params".to_owned(), params.clone());
            }
            Value::Object(value)
        }
        ControlFrame::Response {
            correlation_id,
            result,
            error,
        } => {
            let mut value = Map::new();
            value.insert("kind".to_owned(), json!("response"));
            value.insert("correlationId".to_owned(), json!(correlation_id));
            if let Some(result) = result {
                value.insert("result".to_owned(), result.clone());
            }
            if let Some(error) = error {
                let mut encoded = Map::new();
                encoded.insert("code".to_owned(), json!(error.code));
                encoded.insert("message".to_owned(), json!(error.message));
                if let Some(data) = &error.data {
                    encoded.insert("data".to_owned(), data.clone());
                }
                value.insert("error".to_owned(), Value::Object(encoded));
            }
            Value::Object(value)
        }
        ControlFrame::Event { id, event, data } => {
            let mut value = Map::new();
            value.insert("kind".to_owned(), json!("event"));
            value.insert("id".to_owned(), json!(id));
            value.insert("event".to_owned(), json!(event));
            if let Some(data) = data {
                value.insert("data".to_owned(), data.clone());
            }
            Value::Object(value)
        }
    };
    Ok(serde_json::to_string(&value)?)
}

fn precedence_bytes(envelope: &EnvelopeSpec) -> Result<String, TypeScriptEmitError> {
    let mut object = constants_object(envelope);
    for (index, frame) in envelope.frames.iter().enumerate() {
        object.insert(
            frame.discriminator.name.clone(),
            Value::String(format!("discriminator-{index}")),
        );
        if let Some(id) = &frame.id {
            object.insert(id.name.clone(), Value::String(format!("id-{index}")));
        }
    }
    Ok(serde_json::to_string(&Value::Object(object))?)
}

fn constants_object(envelope: &EnvelopeSpec) -> Map<String, Value> {
    envelope
        .constants
        .iter()
        .map(|constant| (constant.name.clone(), Value::String(constant.value.clone())))
        .collect()
}

fn frame_for(
    envelope: &EnvelopeSpec,
    kind: FrameKind,
) -> Result<&rtvbp_spec_model::FrameSpec, TypeScriptEmitError> {
    envelope
        .frames
        .iter()
        .find(|frame| frame.kind == kind)
        .ok_or_else(|| TypeScriptEmitError::Envelope {
            envelope: envelope.id.clone(),
            message: format!("missing {kind:?} frame"),
        })
}

fn field_literal(field: &rtvbp_spec_model::FieldSpec) -> String {
    format!(
        "{{ name: {:?}, omitWhenNone: {} }}",
        field.name, field.omit_when_none
    )
}

fn frame_kind(kind: FrameKind) -> &'static str {
    match kind {
        FrameKind::Request => "request",
        FrameKind::Response => "response",
        FrameKind::Event => "event",
    }
}

fn validate_catalog(catalog: &ResolvedCatalog) -> Result<(), TypeScriptEmitError> {
    for (name, schema) in &catalog.schemas {
        if !valid_type_identifier(name) {
            return Err(schema_error(name, "invalid TypeScript type identifier"));
        }
        let object = schema
            .as_object()
            .ok_or_else(|| schema_error(name, "schema root must be an object"))?;
        if let Some(properties) = object.get("properties").and_then(Value::as_object) {
            let required = required_fields(object);
            for (field, schema) in properties {
                let field_schema = schema.as_object().ok_or_else(|| {
                    schema_error(name, &format!("field {field:?} is not an object schema"))
                })?;
                let marker = field_schema.get("x-rtvbp-presence").and_then(Value::as_str);
                if field_schema.contains_key("x-rtvbp-presence") && marker != Some("nullable") {
                    return Err(schema_error(
                        name,
                        &format!("field {field:?} has unknown presence"),
                    ));
                }
                if marker == Some("nullable") && !required.contains(field.as_str()) {
                    return Err(schema_error(
                        name,
                        &format!("field {field:?} is nullable but optional"),
                    ));
                }
            }
        }
        ts_type(name, schema, &catalog.schemas)?;
    }
    validate_role_names(catalog)
}

fn validate_role_names(catalog: &ResolvedCatalog) -> Result<(), TypeScriptEmitError> {
    for role in LocalRole::ALL {
        let mut names = HashMap::new();
        for operation in catalog
            .operations
            .iter()
            .filter(|operation| role.owns(operation.handled_by))
        {
            insert_member(
                &mut names,
                &format!("{}Handler", role.name()),
                &member_name(&operation.method),
                &operation.method,
            )?;
        }
        names.clear();
        for event in catalog
            .events
            .iter()
            .filter(|event| role.receives(event.emitted_by))
        {
            insert_member(
                &mut names,
                &format!("{}EventHandler", role.name()),
                &member_name(&event.name),
                &event.name,
            )?;
        }
    }
    Ok(())
}

fn insert_member(
    names: &mut HashMap<String, String>,
    surface: &str,
    method: &str,
    wire_name: &str,
) -> Result<(), TypeScriptEmitError> {
    if let Some(first) = names.insert(method.to_owned(), wire_name.to_owned()) {
        return Err(TypeScriptEmitError::RoleMethodCollision {
            surface: surface.to_owned(),
            method: method.to_owned(),
            first,
            second: wire_name.to_owned(),
        });
    }
    Ok(())
}

fn rejections(
    catalog: &ResolvedCatalog,
    role: LocalRole,
) -> impl Iterator<Item = (&ResolvedOperation, &rtvbp_spec_model::OperationRejection)> {
    catalog.operations.iter().flat_map(move |operation| {
        operation
            .rejections
            .iter()
            .filter(move |rejection| rejection.role == role.spec_role())
            .map(move |rejection| (operation, rejection))
    })
}

fn required_fields(object: &Map<String, Value>) -> HashSet<&str> {
    object
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect()
}

fn contains_null(schema: &Value) -> bool {
    let Some(object) = schema.as_object() else {
        return false;
    };
    match object.get("type") {
        Some(Value::String(value)) if value == "null" => return true,
        Some(Value::Array(values)) if values.iter().any(|value| value.as_str() == Some("null")) => {
            return true;
        }
        _ => {}
    }
    ["anyOf", "oneOf"].iter().any(|keyword| {
        object
            .get(*keyword)
            .and_then(Value::as_array)
            .is_some_and(|variants| variants.iter().any(contains_null))
    })
}

fn remove_null(schema: &Value) -> Option<Value> {
    let mut normalized = schema.clone();
    let object = normalized.as_object_mut()?;
    let single_type = if let Some(Value::Array(types)) = object.get_mut("type") {
        types.retain(|value| value.as_str() != Some("null"));
        (types.len() == 1).then(|| types[0].clone())
    } else {
        None
    };
    if let Some(single_type) = single_type {
        object.insert("type".to_owned(), single_type);
        return Some(normalized);
    }
    let object = schema.as_object()?;
    for keyword in ["anyOf", "oneOf"] {
        let variants = object.get(keyword)?.as_array()?;
        let remaining = variants
            .iter()
            .filter(|variant| !contains_null(variant))
            .cloned()
            .collect::<Vec<_>>();
        if remaining.len() == 1 {
            let mut normalized = remaining.into_iter().next()?;
            if let (Some(target), Some(source)) = (normalized.as_object_mut(), schema.as_object()) {
                for (name, value) in source {
                    if name != keyword && name != "x-rtvbp-presence" {
                        target.entry(name.clone()).or_insert_with(|| value.clone());
                    }
                }
            }
            return Some(normalized);
        }
    }
    None
}

fn parenthesize_union(value: String) -> String {
    if value.contains(" | ") {
        format!("({value})")
    } else {
        value
    }
}

fn operation_constant(value: &str) -> String {
    format!("METHOD_{}", screaming(value))
}

fn event_constant(value: &str) -> String {
    format!("EVENT_{}", screaming(value))
}

fn member_name(value: &str) -> String {
    lower_camel(value)
}

fn lower_camel(value: &str) -> String {
    let words = words(value);
    let mut output = String::new();
    for (index, word) in words.iter().enumerate() {
        if index == 0 {
            output.push_str(&word.to_ascii_lowercase());
        } else {
            let mut chars = word.chars();
            if let Some(first) = chars.next() {
                output.extend(first.to_uppercase());
            }
            output.push_str(&chars.as_str().to_ascii_lowercase());
        }
    }
    if output.is_empty() || output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert(0, '_');
    }
    output
}

fn screaming(value: &str) -> String {
    words(value)
        .into_iter()
        .map(|word| word.to_ascii_uppercase())
        .collect::<Vec<_>>()
        .join("_")
}

fn words(value: &str) -> Vec<&str> {
    value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .collect()
}

fn catalog_module(id: &CatalogId) -> String {
    format!("{}v{}", compact(&id.name), id.major)
}

fn catalog_prefix(id: &CatalogId) -> String {
    format!("{}_V{}", screaming(&id.name), id.major)
}

fn envelope_module(id: &str) -> String {
    compact(id)
}

fn envelope_prefix(id: &str) -> String {
    screaming(id)
}

fn compact(value: &str) -> String {
    words(value).join("").to_ascii_lowercase()
}

fn valid_type_identifier(name: &str) -> bool {
    let mut characters = name.chars();
    characters
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic() || first == '_')
        && characters.all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn schema_error(schema: &str, message: &str) -> TypeScriptEmitError {
    TypeScriptEmitError::Schema {
        schema: schema.to_owned(),
        message: message.to_owned(),
    }
}

fn one_line(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn indent(value: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    value
        .lines()
        .map(|line| format!("{prefix}{line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn finish(mut output: String) -> String {
    while output.ends_with('\n') {
        output.pop();
    }
    output.push('\n');
    output
}
