use std::path::PathBuf;

use rtvbp_spec_model::{ControlFrame, EnvelopeSpec, FrameKind, Scenario};
use serde::Serialize;
use serde_json::{Map, Number, Value, json};
use thiserror::Error;

use super::GeneratedFile;
use crate::resolve::{ResolvedCatalog, ResolvedOperation};

const GENERATED_NOTICE: &str =
    "Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.";

#[derive(Debug, Error)]
pub enum VectorEmitError {
    #[error("vector item name {name:?} cannot be used as a file name")]
    UnsafeFileName { name: String },
    #[error("operation {method:?} references missing schema {schema:?}")]
    MissingSchema { method: String, schema: String },
    #[error("envelope fixture {path:?} is not UTF-8")]
    FixtureUtf8 { path: String },
    #[error("could not encode generated conformance vector: {0}")]
    Json(#[from] serde_json::Error),
    #[error("could not build envelope precedence vector: {0}")]
    Envelope(#[from] rtvbp_spec_model::CodecError),
}

pub fn emit_vectors(
    catalog: &ResolvedCatalog,
    envelopes: &[EnvelopeSpec],
) -> Result<Vec<GeneratedFile>, VectorEmitError> {
    let catalog_id = catalog.id.to_string();
    safe_name(&catalog_id)?;
    let mut files = Vec::new();
    for operation in &catalog.operations {
        safe_name(&operation.method)?;
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("payloads")
                .join(format!("{}.json", operation.method)),
            bytes: pretty(&payload_vector(catalog, operation)?)?,
        });
    }
    for envelope in envelopes {
        safe_name(&envelope.id)?;
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("envelope")
                .join(&envelope.id)
                .join("frames.json"),
            bytes: pretty(&envelope_vector(envelope)?)?,
        });
    }
    for scenario in &catalog.scenarios {
        safe_name(&scenario.name)?;
        files.push(GeneratedFile {
            path: PathBuf::from(&catalog_id)
                .join("scenarios")
                .join(format!("{}.json", scenario.name)),
            bytes: pretty(&scenario_vector(scenario))?,
        });
    }
    Ok(files)
}

fn payload_vector(
    catalog: &ResolvedCatalog,
    operation: &ResolvedOperation,
) -> Result<Value, VectorEmitError> {
    let request_schema =
        catalog
            .schemas
            .get(&operation.request)
            .ok_or_else(|| VectorEmitError::MissingSchema {
                method: operation.method.clone(),
                schema: operation.request.clone(),
            })?;
    let response_schema =
        catalog
            .schemas
            .get(&operation.response)
            .ok_or_else(|| VectorEmitError::MissingSchema {
                method: operation.method.clone(),
                schema: operation.response.clone(),
            })?;
    let request_valid = operation
        .examples
        .iter()
        .map(|example| valid_case(&example.name, &example.request))
        .collect::<Result<Vec<_>, _>>()?;
    let response_valid = operation
        .examples
        .iter()
        .map(|example| valid_case(&example.name, &example.response))
        .collect::<Result<Vec<_>, _>>()?;
    let request_invalid = invalid_cases(request_schema, &operation.examples[0].request);
    let response_invalid = invalid_cases(response_schema, &operation.examples[0].response);
    Ok(json!({
        "_generated": GENERATED_NOTICE,
        "method": operation.method,
        "request": {
            "schema": operation.request,
            "valid": request_valid,
            "invalid": request_invalid,
        },
        "response": {
            "schema": operation.response,
            "valid": response_valid,
            "invalid": response_invalid,
        }
    }))
}

fn valid_case(name: &str, value: &Value) -> Result<Value, serde_json::Error> {
    Ok(json!({"name": name, "json": serde_json::to_string(value)?}))
}

fn invalid_cases(schema: &Value, canonical: &Value) -> Vec<Value> {
    let mut cases = vec![json!({
        "name": "malformed_json",
        "json": "{",
        "error": "decode"
    })];
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        return cases;
    };
    for (field, rule) in properties {
        if rule.get("minLength").is_some() {
            push_invalid(
                &mut cases,
                canonical,
                field,
                Value::String(String::new()),
                "min_length",
            );
        }
        if let Some(minimum) = rule.get("minimum").and_then(Value::as_i64)
            && let Some(below_minimum) = minimum.checked_sub(1)
        {
            push_invalid(
                &mut cases,
                canonical,
                field,
                Value::Number(Number::from(below_minimum)),
                "minimum",
            );
        }
        if rule.get("x-rtvbp-nonzero") == Some(&Value::Bool(true)) {
            push_invalid(
                &mut cases,
                canonical,
                field,
                Value::Number(Number::from(0)),
                "nonzero",
            );
        }
    }
    if let Some(orders) = schema.get("x-rtvbp-field-order").and_then(Value::as_array) {
        for order in orders {
            let (Some(lower), Some(upper)) = (
                order.get("lower").and_then(Value::as_str),
                order.get("upper").and_then(Value::as_str),
            ) else {
                continue;
            };
            let mut invalid = canonical.clone();
            if let Some(object) = invalid.as_object_mut() {
                object.insert(lower.to_owned(), json!(2));
                object.insert(upper.to_owned(), json!(1));
                cases.push(json!({
                    "name": format!("field_order_{lower}_{upper}"),
                    "json": serde_json::to_string(&invalid).unwrap(),
                    "error": "validation"
                }));
            }
        }
    }
    cases
}

fn push_invalid(cases: &mut Vec<Value>, canonical: &Value, field: &str, value: Value, rule: &str) {
    let mut invalid = canonical.clone();
    if let Some(object) = invalid.as_object_mut() {
        object.insert(field.to_owned(), value);
        cases.push(json!({
            "name": format!("{field}_{rule}"),
            "json": serde_json::to_string(&invalid).unwrap(),
            "error": "validation"
        }));
    }
}

#[derive(Serialize)]
struct EnvelopeVector {
    #[serde(rename = "_generated")]
    generated: &'static str,
    envelope: String,
    encode: Vec<FrameCase>,
    decode: Vec<FrameCase>,
    invalid: Vec<InvalidFrameCase>,
}

#[derive(Clone, Serialize)]
struct FrameCase {
    name: String,
    frame: Value,
    bytes: String,
}

#[derive(Serialize)]
struct InvalidFrameCase {
    name: String,
    bytes: String,
    error: &'static str,
}

fn envelope_vector(envelope: &EnvelopeSpec) -> Result<EnvelopeVector, VectorEmitError> {
    let cases = envelope
        .fixtures
        .iter()
        .map(|fixture| {
            Ok(FrameCase {
                name: PathBuf::from(&fixture.path)
                    .file_name()
                    .and_then(|name| name.to_str())
                    .unwrap_or(&fixture.path)
                    .trim_end_matches(".json")
                    .to_owned(),
                frame: frame_value(&fixture.frame),
                bytes: String::from_utf8(fixture.bytes.clone()).map_err(|_| {
                    VectorEmitError::FixtureUtf8 {
                        path: fixture.path.clone(),
                    }
                })?,
            })
        })
        .collect::<Result<Vec<_>, VectorEmitError>>()?;
    let precedence_bytes = precedence_bytes(envelope);
    let precedence_frame = envelope.decode(precedence_bytes.as_bytes())?;
    let mut decode = cases.clone();
    decode.push(FrameCase {
        name: "structural_precedence".to_owned(),
        frame: frame_value(&precedence_frame),
        bytes: precedence_bytes,
    });
    let constants_only = Value::Object(
        envelope
            .constants
            .iter()
            .map(|constant| (constant.name.clone(), Value::String(constant.value.clone())))
            .collect(),
    );
    let mut wrong_constant = constants_only.clone();
    if let Some(constant) = envelope.constants.first()
        && let Some(object) = wrong_constant.as_object_mut()
    {
        object.insert(constant.name.clone(), Value::String("invalid".to_owned()));
    }
    Ok(EnvelopeVector {
        generated: GENERATED_NOTICE,
        envelope: envelope.id.clone(),
        encode: cases,
        decode,
        invalid: vec![
            InvalidFrameCase {
                name: "malformed_json".to_owned(),
                bytes: "{".to_owned(),
                error: "decode",
            },
            InvalidFrameCase {
                name: "missing_discriminator".to_owned(),
                bytes: serde_json::to_string(&constants_only)?,
                error: "decode",
            },
            InvalidFrameCase {
                name: "wrong_constant".to_owned(),
                bytes: serde_json::to_string(&wrong_constant)?,
                error: "decode",
            },
        ],
    })
}

fn precedence_bytes(envelope: &EnvelopeSpec) -> String {
    let mut object = Map::new();
    for constant in &envelope.constants {
        object.insert(constant.name.clone(), Value::String(constant.value.clone()));
    }
    for frame in &envelope.frames {
        let discriminator = match frame.kind {
            FrameKind::Request => "precedence.request",
            FrameKind::Response => "precedence-response",
            FrameKind::Event => "precedence.event",
        };
        object.insert(
            frame.discriminator.name.clone(),
            Value::String(discriminator.to_owned()),
        );
        if let Some(id) = &frame.id {
            object.insert(id.name.clone(), Value::String("precedence-id".to_owned()));
        }
        object.insert(frame.payload.name.clone(), json!({}));
    }
    serde_json::to_string(&object).unwrap()
}

fn frame_value(frame: &ControlFrame) -> Value {
    let mut value = Map::new();
    match frame {
        ControlFrame::Request { id, method, params } => {
            value.insert("kind".to_owned(), json!("request"));
            value.insert("id".to_owned(), json!(id));
            value.insert("method".to_owned(), json!(method));
            if let Some(params) = params {
                value.insert("params".to_owned(), params.clone());
            }
        }
        ControlFrame::Response {
            correlation_id,
            result,
            error,
        } => {
            value.insert("kind".to_owned(), json!("response"));
            value.insert("response".to_owned(), json!(correlation_id));
            if let Some(result) = result {
                value.insert("result".to_owned(), result.clone());
            }
            if let Some(error) = error {
                value.insert("error".to_owned(), json!(error));
            }
        }
        ControlFrame::Event { id, event, data } => {
            value.insert("kind".to_owned(), json!("event"));
            value.insert("id".to_owned(), json!(id));
            value.insert("event".to_owned(), json!(event));
            if let Some(data) = data {
                value.insert("data".to_owned(), data.clone());
            }
        }
    }
    Value::Object(value)
}

fn scenario_vector(scenario: &Scenario) -> Value {
    json!({
        "_generated": GENERATED_NOTICE,
        "name": scenario.name,
        "roles": scenario.roles,
        "cases": scenario.cases,
    })
}

fn pretty(value: &impl Serialize) -> Result<Vec<u8>, serde_json::Error> {
    let mut bytes = serde_json::to_vec_pretty(value)?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn safe_name(name: &str) -> Result<(), VectorEmitError> {
    if !name.is_empty()
        && name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
    {
        Ok(())
    } else {
        Err(VectorEmitError::UnsafeFileName {
            name: name.to_owned(),
        })
    }
}
