// Code generated by rtvbp-spec-gen from the typed profile registry. DO NOT EDIT.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Media {
    pub channel: &'static str,
    pub carrier: &'static str,
    pub wire_format: &'static str,
    pub sdk_format: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Descriptor {
    pub id: &'static str,
    pub token: &'static str,
    pub transport: &'static str,
    pub envelope: &'static str,
    pub catalog: &'static str,
    pub signaling: &'static [&'static str],
    pub media: &'static [Media],
}

pub const PROFILE_RTVBP_V1: &str = "rtvbp.v1";
pub const PROFILE_RTVBP_DEMO_V1: &str = "rtvbp.demo.v1";
pub const PROFILE_RTVBP_WEBRTC_V1: &str = "rtvbp.webrtc.v1";
pub const SIGNALING_TRANSPORT_WEBRTC_OFFER: &str = "transport.webrtc.offer";
pub const DEFAULT: &str = PROFILE_RTVBP_V1;
pub const HEADERLESS: &str = PROFILE_RTVBP_V1;

pub static SERVER_PREFERENCE: &[&str] = &[
    PROFILE_RTVBP_V1,
    PROFILE_RTVBP_DEMO_V1,
    PROFILE_RTVBP_WEBRTC_V1,
];

pub static PROFILES: &[Descriptor] = &[
    Descriptor {
        id: "rtvbp.v1",
        token: PROFILE_RTVBP_V1,
        transport: "ws.v1",
        envelope: "classic.v1",
        catalog: "babelforce.v1",
        signaling: &[],
        media: &[Media {
            channel: "audio",
            carrier: "websocket-binary",
            wire_format: "l16-8000-16-1-20ms",
            sdk_format: "l16-8000-16-1-20ms",
        }],
    },
    Descriptor {
        id: "rtvbp.demo.v1",
        token: PROFILE_RTVBP_DEMO_V1,
        transport: "ws.v1",
        envelope: "classic.v1",
        catalog: "demo.v1",
        signaling: &[],
        media: &[],
    },
    Descriptor {
        id: "rtvbp.webrtc.v1",
        token: PROFILE_RTVBP_WEBRTC_V1,
        transport: "webrtcws.v1",
        envelope: "classic.v1",
        catalog: "babelforce.v1",
        signaling: &["transport.webrtc.offer"],
        media: &[Media {
            channel: "audio",
            carrier: "webrtc-rtp",
            wire_format: "pcmu-8000-8-1-20ms",
            sdk_format: "l16-8000-16-1-20ms",
        }],
    },
];
