use std::collections::BTreeMap;
use std::path::PathBuf;
use std::str::FromStr;

use rtvbp_spec_model::{CatalogId, EventExample, OperationExample, OperationRejection, Role};
use serde::Serialize;
use serde_json::Value;
use thiserror::Error;

use crate::resolve::{ResolvedCatalog, ResolvedEvent, ResolvedOperation};

mod go;
pub use go::{GoEmitError, emit_go, emit_go_envelope};
mod vectors;
pub use vectors::{VectorEmitError, emit_vectors};
mod docs;
pub use docs::{DocsEmitError, emit_docs};

const GENERATED_NOTICE: &str =
    "Code generated by rtvbp-spec-gen from the typed catalog. DO NOT EDIT.";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Target {
    Manifest,
    Go,
    Docs,
    Vectors,
}

impl FromStr for Target {
    type Err = UnknownTarget;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "manifest" => Ok(Self::Manifest),
            "go" => Ok(Self::Go),
            "docs" => Ok(Self::Docs),
            "vectors" => Ok(Self::Vectors),
            _ => Err(UnknownTarget(value.to_owned())),
        }
    }
}

impl Target {
    pub const ALL: [Self; 4] = [Self::Manifest, Self::Go, Self::Docs, Self::Vectors];

    #[must_use]
    pub const fn canonical_out_dir(self) -> &'static str {
        match self {
            Self::Manifest => "spec/manifests",
            Self::Go => "sdk/go",
            Self::Docs => "website/docs/reference",
            Self::Vectors => "conformance",
        }
    }

    /// Whether a relative path belongs exclusively to this target.
    #[must_use]
    pub fn owns_output_path(self, path: &std::path::Path) -> bool {
        match self {
            Self::Manifest => path
                .file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| name.ends_with(".catalog.json")),
            Self::Go => {
                let tree = path.iter().next().and_then(|part| part.to_str());
                matches!(tree, Some("catalog" | "envelope"))
                    && path
                        .file_name()
                        .and_then(|name| name.to_str())
                        .is_some_and(|name| {
                            name.starts_with("zz_generated.") && name.ends_with(".go")
                        })
            }
            Self::Docs => {
                let mut components = path.components();
                let catalog = components.next();
                let file_name = path.file_name().and_then(|name| name.to_str());
                catalog.is_some()
                    && components.next().is_some()
                    && file_name
                        .is_some_and(|name| name == "_category_.json" || name.ends_with(".mdx"))
            }
            Self::Vectors => {
                let parts = path
                    .iter()
                    .filter_map(|part| part.to_str())
                    .collect::<Vec<_>>();
                matches!(
                    parts.as_slice(),
                    [_, "payloads", file] | [_, "scenarios", file]
                        if file.ends_with(".json")
                ) || matches!(parts.as_slice(), [_, "envelope", _, "frames.json"])
            }
        }
    }
}

#[derive(Debug, Error)]
#[error("unknown emit target {0:?}; expected manifest, go, docs, or vectors")]
pub struct UnknownTarget(String);

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: PathBuf,
    pub bytes: Vec<u8>,
}

#[derive(Debug, Error)]
pub enum EmitError {
    #[error("could not serialize catalog manifest: {0}")]
    Json(#[from] serde_json::Error),
}

/// Emit a deterministic catalog manifest without touching the filesystem.
pub fn emit_manifest(catalog: &ResolvedCatalog) -> Result<Vec<GeneratedFile>, EmitError> {
    let manifest = Manifest::from(catalog);
    let mut bytes = serde_json::to_vec_pretty(&manifest)?;
    bytes.push(b'\n');
    Ok(vec![GeneratedFile {
        path: PathBuf::from(format!("{}.catalog.json", catalog.id)),
        bytes,
    }])
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct Manifest<'a> {
    #[serde(rename = "_generated")]
    generated: &'static str,
    format_version: u32,
    catalog: ManifestCatalog<'a>,
    operations: Vec<ManifestOperation<'a>>,
    events: Vec<ManifestEvent<'a>>,
    schemas: &'a BTreeMap<String, Value>,
}

impl<'a> From<&'a ResolvedCatalog> for Manifest<'a> {
    fn from(catalog: &'a ResolvedCatalog) -> Self {
        Self {
            generated: GENERATED_NOTICE,
            format_version: 1,
            catalog: ManifestCatalog {
                id: catalog.id.to_string(),
                catalog_id: &catalog.id,
            },
            operations: catalog
                .operations
                .iter()
                .map(ManifestOperation::from)
                .collect(),
            events: catalog.events.iter().map(ManifestEvent::from).collect(),
            schemas: &catalog.schemas,
        }
    }
}

#[derive(Serialize)]
struct ManifestCatalog<'a> {
    id: String,
    #[serde(flatten)]
    catalog_id: &'a CatalogId,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ManifestOperation<'a> {
    method: &'a str,
    handled_by: Role,
    terminal: bool,
    rejections: &'a [OperationRejection],
    description: &'a str,
    request: SchemaRef,
    response: SchemaRef,
    examples: &'a [OperationExample],
}

impl<'a> From<&'a ResolvedOperation> for ManifestOperation<'a> {
    fn from(operation: &'a ResolvedOperation) -> Self {
        Self {
            method: &operation.method,
            handled_by: operation.handled_by,
            terminal: operation.terminal,
            rejections: &operation.rejections,
            description: &operation.docs,
            request: SchemaRef::new(&operation.request),
            response: SchemaRef::new(&operation.response),
            examples: &operation.examples,
        }
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ManifestEvent<'a> {
    name: &'a str,
    emitted_by: Role,
    description: &'a str,
    data: SchemaRef,
    examples: &'a [EventExample],
}

impl<'a> From<&'a ResolvedEvent> for ManifestEvent<'a> {
    fn from(event: &'a ResolvedEvent) -> Self {
        Self {
            name: &event.name,
            emitted_by: event.emitted_by,
            description: &event.docs,
            data: SchemaRef::new(&event.data),
            examples: &event.examples,
        }
    }
}

#[derive(Serialize)]
struct SchemaRef {
    #[serde(rename = "$ref")]
    reference: String,
}

impl SchemaRef {
    fn new(name: &str) -> Self {
        Self {
            reference: crate::resolve::schema_reference(name),
        }
    }
}
