use std::collections::HashSet;
use std::fs;
use std::path::{Component, Path, PathBuf};

use thiserror::Error;

use crate::GeneratedFile;

#[derive(Debug, Error)]
pub enum WriteError {
    #[error("generated output path must be relative and confined: {0}")]
    UnsafePath(PathBuf),
    #[error("generator emitted duplicate output path: {0}")]
    DuplicatePath(PathBuf),
    #[error("could not access generated output {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("generated output differs: {paths:?}")]
    Drift { paths: Vec<PathBuf> },
}

/// Write generated files. This is the pipeline's only mutating filesystem boundary.
pub fn write_files(out_dir: &Path, files: &[GeneratedFile]) -> Result<(), WriteError> {
    validate_paths(files)?;
    for file in files {
        let path = out_dir.join(&file.path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|source| WriteError::Io {
                path: parent.to_owned(),
                source,
            })?;
        }
        if output_differs(&path, &file.bytes)? {
            fs::write(&path, &file.bytes).map_err(|source| WriteError::Io {
                path: path.clone(),
                source,
            })?;
        }
    }
    Ok(())
}

/// Synchronize a target's owned files, including removal of stale generated outputs.
pub fn synchronize_files(
    out_dir: &Path,
    files: &[GeneratedFile],
    owns: impl Fn(&Path) -> bool,
) -> Result<(), WriteError> {
    validate_paths(files)?;
    let expected = files
        .iter()
        .map(|file| file.path.as_path())
        .collect::<HashSet<_>>();
    for relative in owned_files(out_dir, &owns)? {
        if !expected.contains(relative.as_path()) {
            let path = out_dir.join(relative);
            fs::remove_file(&path).map_err(|source| WriteError::Io { path, source })?;
        }
    }
    write_files(out_dir, files)
}

/// Compare generated bytes with disk without mutating any file.
pub fn check_files(out_dir: &Path, files: &[GeneratedFile]) -> Result<(), WriteError> {
    validate_paths(files)?;
    let mut paths = Vec::new();
    for file in files {
        let path = out_dir.join(&file.path);
        if output_differs(&path, &file.bytes)? {
            paths.push(path);
        }
    }
    if paths.is_empty() {
        Ok(())
    } else {
        Err(WriteError::Drift { paths })
    }
}

/// Compare expected bytes and the complete set of paths owned by one emitter target.
pub fn check_owned_files(
    out_dir: &Path,
    files: &[GeneratedFile],
    owns: impl Fn(&Path) -> bool,
) -> Result<(), WriteError> {
    validate_paths(files)?;
    let expected = files
        .iter()
        .map(|file| file.path.as_path())
        .collect::<HashSet<_>>();
    let mut paths = owned_files(out_dir, &owns)?
        .into_iter()
        .filter(|path| !expected.contains(path.as_path()))
        .map(|path| out_dir.join(path))
        .collect::<Vec<_>>();
    for file in files {
        let path = out_dir.join(&file.path);
        if output_differs(&path, &file.bytes)? {
            paths.push(path);
        }
    }
    paths.sort();
    paths.dedup();
    if paths.is_empty() {
        Ok(())
    } else {
        Err(WriteError::Drift { paths })
    }
}

fn owned_files(out_dir: &Path, owns: &impl Fn(&Path) -> bool) -> Result<Vec<PathBuf>, WriteError> {
    let mut files = Vec::new();
    if !out_dir.exists() {
        return Ok(files);
    }
    collect_owned_files(out_dir, Path::new(""), owns, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_owned_files(
    out_dir: &Path,
    relative_dir: &Path,
    owns: &impl Fn(&Path) -> bool,
    files: &mut Vec<PathBuf>,
) -> Result<(), WriteError> {
    let directory = out_dir.join(relative_dir);
    let entries = fs::read_dir(&directory).map_err(|source| WriteError::Io {
        path: directory,
        source,
    })?;
    for entry in entries {
        let entry = entry.map_err(|source| WriteError::Io {
            path: out_dir.to_owned(),
            source,
        })?;
        let relative = relative_dir.join(entry.file_name());
        let file_type = entry.file_type().map_err(|source| WriteError::Io {
            path: entry.path(),
            source,
        })?;
        if file_type.is_dir() {
            collect_owned_files(out_dir, &relative, owns, files)?;
        } else if file_type.is_file() && owns(&relative) {
            files.push(relative);
        }
    }
    Ok(())
}

fn validate_paths(files: &[GeneratedFile]) -> Result<(), WriteError> {
    let mut paths = HashSet::new();
    for file in files {
        let safe = !file.path.as_os_str().is_empty()
            && file
                .path
                .components()
                .all(|component| matches!(component, Component::Normal(_)));
        if !safe {
            return Err(WriteError::UnsafePath(file.path.clone()));
        }
        if !paths.insert(&file.path) {
            return Err(WriteError::DuplicatePath(file.path.clone()));
        }
    }
    Ok(())
}

fn output_differs(path: &Path, expected: &[u8]) -> Result<bool, WriteError> {
    match fs::read(path) {
        Ok(actual) => Ok(actual != expected),
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(true),
        Err(source) => Err(WriteError::Io {
            path: path.to_owned(),
            source,
        }),
    }
}
