// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package babelforcev1

import (
	"context"
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/babelforce/rtvbp/sdk/go"
)

// Requester is the narrow request capability used by typed peer clients.
// Both *rtvbp.Session and rtvbp.SHC satisfy it.
type Requester interface {
	Request(context.Context, rtvbp.NamedRequest) (rtvbp.Response, error)
}

// Notifier is the narrow event capability used by role event emitters.
// rtvbp.SHC satisfies it.
type Notifier interface {
	Notify(context.Context, rtvbp.NamedEvent) error
}

// ApplicationHandler implements operations handled by the Application role.
type ApplicationHandler interface {
	Ping(context.Context, rtvbp.SHC, *PingRequest) (*PingResponse, error)
	SessionInitialize(context.Context, rtvbp.SHC, *SessionInitializeRequest) (*SessionInitializeResponse, error)
	SessionTerminate(context.Context, rtvbp.SHC, *SessionTerminateRequest) (*EmptyResponse, error)
}

// ApplicationHandlers adapts a ApplicationHandler for rtvbp.NewHandler.
func ApplicationHandlers(handler ApplicationHandler) []any {
	return []any{
		rtvbp.HandleRequest(handler.Ping),
		rtvbp.HandleRequest(handler.SessionInitialize),
		rtvbp.HandleTerminalRequest(handler.SessionTerminate),
	}
}

// VoiceHandler implements operations handled by the Voice role.
type VoiceHandler interface {
	ApplicationMove(context.Context, rtvbp.SHC, *ApplicationMoveRequest) (*ApplicationMoveResponse, error)
	AudioBufferClear(context.Context, rtvbp.SHC, *AudioBufferClearRequest) (*AudioBufferClearResponse, error)
	CallHangup(context.Context, rtvbp.SHC, *CallHangupRequest) (*EmptyResponse, error)
	Ping(context.Context, rtvbp.SHC, *PingRequest) (*PingResponse, error)
	RecordingStart(context.Context, rtvbp.SHC, *RecordingStartRequest) (*RecordingStartResponse, error)
	RecordingStop(context.Context, rtvbp.SHC, *RecordingStopRequest) (*EmptyResponse, error)
	SessionGet(context.Context, rtvbp.SHC, *SessionGetRequest) (*SessionGetResponse, error)
	SessionSet(context.Context, rtvbp.SHC, *SessionSetRequest) (*EmptyResponse, error)
}

// VoiceHandlers adapts a VoiceHandler for rtvbp.NewHandler.
func VoiceHandlers(handler VoiceHandler) []any {
	return []any{
		rtvbp.HandleTerminalRequest(handler.ApplicationMove),
		rtvbp.HandleRequest(handler.AudioBufferClear),
		rtvbp.HandleTerminalRequest(handler.CallHangup),
		rtvbp.HandleRequest(handler.Ping),
		rtvbp.HandleRequest(handler.RecordingStart),
		rtvbp.HandleRequest(handler.RecordingStop),
		rtvbp.HandleRequest(handler.SessionGet),
		rtvbp.HandleRequest(handler.SessionSet),
		rtvbp.HandleWithError[*SessionTerminateRequest](rtvbp.WireError{Code: 501, Message: "session.terminate is not supported. please use application.move or call.hangup instead"}),
	}
}

// ApplicationPeer is a typed client for operations offered by the Application role.
type ApplicationPeer struct {
	requester Requester
}

// NewApplicationPeer creates a typed Application peer client.
func NewApplicationPeer(requester Requester) *ApplicationPeer {
	return &ApplicationPeer{requester: requester}
}

// Ping calls ping.
func (peer *ApplicationPeer) Ping(ctx context.Context, request *PingRequest) (*PingResponse, error) {
	return requestPeer[PingResponse](ctx, peer.requester, request)
}

// SessionInitialize calls session.initialize.
func (peer *ApplicationPeer) SessionInitialize(ctx context.Context, request *SessionInitializeRequest) (*SessionInitializeResponse, error) {
	return requestPeer[SessionInitializeResponse](ctx, peer.requester, request)
}

// SessionTerminate calls session.terminate.
func (peer *ApplicationPeer) SessionTerminate(ctx context.Context, request *SessionTerminateRequest) (*EmptyResponse, error) {
	return requestPeer[EmptyResponse](ctx, peer.requester, request)
}

// VoicePeer is a typed client for operations offered by the Voice role.
type VoicePeer struct {
	requester Requester
}

// NewVoicePeer creates a typed Voice peer client.
func NewVoicePeer(requester Requester) *VoicePeer {
	return &VoicePeer{requester: requester}
}

// ApplicationMove calls application.move.
func (peer *VoicePeer) ApplicationMove(ctx context.Context, request *ApplicationMoveRequest) (*ApplicationMoveResponse, error) {
	return requestPeer[ApplicationMoveResponse](ctx, peer.requester, request)
}

// AudioBufferClear calls audio.buffer.clear.
func (peer *VoicePeer) AudioBufferClear(ctx context.Context, request *AudioBufferClearRequest) (*AudioBufferClearResponse, error) {
	return requestPeer[AudioBufferClearResponse](ctx, peer.requester, request)
}

// CallHangup calls call.hangup.
func (peer *VoicePeer) CallHangup(ctx context.Context, request *CallHangupRequest) (*EmptyResponse, error) {
	return requestPeer[EmptyResponse](ctx, peer.requester, request)
}

// Ping calls ping.
func (peer *VoicePeer) Ping(ctx context.Context, request *PingRequest) (*PingResponse, error) {
	return requestPeer[PingResponse](ctx, peer.requester, request)
}

// RecordingStart calls recording.start.
func (peer *VoicePeer) RecordingStart(ctx context.Context, request *RecordingStartRequest) (*RecordingStartResponse, error) {
	return requestPeer[RecordingStartResponse](ctx, peer.requester, request)
}

// RecordingStop calls recording.stop.
func (peer *VoicePeer) RecordingStop(ctx context.Context, request *RecordingStopRequest) (*EmptyResponse, error) {
	return requestPeer[EmptyResponse](ctx, peer.requester, request)
}

// SessionGet calls session.get.
func (peer *VoicePeer) SessionGet(ctx context.Context, request *SessionGetRequest) (*SessionGetResponse, error) {
	return requestPeer[SessionGetResponse](ctx, peer.requester, request)
}

// SessionSet calls session.set.
func (peer *VoicePeer) SessionSet(ctx context.Context, request *SessionSetRequest) (*EmptyResponse, error) {
	return requestPeer[EmptyResponse](ctx, peer.requester, request)
}

func requestPeer[Result any](ctx context.Context, requester Requester, request rtvbp.NamedRequest) (*Result, error) {
	if request == nil || reflect.ValueOf(request).Kind() == reflect.Pointer && reflect.ValueOf(request).IsNil() {
		return nil, fmt.Errorf("%w: request is nil", rtvbp.ErrRequestValidationFailed)
	}
	if validation, ok := request.(rtvbp.Validation); ok {
		if err := validation.Validate(); err != nil {
			return nil, fmt.Errorf("%w: request for %s: %w", rtvbp.ErrRequestValidationFailed, request.MethodName(), err)
		}
	}
	response, err := requester.Request(ctx, request)
	if err != nil {
		return nil, err
	}
	payload := response.Payload
	if len(payload) == 0 {
		payload = json.RawMessage("{}")
	}
	result := new(Result)
	if err := json.Unmarshal(payload, result); err != nil {
		return nil, fmt.Errorf("decode response for %s: %w", request.MethodName(), err)
	}
	if validation, ok := any(result).(rtvbp.Validation); ok {
		if err := validation.Validate(); err != nil {
			return nil, fmt.Errorf("validate response for %s: %w", request.MethodName(), err)
		}
	}
	return result, nil
}

func notifyEvent(ctx context.Context, notifier Notifier, event rtvbp.NamedEvent) error {
	if event == nil || reflect.ValueOf(event).Kind() == reflect.Pointer && reflect.ValueOf(event).IsNil() {
		return fmt.Errorf("%w: event is nil", rtvbp.ErrRequestValidationFailed)
	}
	if validation, ok := event.(rtvbp.Validation); ok {
		if err := validation.Validate(); err != nil {
			return fmt.Errorf("%w: event %s: %w", rtvbp.ErrRequestValidationFailed, event.EventName(), err)
		}
	}
	return notifier.Notify(ctx, event)
}

// ApplicationEvents emits events owned by the Application role.
type ApplicationEvents struct {
	notifier Notifier
}

// NewApplicationEvents creates a typed Application event emitter.
func NewApplicationEvents(notifier Notifier) *ApplicationEvents {
	return &ApplicationEvents{notifier: notifier}
}

// AgentToolCall emits agent.tool.call.
func (events *ApplicationEvents) AgentToolCall(ctx context.Context, event *AgentToolCallEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// AudioSpeechStarted emits audio.speech.started.
func (events *ApplicationEvents) AudioSpeechStarted(ctx context.Context, event *AudioSpeechStartedEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// InputTranscript emits input.transcript.
func (events *ApplicationEvents) InputTranscript(ctx context.Context, event *InputTranscriptEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// OutputTranscriptDelta emits output.transcript.delta.
func (events *ApplicationEvents) OutputTranscriptDelta(ctx context.Context, event *OutputTranscriptDeltaEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// OutputTranscriptDone emits output.transcript.done.
func (events *ApplicationEvents) OutputTranscriptDone(ctx context.Context, event *OutputTranscriptDoneEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// VoiceEvents emits events owned by the Voice role.
type VoiceEvents struct {
	notifier Notifier
}

// NewVoiceEvents creates a typed Voice event emitter.
func NewVoiceEvents(notifier Notifier) *VoiceEvents {
	return &VoiceEvents{notifier: notifier}
}

// AudioInfo emits audio.info.
func (events *VoiceEvents) AudioInfo(ctx context.Context, event *AudioInfoEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// CallHangup emits call.hangup.
func (events *VoiceEvents) CallHangup(ctx context.Context, event *CallHangupEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// Dtmf emits dtmf.
func (events *VoiceEvents) Dtmf(ctx context.Context, event *DtmfEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// SessionUpdated emits session.updated.
func (events *VoiceEvents) SessionUpdated(ctx context.Context, event *SessionUpdatedEvent) error {
	return notifyEvent(ctx, events.notifier, event)
}

// ApplicationEventHandler receives events emitted by the peer role.
type ApplicationEventHandler interface {
	AudioInfo(context.Context, rtvbp.SHC, *AudioInfoEvent) error
	CallHangup(context.Context, rtvbp.SHC, *CallHangupEvent) error
	Dtmf(context.Context, rtvbp.SHC, *DtmfEvent) error
	SessionUpdated(context.Context, rtvbp.SHC, *SessionUpdatedEvent) error
}

// ApplicationEventHandlers adapts a ApplicationEventHandler for rtvbp.NewHandler.
func ApplicationEventHandlers(handler ApplicationEventHandler) []any {
	return []any{
		rtvbp.HandleEvent(handler.AudioInfo),
		rtvbp.HandleEvent(handler.CallHangup),
		rtvbp.HandleEvent(handler.Dtmf),
		rtvbp.HandleEvent(handler.SessionUpdated),
	}
}

// VoiceEventHandler receives events emitted by the peer role.
type VoiceEventHandler interface {
	AgentToolCall(context.Context, rtvbp.SHC, *AgentToolCallEvent) error
	AudioSpeechStarted(context.Context, rtvbp.SHC, *AudioSpeechStartedEvent) error
	InputTranscript(context.Context, rtvbp.SHC, *InputTranscriptEvent) error
	OutputTranscriptDelta(context.Context, rtvbp.SHC, *OutputTranscriptDeltaEvent) error
	OutputTranscriptDone(context.Context, rtvbp.SHC, *OutputTranscriptDoneEvent) error
}

// VoiceEventHandlers adapts a VoiceEventHandler for rtvbp.NewHandler.
func VoiceEventHandlers(handler VoiceEventHandler) []any {
	return []any{
		rtvbp.HandleEvent(handler.AgentToolCall),
		rtvbp.HandleEvent(handler.AudioSpeechStarted),
		rtvbp.HandleEvent(handler.InputTranscript),
		rtvbp.HandleEvent(handler.OutputTranscriptDelta),
		rtvbp.HandleEvent(handler.OutputTranscriptDone),
	}
}
