// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package babelforcev1

import "errors"

// AgentToolCallEvent is generated from the protocol catalog.
//
// Data emitted by `agent.tool.call` when the agent invokes a tool.
type AgentToolCallEvent struct {
	// Name: Tool name; arguments and results are deliberately excluded.
	Name string `json:"name"`
}

// AppInfo is generated from the protocol catalog.
//
// IVR application metadata supplied when a session starts.
type AppInfo struct {
	// ID: Application or graph-node identifier.
	ID string `json:"id"`
}

// ApplicationMoveRequest is generated from the protocol catalog.
//
// Parameters for terminal operation `application.move`.
type ApplicationMoveRequest struct {
	// Reason: Optional reason for leaving the current graph node.
	Reason string `json:"reason,omitempty"`
	// ApplicationID: Optional target graph-node identifier; absence means advance normally.
	ApplicationID string `json:"application_id,omitempty"`
}

// ApplicationMoveResponse is generated from the protocol catalog.
//
// Result of `application.move`.
type ApplicationMoveResponse struct {
	// NextApplicationID: Graph node selected after the move, when known.
	NextApplicationID string `json:"next_application_id,omitempty"`
}

// AudioBufferClearRequest is generated from the protocol catalog.
//
// Parameters for `audio.buffer.clear`.
type AudioBufferClearRequest struct{}

// AudioBufferClearResponse is generated from the protocol catalog.
//
// Result of `audio.buffer.clear`.
type AudioBufferClearResponse struct {
	// Len: Number of buffered bytes removed.
	Len int `json:"len"`
}

// AudioCodec is generated from the protocol catalog.
//
// A negotiated audio codec.
type AudioCodec struct {
	// ID: Codec identifier such as `L16/8000/1`.
	ID string `json:"id"`
	// Name: Codec name such as `L16`.
	Name string `json:"name"`
	// SampleRate: Sample rate in hertz.
	SampleRate int `json:"sample_rate"`
	// BitDepth: Number of bits per sample.
	BitDepth int `json:"bit_depth"`
	// Channels: Number of audio channels.
	Channels int `json:"channels"`
}

// AudioInfoEvent is generated from the protocol catalog.
//
// Data emitted by `audio.info` with read and write throughput counters.
type AudioInfoEvent struct {
	// Read: Audio read from the telephony stream.
	Read AudioInfoItem `json:"read"`
	// Write: Audio written to the telephony stream.
	Write AudioInfoItem `json:"write"`
}

// AudioInfoItem is generated from the protocol catalog.
//
// Throughput counters for one audio direction.
type AudioInfoItem struct {
	// Bytes: Bytes transferred during the last reporting interval.
	Bytes int64 `json:"bytes"`
	// BytesPerSecond: Transfer rate during the last reporting interval.
	BytesPerSecond float64 `json:"bytes_per_second"`
	// BytesTotal: Total bytes transferred since session start.
	BytesTotal int64 `json:"bytes_total"`
}

// AudioSpeechStartedEvent is generated from the protocol catalog.
//
// Data emitted by `audio.speech.started` for barge-in signaling.
type AudioSpeechStartedEvent struct {
	// Origin: Side where speech began: `sender` or `receiver`.
	Origin string `json:"origin"`
}

// CallHangupEvent is generated from the protocol catalog.
//
// Data emitted by `call.hangup` when the voice peer reports call termination.
type CallHangupEvent struct {
	// Reason: Optional hangup reason.
	Reason string `json:"reason,omitempty"`
}

// CallHangupRequest is generated from the protocol catalog.
//
// Parameters for terminal operation `call.hangup`.
type CallHangupRequest struct {
	// Reason: Reason the call should be hung up.
	Reason string `json:"reason"`
}

// Validate checks the semantic constraints declared for CallHangupRequest.
func (value *CallHangupRequest) Validate() error {
	if value == nil {
		return errors.New("CallHangupRequest is nil")
	}
	if len(value.Reason) < 1 {
		return errors.New("reason must contain at least 1 character(s)")
	}
	return nil
}

// CallInfo is generated from the protocol catalog.
//
// Telephony call metadata supplied when a session starts.
type CallInfo struct {
	// ID: Call identifier.
	ID string `json:"id"`
	// SessionID: Session identifier owned by the voice peer.
	SessionID string `json:"session_id"`
	// From: Caller address or number.
	From string `json:"from"`
	// To: Callee address or number.
	To string `json:"to"`
}

// DtmfEvent is generated from the protocol catalog.
//
// Data emitted by `dtmf` when the caller releases a key.
type DtmfEvent struct {
	// Seq: Monotonic event sequence number within the session.
	Seq int `json:"seq"`
	// PressedAt: Epoch timestamp in milliseconds when the key was pressed.
	PressedAt int64 `json:"pressed_at"`
	// ReleasedAt: Epoch timestamp in milliseconds when the key was released.
	ReleasedAt int64 `json:"released_at"`
	// Digit: DTMF digit that was pressed.
	Digit string `json:"digit"`
}

// Validate checks the semantic constraints declared for DtmfEvent.
func (value *DtmfEvent) Validate() error {
	if value == nil {
		return errors.New("DtmfEvent is nil")
	}
	if value.Seq < 0 {
		return errors.New("seq must be at least 0")
	}
	if value.PressedAt < 0 {
		return errors.New("pressed_at must be at least 0")
	}
	if value.ReleasedAt < 0 {
		return errors.New("released_at must be at least 0")
	}
	if len(value.Digit) < 1 {
		return errors.New("digit must contain at least 1 character(s)")
	}
	if value.PressedAt > value.ReleasedAt {
		return errors.New("released_at must be greater than or equal to pressed_at")
	}
	return nil
}

// EmptyResponse is generated from the protocol catalog.
//
// Empty object returned by operations without result fields.
type EmptyResponse struct{}

// InputTranscriptEvent is generated from the protocol catalog.
//
// Data emitted by `input.transcript` for one finalized caller utterance.
type InputTranscriptEvent struct {
	// Delta: Complete caller transcript; the legacy wire field is named `delta`.
	Delta string `json:"delta"`
}

// OutputTranscriptDeltaEvent is generated from the protocol catalog.
//
// Data emitted by `output.transcript.delta` for incremental agent speech text.
type OutputTranscriptDeltaEvent struct {
	// Delta: Incremental transcript text.
	Delta string `json:"delta"`
}

// OutputTranscriptDoneEvent is generated from the protocol catalog.
//
// Data emitted by `output.transcript.done` when an agent utterance finishes.
type OutputTranscriptDoneEvent struct {
	// Text: Optional complete text; absence means retain the accumulated deltas.
	Text *string `json:"text,omitempty"`
}

// PingRequest is generated from the protocol catalog.
//
// Parameters for ordinary catalog operation `ping`.
type PingRequest struct {
	// T0: Sender timestamp in epoch milliseconds.
	T0 int64 `json:"t0"`
	// RTT: Optional round-trip time measured by a previous ping.
	RTT int64 `json:"rtt,omitempty"`
	// Data: Optional arbitrary data echoed by the peer.
	Data any `json:"data,omitempty"`
}

// Validate checks the semantic constraints declared for PingRequest.
func (value *PingRequest) Validate() error {
	if value == nil {
		return errors.New("PingRequest is nil")
	}
	if value.T0 == 0 {
		return errors.New("t0 must be non-zero")
	}
	return nil
}

// PingResponse is generated from the protocol catalog.
//
// Result of ordinary catalog operation `ping`.
type PingResponse struct {
	// T0: Echo of the request sender timestamp.
	T0 int64 `json:"t0"`
	// T1: Transport receive timestamp in epoch milliseconds.
	T1 int64 `json:"t1"`
	// T2: Application handling timestamp in epoch milliseconds.
	T2 int64 `json:"t2"`
	// OWD: Estimated one-way delay in milliseconds.
	OWD int64 `json:"owd"`
	// Data: Optional arbitrary data echoed from the request.
	Data any `json:"data,omitempty"`
}

// Validate checks the semantic constraints declared for PingResponse.
func (value *PingResponse) Validate() error {
	if value == nil {
		return errors.New("PingResponse is nil")
	}
	if value.T0 == 0 {
		return errors.New("t0 must be non-zero")
	}
	if value.T1 == 0 {
		return errors.New("t1 must be non-zero")
	}
	if value.T2 == 0 {
		return errors.New("t2 must be non-zero")
	}
	return nil
}

// RecordingStartRequest is generated from the protocol catalog.
//
// Parameters for `recording.start`.
type RecordingStartRequest struct {
	// Tags: Optional recording tags.
	Tags []string `json:"tags,omitempty"`
}

// RecordingStartResponse is generated from the protocol catalog.
//
// Result of `recording.start`.
type RecordingStartResponse struct {
	// ID: New recording identifier.
	ID string `json:"id"`
}

// Validate checks the semantic constraints declared for RecordingStartResponse.
func (value *RecordingStartResponse) Validate() error {
	if value == nil {
		return errors.New("RecordingStartResponse is nil")
	}
	if len(value.ID) < 1 {
		return errors.New("id must contain at least 1 character(s)")
	}
	return nil
}

// RecordingStopRequest is generated from the protocol catalog.
//
// Parameters for `recording.stop`.
type RecordingStopRequest struct {
	// ID: Recording identifier to stop.
	ID string `json:"id"`
}

// Validate checks the semantic constraints declared for RecordingStopRequest.
func (value *RecordingStopRequest) Validate() error {
	if value == nil {
		return errors.New("RecordingStopRequest is nil")
	}
	if len(value.ID) < 1 {
		return errors.New("id must contain at least 1 character(s)")
	}
	return nil
}

// SessionGetRequest is generated from the protocol catalog.
//
// Parameters for `session.get`.
type SessionGetRequest struct {
	// Keys: Keys to fetch; an empty list requests all variables.
	Keys []string `json:"keys"`
}

// SessionGetResponse is generated from the protocol catalog.
//
// Bare open-map result returned by `session.get`.
type SessionGetResponse map[string]any

// SessionInitializeRequest is generated from the protocol catalog.
//
// Parameters for `session.initialize`.
type SessionInitializeRequest struct {
	// Application: Application that owns the call flow.
	Application AppInfo `json:"application"`
	// Call: Call being bridged into the session.
	Call CallInfo `json:"call"`
	// AudioCodecOfferings: Audio codecs offered by the voice peer.
	AudioCodecOfferings []AudioCodec `json:"audio_codec_offerings"`
	// Metadata: Free-form session metadata; the field is present and may be `null`.
	Metadata *map[string]any `json:"metadata"`
}

// SessionInitializeResponse is generated from the protocol catalog.
//
// Result of `session.initialize`.
type SessionInitializeResponse struct {
	// AudioCodec: Selected codec; the field is present and may be `null`.
	AudioCodec *AudioCodec `json:"audio_codec"`
}

// SessionSetRequest is generated from the protocol catalog.
//
// Parameters for `session.set`.
type SessionSetRequest struct {
	// Data: Session variables to set.
	Data map[string]any `json:"data"`
}

// SessionTerminateRequest is generated from the protocol catalog.
//
// Parameters for terminal operation `session.terminate`.
type SessionTerminateRequest struct {
	// Reason: Reason the session is ending.
	Reason string `json:"reason"`
}

// Validate checks the semantic constraints declared for SessionTerminateRequest.
func (value *SessionTerminateRequest) Validate() error {
	if value == nil {
		return errors.New("SessionTerminateRequest is nil")
	}
	if len(value.Reason) < 1 {
		return errors.New("reason must contain at least 1 character(s)")
	}
	return nil
}

// SessionUpdatedEvent is generated from the protocol catalog.
//
// Data emitted by `session.updated` when negotiated state changes.
type SessionUpdatedEvent struct {
	// AudioCodec: Current codec; the field is present and may be `null`.
	AudioCodec *AudioCodec `json:"audio_codec"`
}

const MethodApplicationMove = "application.move"
const MethodAudioBufferClear = "audio.buffer.clear"
const MethodCallHangup = "call.hangup"
const MethodPing = "ping"
const MethodRecordingStart = "recording.start"
const MethodRecordingStop = "recording.stop"
const MethodSessionGet = "session.get"
const MethodSessionInitialize = "session.initialize"
const MethodSessionSet = "session.set"
const MethodSessionTerminate = "session.terminate"
const EventAgentToolCall = "agent.tool.call"
const EventAudioInfo = "audio.info"
const EventAudioSpeechStarted = "audio.speech.started"
const EventCallHangup = "call.hangup"
const EventDtmf = "dtmf"
const EventInputTranscript = "input.transcript"
const EventOutputTranscriptDelta = "output.transcript.delta"
const EventOutputTranscriptDone = "output.transcript.done"
const EventSessionUpdated = "session.updated"

// MethodName returns MethodApplicationMove.
func (*ApplicationMoveRequest) MethodName() string { return MethodApplicationMove }

// MethodName returns MethodAudioBufferClear.
func (*AudioBufferClearRequest) MethodName() string { return MethodAudioBufferClear }

// MethodName returns MethodCallHangup.
func (*CallHangupRequest) MethodName() string { return MethodCallHangup }

// MethodName returns MethodPing.
func (*PingRequest) MethodName() string { return MethodPing }

// MethodName returns MethodRecordingStart.
func (*RecordingStartRequest) MethodName() string { return MethodRecordingStart }

// MethodName returns MethodRecordingStop.
func (*RecordingStopRequest) MethodName() string { return MethodRecordingStop }

// MethodName returns MethodSessionGet.
func (*SessionGetRequest) MethodName() string { return MethodSessionGet }

// MethodName returns MethodSessionInitialize.
func (*SessionInitializeRequest) MethodName() string { return MethodSessionInitialize }

// MethodName returns MethodSessionSet.
func (*SessionSetRequest) MethodName() string { return MethodSessionSet }

// MethodName returns MethodSessionTerminate.
func (*SessionTerminateRequest) MethodName() string { return MethodSessionTerminate }

// EventName returns EventAgentToolCall.
func (*AgentToolCallEvent) EventName() string { return EventAgentToolCall }

// EventName returns EventAudioInfo.
func (*AudioInfoEvent) EventName() string { return EventAudioInfo }

// EventName returns EventAudioSpeechStarted.
func (*AudioSpeechStartedEvent) EventName() string { return EventAudioSpeechStarted }

// EventName returns EventCallHangup.
func (*CallHangupEvent) EventName() string { return EventCallHangup }

// EventName returns EventDtmf.
func (*DtmfEvent) EventName() string { return EventDtmf }

// EventName returns EventInputTranscript.
func (*InputTranscriptEvent) EventName() string { return EventInputTranscript }

// EventName returns EventOutputTranscriptDelta.
func (*OutputTranscriptDeltaEvent) EventName() string { return EventOutputTranscriptDelta }

// EventName returns EventOutputTranscriptDone.
func (*OutputTranscriptDoneEvent) EventName() string { return EventOutputTranscriptDone }

// EventName returns EventSessionUpdated.
func (*SessionUpdatedEvent) EventName() string { return EventSessionUpdated }
