// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package babelforcev1

import (
	"bytes"
	"encoding/json"
	"testing"
)

type goldenCase struct {
	name string

	golden []byte

	newValue func() any

	constructed any
}

var goldenCases = []goldenCase{
	{name: "events/agent.tool.call.json", golden: []byte("{\"name\":\"lookup_order\"}"), newValue: func() any { return new(AgentToolCallEvent) }, constructed: ptr(AgentToolCallEvent{Name: "lookup_order"})},
	{name: "events/audio.info.json", golden: []byte("{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}"), newValue: func() any { return new(AudioInfoEvent) }, constructed: ptr(AudioInfoEvent{Read: AudioInfoItem{Bytes: 0, BytesPerSecond: 0, BytesTotal: 0}, Write: AudioInfoItem{Bytes: 0, BytesPerSecond: 0, BytesTotal: 0}})},
	{name: "events/audio.speech.started.json", golden: []byte("{\"origin\":\"sender\"}"), newValue: func() any { return new(AudioSpeechStartedEvent) }, constructed: ptr(AudioSpeechStartedEvent{Origin: "sender"})},
	{name: "events/call.hangup.json", golden: []byte("{\"reason\":\"caller\"}"), newValue: func() any { return new(CallHangupEvent) }, constructed: ptr(CallHangupEvent{Reason: "caller"})},
	{name: "events/dtmf.json", golden: []byte("{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}"), newValue: func() any { return new(DtmfEvent) }, constructed: ptr(DtmfEvent{Seq: 7, PressedAt: 1700000000000, ReleasedAt: 1700000000120, Digit: "5"})},
	{name: "events/input.transcript.json", golden: []byte("{\"delta\":\"hello there\"}"), newValue: func() any { return new(InputTranscriptEvent) }, constructed: ptr(InputTranscriptEvent{Delta: "hello there"})},
	{name: "events/output.transcript.delta.json", golden: []byte("{\"delta\":\"Hi \"}"), newValue: func() any { return new(OutputTranscriptDeltaEvent) }, constructed: ptr(OutputTranscriptDeltaEvent{Delta: "Hi "})},
	{name: "events/output.transcript.done.json", golden: []byte("{}"), newValue: func() any { return new(OutputTranscriptDoneEvent) }, constructed: ptr(OutputTranscriptDoneEvent{})},
	{name: "events/session.updated.json", golden: []byte("{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}"), newValue: func() any { return new(SessionUpdatedEvent) }, constructed: ptr(SessionUpdatedEvent{AudioCodec: ptr(AudioCodec{ID: "L16/8000/1", Name: "L16", SampleRate: 8000, BitDepth: 16, Channels: 1})})},
	{name: "payloads/application.move.request.json", golden: []byte("{\"reason\":\"handoff\",\"application_id\":\"app-2\"}"), newValue: func() any { return new(ApplicationMoveRequest) }, constructed: ptr(ApplicationMoveRequest{Reason: "handoff", ApplicationID: "app-2"})},
	{name: "payloads/application.move.response.json", golden: []byte("{\"next_application_id\":\"app-2\"}"), newValue: func() any { return new(ApplicationMoveResponse) }, constructed: ptr(ApplicationMoveResponse{NextApplicationID: "app-2"})},
	{name: "payloads/audio.buffer.clear.request.json", golden: []byte("{}"), newValue: func() any { return new(AudioBufferClearRequest) }, constructed: ptr(AudioBufferClearRequest{})},
	{name: "payloads/audio.buffer.clear.response.json", golden: []byte("{\"len\":320}"), newValue: func() any { return new(AudioBufferClearResponse) }, constructed: ptr(AudioBufferClearResponse{Len: 320})},
	{name: "payloads/call.hangup.request.json", golden: []byte("{\"reason\":\"caller\"}"), newValue: func() any { return new(CallHangupRequest) }, constructed: ptr(CallHangupRequest{Reason: "caller"})},
	{name: "payloads/call.hangup.response.json", golden: []byte("{}"), newValue: func() any { return new(EmptyResponse) }, constructed: ptr(EmptyResponse{})},
	{name: "payloads/ping.request.json", golden: []byte("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}"), newValue: func() any { return new(PingRequest) }, constructed: ptr(PingRequest{T0: 1700000000000, RTT: 42, Data: map[string]any{"probe": "canonical"}})},
	{name: "payloads/ping.response.json", golden: []byte("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}"), newValue: func() any { return new(PingResponse) }, constructed: ptr(PingResponse{T0: 1700000000000, T1: 1700000000010, T2: 1700000000012, OWD: 5, Data: map[string]any{"probe": "canonical"}})},
	{name: "payloads/recording.start.request.json", golden: []byte("{\"tags\":[\"support\",\"canonical\"]}"), newValue: func() any { return new(RecordingStartRequest) }, constructed: ptr(RecordingStartRequest{Tags: []string{"support", "canonical"}})},
	{name: "payloads/recording.start.response.json", golden: []byte("{\"id\":\"recording-1\"}"), newValue: func() any { return new(RecordingStartResponse) }, constructed: ptr(RecordingStartResponse{ID: "recording-1"})},
	{name: "payloads/recording.stop.request.json", golden: []byte("{\"id\":\"recording-1\"}"), newValue: func() any { return new(RecordingStopRequest) }, constructed: ptr(RecordingStopRequest{ID: "recording-1"})},
	{name: "payloads/recording.stop.response.json", golden: []byte("{}"), newValue: func() any { return new(EmptyResponse) }, constructed: ptr(EmptyResponse{})},
	{name: "payloads/session.get.request.json", golden: []byte("{\"keys\":[\"customer\",\"attempt\"]}"), newValue: func() any { return new(SessionGetRequest) }, constructed: ptr(SessionGetRequest{Keys: []string{"customer", "attempt"}})},
	{name: "payloads/session.get.response.json", golden: []byte("{\"attempt\":2,\"customer\":\"Ada\"}"), newValue: func() any { return new(SessionGetResponse) }, constructed: ptr(SessionGetResponse{"attempt": int64(2), "customer": "Ada"})},
	{name: "payloads/session.initialize.request.json", golden: []byte("{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}"), newValue: func() any { return new(SessionInitializeRequest) }, constructed: ptr(SessionInitializeRequest{Application: AppInfo{ID: "app-1"}, Call: CallInfo{ID: "call-1", SessionID: "session-1", From: "+12025550100", To: "+12025550101"}, AudioCodecOfferings: []AudioCodec{AudioCodec{ID: "L16/8000/1", Name: "L16", SampleRate: 8000, BitDepth: 16, Channels: 1}}, Metadata: nil})},
	{name: "payloads/session.initialize.response.json", golden: []byte("{\"audio_codec\":null}"), newValue: func() any { return new(SessionInitializeResponse) }, constructed: ptr(SessionInitializeResponse{AudioCodec: nil})},
	{name: "payloads/session.set.request.json", golden: []byte("{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}"), newValue: func() any { return new(SessionSetRequest) }, constructed: ptr(SessionSetRequest{Data: map[string]any{"attempt": int64(2), "customer": "Ada"}})},
	{name: "payloads/session.set.response.json", golden: []byte("{}"), newValue: func() any { return new(EmptyResponse) }, constructed: ptr(EmptyResponse{})},
	{name: "payloads/session.terminate.request.json", golden: []byte("{\"reason\":\"completed\"}"), newValue: func() any { return new(SessionTerminateRequest) }, constructed: ptr(SessionTerminateRequest{Reason: "completed"})},
	{name: "payloads/session.terminate.response.json", golden: []byte("{}"), newValue: func() any { return new(EmptyResponse) }, constructed: ptr(EmptyResponse{})},
	{name: "variants/events/audio.info-nonzero.json", golden: []byte("{\"read\":{\"bytes\":1280,\"bytes_per_second\":12800,\"bytes_total\":6400},\"write\":{\"bytes\":32,\"bytes_per_second\":106.66666666666667,\"bytes_total\":96}}"), newValue: func() any { return new(AudioInfoEvent) }, constructed: ptr(AudioInfoEvent{Read: AudioInfoItem{Bytes: 1280, BytesPerSecond: 12800, BytesTotal: 6400}, Write: AudioInfoItem{Bytes: 32, BytesPerSecond: 106.66666666666667, BytesTotal: 96}})},
	{name: "variants/events/call.hangup-no-reason.json", golden: []byte("{}"), newValue: func() any { return new(CallHangupEvent) }, constructed: ptr(CallHangupEvent{})},
	{name: "variants/events/output.transcript.done-text-empty.json", golden: []byte("{\"text\":\"\"}"), newValue: func() any { return new(OutputTranscriptDoneEvent) }, constructed: ptr(OutputTranscriptDoneEvent{Text: ptr("")})},
	{name: "variants/events/output.transcript.done-text.json", golden: []byte("{\"text\":\"Hi there\"}"), newValue: func() any { return new(OutputTranscriptDoneEvent) }, constructed: ptr(OutputTranscriptDoneEvent{Text: ptr("Hi there")})},
	{name: "variants/payloads/application.move.request-empty.json", golden: []byte("{}"), newValue: func() any { return new(ApplicationMoveRequest) }, constructed: ptr(ApplicationMoveRequest{})},
	{name: "variants/payloads/application.move.response-no-next.json", golden: []byte("{}"), newValue: func() any { return new(ApplicationMoveResponse) }, constructed: ptr(ApplicationMoveResponse{})},
	{name: "variants/payloads/ping.request-no-optionals.json", golden: []byte("{\"t0\":1700000000000}"), newValue: func() any { return new(PingRequest) }, constructed: ptr(PingRequest{T0: 1700000000000})},
	{name: "variants/payloads/ping.response-no-data.json", golden: []byte("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5}"), newValue: func() any { return new(PingResponse) }, constructed: ptr(PingResponse{T0: 1700000000000, T1: 1700000000010, T2: 1700000000012, OWD: 5})},
	{name: "variants/payloads/recording.start.request-no-tags.json", golden: []byte("{}"), newValue: func() any { return new(RecordingStartRequest) }, constructed: ptr(RecordingStartRequest{})},
}

func TestGoldenPayloads(t *testing.T) {
	for _, tc := range goldenCases {
		t.Run(tc.name+"/round_trip", func(t *testing.T) {
			value := tc.newValue()
			if err := json.Unmarshal(tc.golden, value); err != nil {
				t.Fatal(err)
			}
			actual, err := json.Marshal(value)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(actual, tc.golden) {
				t.Fatalf("round-trip mismatch\nwant: %s\n got: %s", tc.golden, actual)
			}
		})
		t.Run(tc.name+"/construct", func(t *testing.T) {
			actual, err := json.Marshal(tc.constructed)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(actual, tc.golden) {
				t.Fatalf("constructed mismatch\nwant: %s\n got: %s", tc.golden, actual)
			}
		})
	}
}

func ptr[T any](value T) *T { return &value }
