// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

package babelforcev1

import (
	"context"
	"encoding/json"
	"errors"
	"testing"

	"github.com/babelforce/rtvbp/sdk/go"
)

var roleTestRequests = map[string]json.RawMessage{
	MethodApplicationMove:   json.RawMessage("{\"reason\":\"handoff\",\"application_id\":\"app-2\"}"),
	MethodAudioBufferClear:  json.RawMessage("{}"),
	MethodCallHangup:        json.RawMessage("{\"reason\":\"caller\"}"),
	MethodPing:              json.RawMessage("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}"),
	MethodRecordingStart:    json.RawMessage("{\"tags\":[\"support\",\"canonical\"]}"),
	MethodRecordingStop:     json.RawMessage("{\"id\":\"recording-1\"}"),
	MethodSessionGet:        json.RawMessage("{\"keys\":[\"customer\",\"attempt\"]}"),
	MethodSessionInitialize: json.RawMessage("{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}"),
	MethodSessionSet:        json.RawMessage("{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}"),
	MethodSessionTerminate:  json.RawMessage("{\"reason\":\"completed\"}"),
}

var roleTestResponses = map[string]json.RawMessage{
	MethodApplicationMove:   json.RawMessage("{\"next_application_id\":\"app-2\"}"),
	MethodAudioBufferClear:  json.RawMessage("{\"len\":320}"),
	MethodCallHangup:        json.RawMessage("{}"),
	MethodPing:              json.RawMessage("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}"),
	MethodRecordingStart:    json.RawMessage("{\"id\":\"recording-1\"}"),
	MethodRecordingStop:     json.RawMessage("{}"),
	MethodSessionGet:        json.RawMessage("{\"attempt\":2,\"customer\":\"Ada\"}"),
	MethodSessionInitialize: json.RawMessage("{\"audio_codec\":null}"),
	MethodSessionSet:        json.RawMessage("{}"),
	MethodSessionTerminate:  json.RawMessage("{}"),
}

var roleTestEvents = map[string]json.RawMessage{
	EventAgentToolCall:         json.RawMessage("{\"name\":\"lookup_order\"}"),
	EventAudioInfo:             json.RawMessage("{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}"),
	EventAudioSpeechStarted:    json.RawMessage("{\"origin\":\"sender\"}"),
	EventCallHangup:            json.RawMessage("{\"reason\":\"caller\"}"),
	EventDtmf:                  json.RawMessage("{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}"),
	EventInputTranscript:       json.RawMessage("{\"delta\":\"hello there\"}"),
	EventOutputTranscriptDelta: json.RawMessage("{\"delta\":\"Hi \"}"),
	EventOutputTranscriptDone:  json.RawMessage("{}"),
	EventSessionUpdated:        json.RawMessage("{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}"),
}

var roleTestTerminal = map[string]bool{
	MethodApplicationMove:   true,
	MethodAudioBufferClear:  false,
	MethodCallHangup:        true,
	MethodPing:              false,
	MethodRecordingStart:    false,
	MethodRecordingStop:     false,
	MethodSessionGet:        false,
	MethodSessionInitialize: false,
	MethodSessionSet:        false,
	MethodSessionTerminate:  true,
}

var roleTestRejections = map[string]rtvbp.WireError{
	"voice/session.terminate": {Code: 501, Message: "session.terminate is not supported. please use application.move or call.hangup instead"},
}

func roleTestValue[T any](payload json.RawMessage) *T {
	value := new(T)
	if err := json.Unmarshal(payload, value); err != nil {
		panic(err)
	}
	return value
}

type applicationRoleTestHandler struct{}

func (*applicationRoleTestHandler) Ping(context.Context, rtvbp.SHC, *PingRequest) (*PingResponse, error) {
	return roleTestValue[PingResponse](roleTestResponses[MethodPing]), nil
}

func (*applicationRoleTestHandler) SessionInitialize(context.Context, rtvbp.SHC, *SessionInitializeRequest) (*SessionInitializeResponse, error) {
	return roleTestValue[SessionInitializeResponse](roleTestResponses[MethodSessionInitialize]), nil
}

func (*applicationRoleTestHandler) SessionTerminate(context.Context, rtvbp.SHC, *SessionTerminateRequest) (*EmptyResponse, error) {
	return roleTestValue[EmptyResponse](roleTestResponses[MethodSessionTerminate]), nil
}

type applicationRoleTestEventHandler struct{}

func (*applicationRoleTestEventHandler) AudioInfo(context.Context, rtvbp.SHC, *AudioInfoEvent) error {
	return nil
}

func (*applicationRoleTestEventHandler) CallHangup(context.Context, rtvbp.SHC, *CallHangupEvent) error {
	return nil
}

func (*applicationRoleTestEventHandler) Dtmf(context.Context, rtvbp.SHC, *DtmfEvent) error {
	return nil
}

func (*applicationRoleTestEventHandler) SessionUpdated(context.Context, rtvbp.SHC, *SessionUpdatedEvent) error {
	return nil
}

type voiceRoleTestHandler struct{}

func (*voiceRoleTestHandler) ApplicationMove(context.Context, rtvbp.SHC, *ApplicationMoveRequest) (*ApplicationMoveResponse, error) {
	return roleTestValue[ApplicationMoveResponse](roleTestResponses[MethodApplicationMove]), nil
}

func (*voiceRoleTestHandler) AudioBufferClear(context.Context, rtvbp.SHC, *AudioBufferClearRequest) (*AudioBufferClearResponse, error) {
	return roleTestValue[AudioBufferClearResponse](roleTestResponses[MethodAudioBufferClear]), nil
}

func (*voiceRoleTestHandler) CallHangup(context.Context, rtvbp.SHC, *CallHangupRequest) (*EmptyResponse, error) {
	return roleTestValue[EmptyResponse](roleTestResponses[MethodCallHangup]), nil
}

func (*voiceRoleTestHandler) Ping(context.Context, rtvbp.SHC, *PingRequest) (*PingResponse, error) {
	return roleTestValue[PingResponse](roleTestResponses[MethodPing]), nil
}

func (*voiceRoleTestHandler) RecordingStart(context.Context, rtvbp.SHC, *RecordingStartRequest) (*RecordingStartResponse, error) {
	return roleTestValue[RecordingStartResponse](roleTestResponses[MethodRecordingStart]), nil
}

func (*voiceRoleTestHandler) RecordingStop(context.Context, rtvbp.SHC, *RecordingStopRequest) (*EmptyResponse, error) {
	return roleTestValue[EmptyResponse](roleTestResponses[MethodRecordingStop]), nil
}

func (*voiceRoleTestHandler) SessionGet(context.Context, rtvbp.SHC, *SessionGetRequest) (*SessionGetResponse, error) {
	return roleTestValue[SessionGetResponse](roleTestResponses[MethodSessionGet]), nil
}

func (*voiceRoleTestHandler) SessionSet(context.Context, rtvbp.SHC, *SessionSetRequest) (*EmptyResponse, error) {
	return roleTestValue[EmptyResponse](roleTestResponses[MethodSessionSet]), nil
}

type voiceRoleTestEventHandler struct{}

func (*voiceRoleTestEventHandler) AgentToolCall(context.Context, rtvbp.SHC, *AgentToolCallEvent) error {
	return nil
}

func (*voiceRoleTestEventHandler) AudioSpeechStarted(context.Context, rtvbp.SHC, *AudioSpeechStartedEvent) error {
	return nil
}

func (*voiceRoleTestEventHandler) InputTranscript(context.Context, rtvbp.SHC, *InputTranscriptEvent) error {
	return nil
}

func (*voiceRoleTestEventHandler) OutputTranscriptDelta(context.Context, rtvbp.SHC, *OutputTranscriptDeltaEvent) error {
	return nil
}

func (*voiceRoleTestEventHandler) OutputTranscriptDone(context.Context, rtvbp.SHC, *OutputTranscriptDoneEvent) error {
	return nil
}

type roleTestRequest struct{}

func (*roleTestRequest) MethodName() string { return "role.test" }

type roleTestInvalidRequest struct{}

func (*roleTestInvalidRequest) MethodName() string { return "role.invalid" }
func (*roleTestInvalidRequest) Validate() error    { return errors.New("invalid request") }

type roleTestInvalidEvent struct{}

func (*roleTestInvalidEvent) EventName() string { return "role.invalid" }
func (*roleTestInvalidEvent) Validate() error   { return errors.New("invalid event") }

type roleTestRequester struct {
	empty bool
	calls int
}

func (requester *roleTestRequester) Request(_ context.Context, request rtvbp.NamedRequest) (rtvbp.Response, error) {
	requester.calls++
	if requester.empty {
		return rtvbp.Response{}, nil
	}
	return rtvbp.Response{Payload: roleTestResponses[request.MethodName()]}, nil
}

type roleTestNotifier struct {
	names []string
}

func (notifier *roleTestNotifier) Notify(_ context.Context, event rtvbp.NamedEvent) error {
	notifier.names = append(notifier.names, event.EventName())
	return nil
}

func TestGeneratedRoleAdapters(t *testing.T) {
	tests := []struct {
		name string
		requests []any
		events []any
	}{
		{name: "application", requests: ApplicationHandlers(&applicationRoleTestHandler{}), events: ApplicationEventHandlers(&applicationRoleTestEventHandler{})},
		{name: "voice", requests: VoiceHandlers(&voiceRoleTestHandler{}), events: VoiceEventHandlers(&voiceRoleTestEventHandler{})},
	}
	for _, tc := range tests {
		t.Run(tc.name+"/requests", func(t *testing.T) {
			for _, registration := range tc.requests {
				handler := registration.(rtvbp.RequestHandler)
				shc := rtvbp.NewTestingSHC()
				err := handler.Handle(context.Background(), shc, rtvbp.Request{Method: handler.MethodName(), Payload: roleTestRequests[handler.MethodName()]})
				if rejection, ok := roleTestRejections[tc.name+"/"+handler.MethodName()]; ok {
					var handlerError *rtvbp.HandlerError
					if !errors.As(err, &handlerError) || handlerError.WireError.Code != rejection.Code || handlerError.WireError.Message != rejection.Message {
						t.Fatalf("%s rejection = %#v, want %#v", handler.MethodName(), err, rejection)
					}
					if got := shc.State(); got != rtvbp.SessionStateActive {
						t.Fatalf("%s rejection state = %s, want active", handler.MethodName(), got)
					}
					continue
				}
				if err != nil {
					t.Fatalf("%s: %v", handler.MethodName(), err)
				}
				want := rtvbp.SessionStateActive
				if roleTestTerminal[handler.MethodName()] {
					want = rtvbp.SessionStateClosed
				}
				if got := shc.State(); got != want {
					t.Fatalf("%s state = %s, want %s", handler.MethodName(), got, want)
				}
			}
		})
		t.Run(tc.name+"/events", func(t *testing.T) {
			for _, registration := range tc.events {
				handler := registration.(rtvbp.EventHandler)
				err := handler.Handle(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Event{Name: handler.EventName(), Payload: roleTestEvents[handler.EventName()]})
				if err != nil {
					t.Fatalf("%s: %v", handler.EventName(), err)
				}
			}
		})
	}
}

func TestGeneratedTypedPeers(t *testing.T) {
	ctx := context.Background()
	application := NewApplicationPeer(&roleTestRequester{})
	if _, err := application.Ping(ctx, roleTestValue[PingRequest](roleTestRequests[MethodPing])); err != nil {
		t.Fatalf("Application.Ping: %v", err)
	}
	if _, err := application.SessionInitialize(ctx, roleTestValue[SessionInitializeRequest](roleTestRequests[MethodSessionInitialize])); err != nil {
		t.Fatalf("Application.SessionInitialize: %v", err)
	}
	if _, err := application.SessionTerminate(ctx, roleTestValue[SessionTerminateRequest](roleTestRequests[MethodSessionTerminate])); err != nil {
		t.Fatalf("Application.SessionTerminate: %v", err)
	}
	voice := NewVoicePeer(&roleTestRequester{})
	if _, err := voice.ApplicationMove(ctx, roleTestValue[ApplicationMoveRequest](roleTestRequests[MethodApplicationMove])); err != nil {
		t.Fatalf("Voice.ApplicationMove: %v", err)
	}
	if _, err := voice.AudioBufferClear(ctx, roleTestValue[AudioBufferClearRequest](roleTestRequests[MethodAudioBufferClear])); err != nil {
		t.Fatalf("Voice.AudioBufferClear: %v", err)
	}
	if _, err := voice.CallHangup(ctx, roleTestValue[CallHangupRequest](roleTestRequests[MethodCallHangup])); err != nil {
		t.Fatalf("Voice.CallHangup: %v", err)
	}
	if _, err := voice.Ping(ctx, roleTestValue[PingRequest](roleTestRequests[MethodPing])); err != nil {
		t.Fatalf("Voice.Ping: %v", err)
	}
	if _, err := voice.RecordingStart(ctx, roleTestValue[RecordingStartRequest](roleTestRequests[MethodRecordingStart])); err != nil {
		t.Fatalf("Voice.RecordingStart: %v", err)
	}
	if _, err := voice.RecordingStop(ctx, roleTestValue[RecordingStopRequest](roleTestRequests[MethodRecordingStop])); err != nil {
		t.Fatalf("Voice.RecordingStop: %v", err)
	}
	if _, err := voice.SessionGet(ctx, roleTestValue[SessionGetRequest](roleTestRequests[MethodSessionGet])); err != nil {
		t.Fatalf("Voice.SessionGet: %v", err)
	}
	if _, err := voice.SessionSet(ctx, roleTestValue[SessionSetRequest](roleTestRequests[MethodSessionSet])); err != nil {
		t.Fatalf("Voice.SessionSet: %v", err)
	}
	empty, err := requestPeer[map[string]any](ctx, &roleTestRequester{empty: true}, &roleTestRequest{})
	if err != nil || empty == nil || len(*empty) != 0 {
		t.Fatalf("empty response = %#v, %v", empty, err)
	}
	boundary := &roleTestRequester{}
	if _, err := requestPeer[map[string]any](ctx, boundary, &roleTestInvalidRequest{}); !errors.Is(err, rtvbp.ErrRequestValidationFailed) || boundary.calls != 0 {
		t.Fatalf("invalid request error = %v, calls = %d", err, boundary.calls)
	}
}

func TestGeneratedRoleEventEmitters(t *testing.T) {
	ctx := context.Background()
	applicationNotifier := &roleTestNotifier{}
	application := NewApplicationEvents(applicationNotifier)
	if err := application.AgentToolCall(ctx, roleTestValue[AgentToolCallEvent](roleTestEvents[EventAgentToolCall])); err != nil {
		t.Fatal(err)
	}
	if err := application.AudioSpeechStarted(ctx, roleTestValue[AudioSpeechStartedEvent](roleTestEvents[EventAudioSpeechStarted])); err != nil {
		t.Fatal(err)
	}
	if err := application.InputTranscript(ctx, roleTestValue[InputTranscriptEvent](roleTestEvents[EventInputTranscript])); err != nil {
		t.Fatal(err)
	}
	if err := application.OutputTranscriptDelta(ctx, roleTestValue[OutputTranscriptDeltaEvent](roleTestEvents[EventOutputTranscriptDelta])); err != nil {
		t.Fatal(err)
	}
	if err := application.OutputTranscriptDone(ctx, roleTestValue[OutputTranscriptDoneEvent](roleTestEvents[EventOutputTranscriptDone])); err != nil {
		t.Fatal(err)
	}
	voiceNotifier := &roleTestNotifier{}
	voice := NewVoiceEvents(voiceNotifier)
	if err := voice.AudioInfo(ctx, roleTestValue[AudioInfoEvent](roleTestEvents[EventAudioInfo])); err != nil {
		t.Fatal(err)
	}
	if err := voice.CallHangup(ctx, roleTestValue[CallHangupEvent](roleTestEvents[EventCallHangup])); err != nil {
		t.Fatal(err)
	}
	if err := voice.Dtmf(ctx, roleTestValue[DtmfEvent](roleTestEvents[EventDtmf])); err != nil {
		t.Fatal(err)
	}
	if err := voice.SessionUpdated(ctx, roleTestValue[SessionUpdatedEvent](roleTestEvents[EventSessionUpdated])); err != nil {
		t.Fatal(err)
	}
	if got := len(applicationNotifier.names) + len(voiceNotifier.names); got != 9 {
		t.Fatalf("emitted event count = %d, want 9", got)
	}
	boundary := &roleTestNotifier{}
	if err := notifyEvent(ctx, boundary, &roleTestInvalidEvent{}); !errors.Is(err, rtvbp.ErrRequestValidationFailed) || len(boundary.names) != 0 {
		t.Fatalf("invalid event error = %v, notifications = %v", err, boundary.names)
	}
}

func TestGeneratedAdaptersPreserveUnknownHooks(t *testing.T) {
	registrations := ApplicationHandlers(&applicationRoleTestHandler{})
	registrations = append(registrations, ApplicationEventHandlers(&applicationRoleTestEventHandler{})...)
	defaultHandler := rtvbp.NewHandler(rtvbp.HandlerConfig{}, registrations...)
	err := defaultHandler.OnRequest(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Request{Method: "unknown.method"})
	var handlerError *rtvbp.HandlerError
	if !errors.As(err, &handlerError) || handlerError.WireError.Code != 501 {
		t.Fatalf("unknown method error = %#v", err)
	}
	if err := defaultHandler.OnEvent(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Event{Name: "unknown.event"}); err != nil {
		t.Fatalf("unknown event: %v", err)
	}

	methodHooked, eventHooked := false, false
	hooked := rtvbp.NewHandler(rtvbp.HandlerConfig{
		OnUnknownMethod: func(context.Context, rtvbp.SHC, rtvbp.Request) error { methodHooked = true; return rtvbp.NotImplemented("hooked") },
		OnUnknownEvent: func(context.Context, rtvbp.SHC, rtvbp.Event) error { eventHooked = true; return nil },
	}, registrations...)
	_ = hooked.OnRequest(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Request{Method: "unknown.method"})
	_ = hooked.OnEvent(context.Background(), rtvbp.NewTestingSHC(), rtvbp.Event{Name: "unknown.event"})
	if !methodHooked || !eventHooked {
		t.Fatalf("hooks = method:%v event:%v", methodHooked, eventHooked)
	}
}
