// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

import assert from "node:assert/strict";
import test from "node:test";

import * as catalog from "../src/generated/zz_generated_demov1_types.ts";

import * as roles from "../src/generated/zz_generated_demov1_roles.ts";
import { ProtocolHandlerError } from "../src/protocol.ts";
import { encodeWireJson } from "../src/wire.ts";

const CONTEXT = { signal: new AbortController().signal };

test("demo.echo/request/malformed_json", () => {
  assert.throws(() => catalog.decodeDemoEchoRequest("{"));
});

test("demo.echo/request/message_min_length", () => {
  assert.throws(() => catalog.decodeDemoEchoRequest("{\"message\":\"\"}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("demo.echo/response/malformed_json", () => {
  assert.throws(() => catalog.decodeDemoEchoResponse("{"));
});

test("demo.echo/response/message_min_length", () => {
  assert.throws(() => catalog.decodeDemoEchoResponse("{\"message\":\"\"}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("generated application request adapter preserves payloads and terminal metadata", async () => {
  const handler: roles.ApplicationHandler = {
    demoEcho(_context, request) {
      assert.deepEqual(request, {"message":"hello from demo.v1"});
      return {"message":"hello from demo.v1"};
    },
  };
  const registrations = roles.applicationRequestHandlers(handler);
  assert.deepEqual(
    registrations.map((registration) => [registration.method, registration.terminal]),
    [
      [catalog.METHOD_DEMO_ECHO, false],
    ],
  );
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_DEMO_ECHO)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeDemoEchoRequest("{\"message\":\"hello from demo.v1\"}"));
    assert.equal(encodeWireJson(reply), "{\"message\":\"hello from demo.v1\"}");
  }
});

test("generated application peer calls demo.echo", async () => {
  const peer = new roles.ApplicationPeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_DEMO_ECHO);
      assert.equal(encodeWireJson(params), "{\"message\":\"hello from demo.v1\"}");
      assert.equal(options?.terminal, false);
      return catalog.decodeDemoEchoResponse("{\"message\":\"hello from demo.v1\"}");
    },
  });
  assert.deepEqual(await peer.demoEcho({"message":"hello from demo.v1"}), {"message":"hello from demo.v1"});
});

test("generated application event adapter validates every peer event", async () => {
  const handler: roles.ApplicationEventHandler = {
  };
  const registrations = roles.applicationEventHandlers(handler);
  const unknown = { request: async () => {}, event: async () => {} };
  assert.equal(roles.applicationAdapter(handler as unknown as roles.ApplicationHandler, handler, unknown).unknown, unknown);
});

test("generated application event emitter sends demo.observed", async () => {
  const events = new roles.ApplicationEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_DEMO_OBSERVED);
      assert.equal(encodeWireJson(payload), "{\"message\":\"hello from demo.v1\"}");
    },
  });
  await events.demoObserved({"message":"hello from demo.v1"});
});

test("generated voice request adapter preserves payloads and terminal metadata", async () => {
  const handler: roles.VoiceHandler = {
  };
  const registrations = roles.voiceRequestHandlers(handler);
  assert.deepEqual(
    registrations.map((registration) => [registration.method, registration.terminal]),
    [
    ],
  );
});

test("generated voice event adapter validates every peer event", async () => {
  const handler: roles.VoiceEventHandler = {
    demoObserved(_context, event) { assert.deepEqual(event, {"message":"hello from demo.v1"}); },
  };
  const registrations = roles.voiceEventHandlers(handler);
  await registrations.find((candidate) => candidate.event === catalog.EVENT_DEMO_OBSERVED)!.handle(CONTEXT, catalog.decodeDemoObservedEvent("{\"message\":\"hello from demo.v1\"}"));
  const unknown = { request: async () => {}, event: async () => {} };
  assert.equal(roles.voiceAdapter(handler as unknown as roles.VoiceHandler, handler, unknown).unknown, unknown);
});
