// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

import assert from "node:assert/strict";
import test from "node:test";

import { classicV1Envelope } from "../src/generated/zz_generated_classicv1_envelope.ts";

test("envelope/classic.v1/request.json", () => {
  const frame = {"kind":"request","id":"request-1","method":"session.get"} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"id\":\"request-1\",\"method\":\"session.get\"}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"id\":\"request-1\",\"method\":\"session.get\"}"), frame);
});

test("envelope/classic.v1/request-with-params.json", () => {
  const frame = {"kind":"request","id":"request-terminate-1","method":"session.terminate","params":{"reason":"completed"}} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"id\":\"request-terminate-1\",\"method\":\"session.terminate\",\"params\":{\"reason\":\"completed\"}}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"id\":\"request-terminate-1\",\"method\":\"session.terminate\",\"params\":{\"reason\":\"completed\"}}"), frame);
});

test("envelope/classic.v1/response-ok.json", () => {
  const frame = {"kind":"response","correlationId":"request-1","result":{}} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"response\":\"request-1\",\"result\":{}}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"response\":\"request-1\",\"result\":{}}"), frame);
});

test("envelope/classic.v1/response-ok-no-result.json", () => {
  const frame = {"kind":"response","correlationId":"request-1"} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"response\":\"request-1\"}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"response\":\"request-1\"}"), frame);
});

test("envelope/classic.v1/response-ok-null-result.json", () => {
  const frame = {"kind":"response","correlationId":"request-1","result":null} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"response\":\"request-1\",\"result\":null}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"response\":\"request-1\",\"result\":null}"), frame);
});

test("envelope/classic.v1/response-error.json", () => {
  const frame = {"kind":"response","correlationId":"request-1","error":{"code":400,"message":"invalid request","data":{"field":"reason","retryable":false}}} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":400,\"message\":\"invalid request\",\"any\":{\"field\":\"reason\",\"retryable\":false}}}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":400,\"message\":\"invalid request\",\"any\":{\"field\":\"reason\",\"retryable\":false}}}"), frame);
});

test("envelope/classic.v1/response-error-unknown.json", () => {
  const frame = {"kind":"response","correlationId":"request-1","error":{"code":-1,"message":"unknown failure"}} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":-1,\"message\":\"unknown failure\"}}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":-1,\"message\":\"unknown failure\"}}"), frame);
});

test("envelope/classic.v1/response-error-internal.json", () => {
  const frame = {"kind":"response","correlationId":"request-1","error":{"code":500,"message":"internal failure"}} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":500,\"message\":\"internal failure\"}}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"response\":\"request-1\",\"error\":{\"code\":500,\"message\":\"internal failure\"}}"), frame);
});

test("envelope/classic.v1/response-error-not-implemented.json", () => {
  const frame = {"kind":"response","correlationId":"request-terminate-1","error":{"code":501,"message":"session.terminate is not supported. please use application.move or call.hangup instead"}} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"response\":\"request-terminate-1\",\"error\":{\"code\":501,\"message\":\"session.terminate is not supported. please use application.move or call.hangup instead\"}}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"response\":\"request-terminate-1\",\"error\":{\"code\":501,\"message\":\"session.terminate is not supported. please use application.move or call.hangup instead\"}}"), frame);
});

test("envelope/classic.v1/event.json", () => {
  const frame = {"kind":"event","id":"event-1","event":"dtmf","data":{"seq":7,"pressed_at":1700000000000,"released_at":1700000000120,"digit":"5"}} as const;
  assert.equal(classicV1Envelope.encode(frame), "{\"version\":\"1\",\"id\":\"event-1\",\"event\":\"dtmf\",\"data\":{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}}");
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"id\":\"event-1\",\"event\":\"dtmf\",\"data\":{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}}"), frame);
});

test("structural discriminator precedence is generated", () => {
  assert.deepEqual(classicV1Envelope.decode("{\"version\":\"1\",\"event\":\"discriminator-0\",\"id\":\"id-1\",\"method\":\"discriminator-1\",\"response\":\"discriminator-2\"}"), {"kind":"event","id":"id-1","event":"discriminator-0"});
});

test("response result and error are independently optional", () => {
  const response = { ...{"version":"1"}, "response": "correlation-1" };
  assert.deepEqual(classicV1Envelope.decode(JSON.stringify(response)), { kind: "response", correlationId: "correlation-1" });
});

test("a null wire error normalizes to no semantic error", () => {
  const response = { ...{"version":"1"}, "response": "correlation-1", "error": null };
  assert.deepEqual(classicV1Envelope.decode(JSON.stringify(response)), { kind: "response", correlationId: "correlation-1" });
});

test("malformed envelopes fail without coercion", () => {
  for (const bytes of ["{", "[]", "{\"version\":\"1\"}"]) assert.throws(() => classicV1Envelope.decode(bytes));
});
