// Code generated by rtvbp-spec-gen from the typed protocol specification. DO NOT EDIT.

import assert from "node:assert/strict";
import test from "node:test";

import * as catalog from "../src/generated/zz_generated_babelforcev1_types.ts";

import * as roles from "../src/generated/zz_generated_babelforcev1_roles.ts";
import { ProtocolHandlerError, type HandlerContext } from "../src/protocol.ts";
import { encodeWireJson } from "../src/wire.ts";

const CONTEXT = { signal: new AbortController().signal } as HandlerContext;

test("events/agent.tool.call.json/round_trip", () => {
  const decoded = catalog.decodeAgentToolCallEvent("{\"name\":\"lookup_order\"}");
  assert.equal(catalog.encodeAgentToolCallEvent(decoded), "{\"name\":\"lookup_order\"}");
});

test("events/agent.tool.call.json/construct", () => {
  const constructed: catalog.AgentToolCallEvent = {"name":"lookup_order"};
  assert.equal(catalog.encodeAgentToolCallEvent(constructed), "{\"name\":\"lookup_order\"}");
});

test("events/audio.info.json/round_trip", () => {
  const decoded = catalog.decodeAudioInfoEvent("{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}");
  assert.equal(catalog.encodeAudioInfoEvent(decoded), "{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}");
});

test("events/audio.info.json/construct", () => {
  const constructed: catalog.AudioInfoEvent = {"read":{"bytes":0,"bytes_per_second":0,"bytes_total":0},"write":{"bytes":0,"bytes_per_second":0,"bytes_total":0}};
  assert.equal(catalog.encodeAudioInfoEvent(constructed), "{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}");
});

test("events/audio.speech.started.json/round_trip", () => {
  const decoded = catalog.decodeAudioSpeechStartedEvent("{\"origin\":\"sender\"}");
  assert.equal(catalog.encodeAudioSpeechStartedEvent(decoded), "{\"origin\":\"sender\"}");
});

test("events/audio.speech.started.json/construct", () => {
  const constructed: catalog.AudioSpeechStartedEvent = {"origin":"sender"};
  assert.equal(catalog.encodeAudioSpeechStartedEvent(constructed), "{\"origin\":\"sender\"}");
});

test("events/call.hangup.json/round_trip", () => {
  const decoded = catalog.decodeCallHangupEvent("{\"reason\":\"caller\"}");
  assert.equal(catalog.encodeCallHangupEvent(decoded), "{\"reason\":\"caller\"}");
});

test("events/call.hangup.json/construct", () => {
  const constructed: catalog.CallHangupEvent = {"reason":"caller"};
  assert.equal(catalog.encodeCallHangupEvent(constructed), "{\"reason\":\"caller\"}");
});

test("events/dtmf.json/round_trip", () => {
  const decoded = catalog.decodeDtmfEvent("{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}");
  assert.equal(catalog.encodeDtmfEvent(decoded), "{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}");
});

test("events/dtmf.json/construct", () => {
  const constructed: catalog.DtmfEvent = {"seq":7,"pressed_at":1700000000000,"released_at":1700000000120,"digit":"5"};
  assert.equal(catalog.encodeDtmfEvent(constructed), "{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}");
});

test("events/input.transcript.json/round_trip", () => {
  const decoded = catalog.decodeInputTranscriptEvent("{\"delta\":\"hello there\"}");
  assert.equal(catalog.encodeInputTranscriptEvent(decoded), "{\"delta\":\"hello there\"}");
});

test("events/input.transcript.json/construct", () => {
  const constructed: catalog.InputTranscriptEvent = {"delta":"hello there"};
  assert.equal(catalog.encodeInputTranscriptEvent(constructed), "{\"delta\":\"hello there\"}");
});

test("events/output.transcript.delta.json/round_trip", () => {
  const decoded = catalog.decodeOutputTranscriptDeltaEvent("{\"delta\":\"Hi \"}");
  assert.equal(catalog.encodeOutputTranscriptDeltaEvent(decoded), "{\"delta\":\"Hi \"}");
});

test("events/output.transcript.delta.json/construct", () => {
  const constructed: catalog.OutputTranscriptDeltaEvent = {"delta":"Hi "};
  assert.equal(catalog.encodeOutputTranscriptDeltaEvent(constructed), "{\"delta\":\"Hi \"}");
});

test("events/output.transcript.done.json/round_trip", () => {
  const decoded = catalog.decodeOutputTranscriptDoneEvent("{}");
  assert.equal(catalog.encodeOutputTranscriptDoneEvent(decoded), "{}");
});

test("events/output.transcript.done.json/construct", () => {
  const constructed: catalog.OutputTranscriptDoneEvent = {};
  assert.equal(catalog.encodeOutputTranscriptDoneEvent(constructed), "{}");
});

test("events/session.updated.json/round_trip", () => {
  const decoded = catalog.decodeSessionUpdatedEvent("{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}");
  assert.equal(catalog.encodeSessionUpdatedEvent(decoded), "{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}");
});

test("events/session.updated.json/construct", () => {
  const constructed: catalog.SessionUpdatedEvent = {"audio_codec":{"id":"L16/8000/1","name":"L16","sample_rate":8000,"bit_depth":16,"channels":1}};
  assert.equal(catalog.encodeSessionUpdatedEvent(constructed), "{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}");
});

test("payloads/application.move.request.json/round_trip", () => {
  const decoded = catalog.decodeApplicationMoveRequest("{\"reason\":\"handoff\",\"application_id\":\"app-2\"}");
  assert.equal(catalog.encodeApplicationMoveRequest(decoded), "{\"reason\":\"handoff\",\"application_id\":\"app-2\"}");
});

test("payloads/application.move.request.json/construct", () => {
  const constructed: catalog.ApplicationMoveRequest = {"reason":"handoff","application_id":"app-2"};
  assert.equal(catalog.encodeApplicationMoveRequest(constructed), "{\"reason\":\"handoff\",\"application_id\":\"app-2\"}");
});

test("payloads/application.move.response.json/round_trip", () => {
  const decoded = catalog.decodeApplicationMoveResponse("{\"next_application_id\":\"app-2\"}");
  assert.equal(catalog.encodeApplicationMoveResponse(decoded), "{\"next_application_id\":\"app-2\"}");
});

test("payloads/application.move.response.json/construct", () => {
  const constructed: catalog.ApplicationMoveResponse = {"next_application_id":"app-2"};
  assert.equal(catalog.encodeApplicationMoveResponse(constructed), "{\"next_application_id\":\"app-2\"}");
});

test("payloads/audio.buffer.clear.request.json/round_trip", () => {
  const decoded = catalog.decodeAudioBufferClearRequest("{}");
  assert.equal(catalog.encodeAudioBufferClearRequest(decoded), "{}");
});

test("payloads/audio.buffer.clear.request.json/construct", () => {
  const constructed: catalog.AudioBufferClearRequest = {};
  assert.equal(catalog.encodeAudioBufferClearRequest(constructed), "{}");
});

test("payloads/audio.buffer.clear.response.json/round_trip", () => {
  const decoded = catalog.decodeAudioBufferClearResponse("{\"len\":320}");
  assert.equal(catalog.encodeAudioBufferClearResponse(decoded), "{\"len\":320}");
});

test("payloads/audio.buffer.clear.response.json/construct", () => {
  const constructed: catalog.AudioBufferClearResponse = {"len":320};
  assert.equal(catalog.encodeAudioBufferClearResponse(constructed), "{\"len\":320}");
});

test("payloads/call.hangup.request.json/round_trip", () => {
  const decoded = catalog.decodeCallHangupRequest("{\"reason\":\"caller\"}");
  assert.equal(catalog.encodeCallHangupRequest(decoded), "{\"reason\":\"caller\"}");
});

test("payloads/call.hangup.request.json/construct", () => {
  const constructed: catalog.CallHangupRequest = {"reason":"caller"};
  assert.equal(catalog.encodeCallHangupRequest(constructed), "{\"reason\":\"caller\"}");
});

test("payloads/call.hangup.response.json/round_trip", () => {
  const decoded = catalog.decodeEmptyResponse("{}");
  assert.equal(catalog.encodeEmptyResponse(decoded), "{}");
});

test("payloads/call.hangup.response.json/construct", () => {
  const constructed: catalog.EmptyResponse = {};
  assert.equal(catalog.encodeEmptyResponse(constructed), "{}");
});

test("payloads/ping.request.json/round_trip", () => {
  const decoded = catalog.decodePingRequest("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}");
  assert.equal(catalog.encodePingRequest(decoded), "{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}");
});

test("payloads/ping.request.json/construct", () => {
  const constructed: catalog.PingRequest = {"t0":1700000000000,"rtt":42,"data":{"probe":"canonical"}};
  assert.equal(catalog.encodePingRequest(constructed), "{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}");
});

test("payloads/ping.response.json/round_trip", () => {
  const decoded = catalog.decodePingResponse("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}");
  assert.equal(catalog.encodePingResponse(decoded), "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}");
});

test("payloads/ping.response.json/construct", () => {
  const constructed: catalog.PingResponse = {"t0":1700000000000,"t1":1700000000010,"t2":1700000000012,"owd":5,"data":{"probe":"canonical"}};
  assert.equal(catalog.encodePingResponse(constructed), "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}");
});

test("payloads/recording.start.request.json/round_trip", () => {
  const decoded = catalog.decodeRecordingStartRequest("{\"tags\":[\"support\",\"canonical\"]}");
  assert.equal(catalog.encodeRecordingStartRequest(decoded), "{\"tags\":[\"support\",\"canonical\"]}");
});

test("payloads/recording.start.request.json/construct", () => {
  const constructed: catalog.RecordingStartRequest = {"tags":["support","canonical"]};
  assert.equal(catalog.encodeRecordingStartRequest(constructed), "{\"tags\":[\"support\",\"canonical\"]}");
});

test("payloads/recording.start.response.json/round_trip", () => {
  const decoded = catalog.decodeRecordingStartResponse("{\"id\":\"recording-1\"}");
  assert.equal(catalog.encodeRecordingStartResponse(decoded), "{\"id\":\"recording-1\"}");
});

test("payloads/recording.start.response.json/construct", () => {
  const constructed: catalog.RecordingStartResponse = {"id":"recording-1"};
  assert.equal(catalog.encodeRecordingStartResponse(constructed), "{\"id\":\"recording-1\"}");
});

test("payloads/recording.stop.request.json/round_trip", () => {
  const decoded = catalog.decodeRecordingStopRequest("{\"id\":\"recording-1\"}");
  assert.equal(catalog.encodeRecordingStopRequest(decoded), "{\"id\":\"recording-1\"}");
});

test("payloads/recording.stop.request.json/construct", () => {
  const constructed: catalog.RecordingStopRequest = {"id":"recording-1"};
  assert.equal(catalog.encodeRecordingStopRequest(constructed), "{\"id\":\"recording-1\"}");
});

test("payloads/recording.stop.response.json/round_trip", () => {
  const decoded = catalog.decodeEmptyResponse("{}");
  assert.equal(catalog.encodeEmptyResponse(decoded), "{}");
});

test("payloads/recording.stop.response.json/construct", () => {
  const constructed: catalog.EmptyResponse = {};
  assert.equal(catalog.encodeEmptyResponse(constructed), "{}");
});

test("payloads/session.get.request.json/round_trip", () => {
  const decoded = catalog.decodeSessionGetRequest("{\"keys\":[\"customer\",\"attempt\"]}");
  assert.equal(catalog.encodeSessionGetRequest(decoded), "{\"keys\":[\"customer\",\"attempt\"]}");
});

test("payloads/session.get.request.json/construct", () => {
  const constructed: catalog.SessionGetRequest = {"keys":["customer","attempt"]};
  assert.equal(catalog.encodeSessionGetRequest(constructed), "{\"keys\":[\"customer\",\"attempt\"]}");
});

test("payloads/session.get.response.json/round_trip", () => {
  const decoded = catalog.decodeSessionGetResponse("{\"attempt\":2,\"customer\":\"Ada\"}");
  assert.equal(catalog.encodeSessionGetResponse(decoded), "{\"attempt\":2,\"customer\":\"Ada\"}");
});

test("payloads/session.get.response.json/construct", () => {
  const constructed: catalog.SessionGetResponse = {"attempt":2,"customer":"Ada"};
  assert.equal(catalog.encodeSessionGetResponse(constructed), "{\"attempt\":2,\"customer\":\"Ada\"}");
});

test("payloads/session.initialize.request.json/round_trip", () => {
  const decoded = catalog.decodeSessionInitializeRequest("{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}");
  assert.equal(catalog.encodeSessionInitializeRequest(decoded), "{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}");
});

test("payloads/session.initialize.request.json/construct", () => {
  const constructed: catalog.SessionInitializeRequest = {"application":{"id":"app-1"},"call":{"id":"call-1","session_id":"session-1","from":"+12025550100","to":"+12025550101"},"audio_codec_offerings":[{"id":"L16/8000/1","name":"L16","sample_rate":8000,"bit_depth":16,"channels":1}],"metadata":null};
  assert.equal(catalog.encodeSessionInitializeRequest(constructed), "{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}");
});

test("payloads/session.initialize.response.json/round_trip", () => {
  const decoded = catalog.decodeSessionInitializeResponse("{\"audio_codec\":null}");
  assert.equal(catalog.encodeSessionInitializeResponse(decoded), "{\"audio_codec\":null}");
});

test("payloads/session.initialize.response.json/construct", () => {
  const constructed: catalog.SessionInitializeResponse = {"audio_codec":null};
  assert.equal(catalog.encodeSessionInitializeResponse(constructed), "{\"audio_codec\":null}");
});

test("payloads/session.set.request.json/round_trip", () => {
  const decoded = catalog.decodeSessionSetRequest("{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}");
  assert.equal(catalog.encodeSessionSetRequest(decoded), "{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}");
});

test("payloads/session.set.request.json/construct", () => {
  const constructed: catalog.SessionSetRequest = {"data":{"attempt":2,"customer":"Ada"}};
  assert.equal(catalog.encodeSessionSetRequest(constructed), "{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}");
});

test("payloads/session.set.response.json/round_trip", () => {
  const decoded = catalog.decodeEmptyResponse("{}");
  assert.equal(catalog.encodeEmptyResponse(decoded), "{}");
});

test("payloads/session.set.response.json/construct", () => {
  const constructed: catalog.EmptyResponse = {};
  assert.equal(catalog.encodeEmptyResponse(constructed), "{}");
});

test("payloads/session.terminate.request.json/round_trip", () => {
  const decoded = catalog.decodeSessionTerminateRequest("{\"reason\":\"completed\"}");
  assert.equal(catalog.encodeSessionTerminateRequest(decoded), "{\"reason\":\"completed\"}");
});

test("payloads/session.terminate.request.json/construct", () => {
  const constructed: catalog.SessionTerminateRequest = {"reason":"completed"};
  assert.equal(catalog.encodeSessionTerminateRequest(constructed), "{\"reason\":\"completed\"}");
});

test("payloads/session.terminate.response.json/round_trip", () => {
  const decoded = catalog.decodeEmptyResponse("{}");
  assert.equal(catalog.encodeEmptyResponse(decoded), "{}");
});

test("payloads/session.terminate.response.json/construct", () => {
  const constructed: catalog.EmptyResponse = {};
  assert.equal(catalog.encodeEmptyResponse(constructed), "{}");
});

test("variants/events/audio.info-nonzero.json/round_trip", () => {
  const decoded = catalog.decodeAudioInfoEvent("{\"read\":{\"bytes\":1280,\"bytes_per_second\":12800,\"bytes_total\":6400},\"write\":{\"bytes\":32,\"bytes_per_second\":106.66666666666667,\"bytes_total\":96}}");
  assert.equal(catalog.encodeAudioInfoEvent(decoded), "{\"read\":{\"bytes\":1280,\"bytes_per_second\":12800,\"bytes_total\":6400},\"write\":{\"bytes\":32,\"bytes_per_second\":106.66666666666667,\"bytes_total\":96}}");
});

test("variants/events/audio.info-nonzero.json/construct", () => {
  const constructed: catalog.AudioInfoEvent = {"read":{"bytes":1280,"bytes_per_second":12800,"bytes_total":6400},"write":{"bytes":32,"bytes_per_second":106.66666666666667,"bytes_total":96}};
  assert.equal(catalog.encodeAudioInfoEvent(constructed), "{\"read\":{\"bytes\":1280,\"bytes_per_second\":12800,\"bytes_total\":6400},\"write\":{\"bytes\":32,\"bytes_per_second\":106.66666666666667,\"bytes_total\":96}}");
});

test("variants/events/call.hangup-no-reason.json/round_trip", () => {
  const decoded = catalog.decodeCallHangupEvent("{}");
  assert.equal(catalog.encodeCallHangupEvent(decoded), "{}");
});

test("variants/events/call.hangup-no-reason.json/construct", () => {
  const constructed: catalog.CallHangupEvent = {};
  assert.equal(catalog.encodeCallHangupEvent(constructed), "{}");
});

test("variants/events/output.transcript.done-text-empty.json/round_trip", () => {
  const decoded = catalog.decodeOutputTranscriptDoneEvent("{\"text\":\"\"}");
  assert.equal(catalog.encodeOutputTranscriptDoneEvent(decoded), "{\"text\":\"\"}");
});

test("variants/events/output.transcript.done-text-empty.json/construct", () => {
  const constructed: catalog.OutputTranscriptDoneEvent = {"text":""};
  assert.equal(catalog.encodeOutputTranscriptDoneEvent(constructed), "{\"text\":\"\"}");
});

test("variants/events/output.transcript.done-text.json/round_trip", () => {
  const decoded = catalog.decodeOutputTranscriptDoneEvent("{\"text\":\"Hi there\"}");
  assert.equal(catalog.encodeOutputTranscriptDoneEvent(decoded), "{\"text\":\"Hi there\"}");
});

test("variants/events/output.transcript.done-text.json/construct", () => {
  const constructed: catalog.OutputTranscriptDoneEvent = {"text":"Hi there"};
  assert.equal(catalog.encodeOutputTranscriptDoneEvent(constructed), "{\"text\":\"Hi there\"}");
});

test("variants/payloads/application.move.request-empty.json/round_trip", () => {
  const decoded = catalog.decodeApplicationMoveRequest("{}");
  assert.equal(catalog.encodeApplicationMoveRequest(decoded), "{}");
});

test("variants/payloads/application.move.request-empty.json/construct", () => {
  const constructed: catalog.ApplicationMoveRequest = {};
  assert.equal(catalog.encodeApplicationMoveRequest(constructed), "{}");
});

test("variants/payloads/application.move.response-no-next.json/round_trip", () => {
  const decoded = catalog.decodeApplicationMoveResponse("{}");
  assert.equal(catalog.encodeApplicationMoveResponse(decoded), "{}");
});

test("variants/payloads/application.move.response-no-next.json/construct", () => {
  const constructed: catalog.ApplicationMoveResponse = {};
  assert.equal(catalog.encodeApplicationMoveResponse(constructed), "{}");
});

test("variants/payloads/ping.request-no-optionals.json/round_trip", () => {
  const decoded = catalog.decodePingRequest("{\"t0\":1700000000000}");
  assert.equal(catalog.encodePingRequest(decoded), "{\"t0\":1700000000000}");
});

test("variants/payloads/ping.request-no-optionals.json/construct", () => {
  const constructed: catalog.PingRequest = {"t0":1700000000000};
  assert.equal(catalog.encodePingRequest(constructed), "{\"t0\":1700000000000}");
});

test("variants/payloads/ping.response-no-data.json/round_trip", () => {
  const decoded = catalog.decodePingResponse("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5}");
  assert.equal(catalog.encodePingResponse(decoded), "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5}");
});

test("variants/payloads/ping.response-no-data.json/construct", () => {
  const constructed: catalog.PingResponse = {"t0":1700000000000,"t1":1700000000010,"t2":1700000000012,"owd":5};
  assert.equal(catalog.encodePingResponse(constructed), "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5}");
});

test("variants/payloads/recording.start.request-no-tags.json/round_trip", () => {
  const decoded = catalog.decodeRecordingStartRequest("{}");
  assert.equal(catalog.encodeRecordingStartRequest(decoded), "{}");
});

test("variants/payloads/recording.start.request-no-tags.json/construct", () => {
  const constructed: catalog.RecordingStartRequest = {};
  assert.equal(catalog.encodeRecordingStartRequest(constructed), "{}");
});

test("application.move/request/malformed_json", () => {
  assert.throws(() => catalog.decodeApplicationMoveRequest("{"));
});

test("application.move/response/malformed_json", () => {
  assert.throws(() => catalog.decodeApplicationMoveResponse("{"));
});

test("audio.buffer.clear/request/malformed_json", () => {
  assert.throws(() => catalog.decodeAudioBufferClearRequest("{"));
});

test("audio.buffer.clear/response/malformed_json", () => {
  assert.throws(() => catalog.decodeAudioBufferClearResponse("{"));
});

test("call.hangup/request/malformed_json", () => {
  assert.throws(() => catalog.decodeCallHangupRequest("{"));
});

test("call.hangup/request/reason_min_length", () => {
  assert.throws(() => catalog.decodeCallHangupRequest("{\"reason\":\"\"}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("call.hangup/response/malformed_json", () => {
  assert.throws(() => catalog.decodeEmptyResponse("{"));
});

test("ping/request/malformed_json", () => {
  assert.throws(() => catalog.decodePingRequest("{"));
});

test("ping/request/t0_nonzero", () => {
  assert.throws(() => catalog.decodePingRequest("{\"t0\":0,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("ping/response/malformed_json", () => {
  assert.throws(() => catalog.decodePingResponse("{"));
});

test("ping/response/t0_nonzero", () => {
  assert.throws(() => catalog.decodePingResponse("{\"t0\":0,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("ping/response/t1_nonzero", () => {
  assert.throws(() => catalog.decodePingResponse("{\"t0\":1700000000000,\"t1\":0,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("ping/response/t2_nonzero", () => {
  assert.throws(() => catalog.decodePingResponse("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":0,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("recording.start/request/malformed_json", () => {
  assert.throws(() => catalog.decodeRecordingStartRequest("{"));
});

test("recording.start/response/malformed_json", () => {
  assert.throws(() => catalog.decodeRecordingStartResponse("{"));
});

test("recording.start/response/id_min_length", () => {
  assert.throws(() => catalog.decodeRecordingStartResponse("{\"id\":\"\"}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("recording.stop/request/malformed_json", () => {
  assert.throws(() => catalog.decodeRecordingStopRequest("{"));
});

test("recording.stop/request/id_min_length", () => {
  assert.throws(() => catalog.decodeRecordingStopRequest("{\"id\":\"\"}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("recording.stop/response/malformed_json", () => {
  assert.throws(() => catalog.decodeEmptyResponse("{"));
});

test("session.get/request/malformed_json", () => {
  assert.throws(() => catalog.decodeSessionGetRequest("{"));
});

test("session.get/response/malformed_json", () => {
  assert.throws(() => catalog.decodeSessionGetResponse("{"));
});

test("session.initialize/request/malformed_json", () => {
  assert.throws(() => catalog.decodeSessionInitializeRequest("{"));
});

test("session.initialize/response/malformed_json", () => {
  assert.throws(() => catalog.decodeSessionInitializeResponse("{"));
});

test("session.set/request/malformed_json", () => {
  assert.throws(() => catalog.decodeSessionSetRequest("{"));
});

test("session.set/response/malformed_json", () => {
  assert.throws(() => catalog.decodeEmptyResponse("{"));
});

test("session.terminate/request/malformed_json", () => {
  assert.throws(() => catalog.decodeSessionTerminateRequest("{"));
});

test("session.terminate/request/reason_min_length", () => {
  assert.throws(() => catalog.decodeSessionTerminateRequest("{\"reason\":\"\"}"), (error: unknown) => {
    assert.equal((error as Error).name, "ProtocolValidationError");
    return true;
  });
});

test("session.terminate/response/malformed_json", () => {
  assert.throws(() => catalog.decodeEmptyResponse("{"));
});

test("generated application request adapter preserves payloads and terminal metadata", async () => {
  const handler: roles.ApplicationHandler = {
    ping(_context, request) {
      assert.deepEqual(request, {"t0":1700000000000,"rtt":42,"data":{"probe":"canonical"}});
      return {"t0":1700000000000,"t1":1700000000010,"t2":1700000000012,"owd":5,"data":{"probe":"canonical"}};
    },
    sessionInitialize(_context, request) {
      assert.deepEqual(request, {"application":{"id":"app-1"},"call":{"id":"call-1","session_id":"session-1","from":"+12025550100","to":"+12025550101"},"audio_codec_offerings":[{"id":"L16/8000/1","name":"L16","sample_rate":8000,"bit_depth":16,"channels":1}],"metadata":null});
      return {"audio_codec":null};
    },
    sessionTerminate(_context, request) {
      assert.deepEqual(request, {"reason":"completed"});
      return {};
    },
  };
  const registrations = roles.applicationRequestHandlers(handler);
  assert.deepEqual(
    registrations.map((registration) => [registration.method, registration.terminal]),
    [
      [catalog.METHOD_PING, false],
      [catalog.METHOD_SESSION_INITIALIZE, false],
      [catalog.METHOD_SESSION_TERMINATE, true],
    ],
  );
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_PING)!;
    const reply = await registration.handle(CONTEXT, catalog.decodePingRequest("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}"));
    assert.equal(encodeWireJson(reply), "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_SESSION_INITIALIZE)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeSessionInitializeRequest("{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}"));
    assert.equal(encodeWireJson(reply), "{\"audio_codec\":null}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_SESSION_TERMINATE)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeSessionTerminateRequest("{\"reason\":\"completed\"}"));
    assert.equal(encodeWireJson(reply), "{}");
  }
});

test("generated application peer calls ping", async () => {
  const peer = new roles.ApplicationPeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_PING);
      assert.equal(encodeWireJson(params), "{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}");
      assert.equal(options?.terminal, false);
      return catalog.decodePingResponse("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}");
    },
  });
  assert.deepEqual(await peer.ping({"t0":1700000000000,"rtt":42,"data":{"probe":"canonical"}}), {"t0":1700000000000,"t1":1700000000010,"t2":1700000000012,"owd":5,"data":{"probe":"canonical"}});
});

test("generated application peer calls session.initialize", async () => {
  const peer = new roles.ApplicationPeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_SESSION_INITIALIZE);
      assert.equal(encodeWireJson(params), "{\"application\":{\"id\":\"app-1\"},\"call\":{\"id\":\"call-1\",\"session_id\":\"session-1\",\"from\":\"+12025550100\",\"to\":\"+12025550101\"},\"audio_codec_offerings\":[{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}],\"metadata\":null}");
      assert.equal(options?.terminal, false);
      return catalog.decodeSessionInitializeResponse("{\"audio_codec\":null}");
    },
  });
  assert.deepEqual(await peer.sessionInitialize({"application":{"id":"app-1"},"call":{"id":"call-1","session_id":"session-1","from":"+12025550100","to":"+12025550101"},"audio_codec_offerings":[{"id":"L16/8000/1","name":"L16","sample_rate":8000,"bit_depth":16,"channels":1}],"metadata":null}), {"audio_codec":null});
});

test("generated application peer calls session.terminate", async () => {
  const peer = new roles.ApplicationPeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_SESSION_TERMINATE);
      assert.equal(encodeWireJson(params), "{\"reason\":\"completed\"}");
      assert.equal(options?.terminal, true);
      return catalog.decodeEmptyResponse("{}");
    },
  });
  assert.deepEqual(await peer.sessionTerminate({"reason":"completed"}), {});
});

test("generated application event adapter validates every peer event", async () => {
  const handler: roles.ApplicationEventHandler = {
    audioInfo(_context, event) { assert.deepEqual(event, {"read":{"bytes":0,"bytes_per_second":0,"bytes_total":0},"write":{"bytes":0,"bytes_per_second":0,"bytes_total":0}}); },
    callHangup(_context, event) { assert.deepEqual(event, {"reason":"caller"}); },
    dtmf(_context, event) { assert.deepEqual(event, {"seq":7,"pressed_at":1700000000000,"released_at":1700000000120,"digit":"5"}); },
    sessionUpdated(_context, event) { assert.deepEqual(event, {"audio_codec":{"id":"L16/8000/1","name":"L16","sample_rate":8000,"bit_depth":16,"channels":1}}); },
  };
  const registrations = roles.applicationEventHandlers(handler);
  await registrations.find((candidate) => candidate.event === catalog.EVENT_AUDIO_INFO)!.handle(CONTEXT, catalog.decodeAudioInfoEvent("{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}"));
  await registrations.find((candidate) => candidate.event === catalog.EVENT_CALL_HANGUP)!.handle(CONTEXT, catalog.decodeCallHangupEvent("{\"reason\":\"caller\"}"));
  await registrations.find((candidate) => candidate.event === catalog.EVENT_DTMF)!.handle(CONTEXT, catalog.decodeDtmfEvent("{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}"));
  await registrations.find((candidate) => candidate.event === catalog.EVENT_SESSION_UPDATED)!.handle(CONTEXT, catalog.decodeSessionUpdatedEvent("{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}"));
  const unknown = { request: async () => {}, event: async () => {} };
  assert.equal(roles.applicationAdapter(handler as unknown as roles.ApplicationHandler, handler, unknown).unknown, unknown);
});

test("generated application event emitter sends agent.tool.call", async () => {
  const events = new roles.ApplicationEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_AGENT_TOOL_CALL);
      assert.equal(encodeWireJson(payload), "{\"name\":\"lookup_order\"}");
    },
  });
  await events.agentToolCall({"name":"lookup_order"});
});

test("generated application event emitter sends audio.speech.started", async () => {
  const events = new roles.ApplicationEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_AUDIO_SPEECH_STARTED);
      assert.equal(encodeWireJson(payload), "{\"origin\":\"sender\"}");
    },
  });
  await events.audioSpeechStarted({"origin":"sender"});
});

test("generated application event emitter sends input.transcript", async () => {
  const events = new roles.ApplicationEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_INPUT_TRANSCRIPT);
      assert.equal(encodeWireJson(payload), "{\"delta\":\"hello there\"}");
    },
  });
  await events.inputTranscript({"delta":"hello there"});
});

test("generated application event emitter sends output.transcript.delta", async () => {
  const events = new roles.ApplicationEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_OUTPUT_TRANSCRIPT_DELTA);
      assert.equal(encodeWireJson(payload), "{\"delta\":\"Hi \"}");
    },
  });
  await events.outputTranscriptDelta({"delta":"Hi "});
});

test("generated application event emitter sends output.transcript.done", async () => {
  const events = new roles.ApplicationEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_OUTPUT_TRANSCRIPT_DONE);
      assert.equal(encodeWireJson(payload), "{}");
    },
  });
  await events.outputTranscriptDone({});
});

test("generated voice request adapter preserves payloads and terminal metadata", async () => {
  const handler: roles.VoiceHandler = {
    applicationMove(_context, request) {
      assert.deepEqual(request, {"reason":"handoff","application_id":"app-2"});
      return {"next_application_id":"app-2"};
    },
    audioBufferClear(_context, request) {
      assert.deepEqual(request, {});
      return {"len":320};
    },
    callHangup(_context, request) {
      assert.deepEqual(request, {"reason":"caller"});
      return {};
    },
    ping(_context, request) {
      assert.deepEqual(request, {"t0":1700000000000,"rtt":42,"data":{"probe":"canonical"}});
      return {"t0":1700000000000,"t1":1700000000010,"t2":1700000000012,"owd":5,"data":{"probe":"canonical"}};
    },
    recordingStart(_context, request) {
      assert.deepEqual(request, {"tags":["support","canonical"]});
      return {"id":"recording-1"};
    },
    recordingStop(_context, request) {
      assert.deepEqual(request, {"id":"recording-1"});
      return {};
    },
    sessionGet(_context, request) {
      assert.deepEqual(request, {"keys":["customer","attempt"]});
      return {"attempt":2,"customer":"Ada"};
    },
    sessionSet(_context, request) {
      assert.deepEqual(request, {"data":{"attempt":2,"customer":"Ada"}});
      return {};
    },
  };
  const registrations = roles.voiceRequestHandlers(handler);
  assert.deepEqual(
    registrations.map((registration) => [registration.method, registration.terminal]),
    [
      [catalog.METHOD_APPLICATION_MOVE, true],
      [catalog.METHOD_AUDIO_BUFFER_CLEAR, false],
      [catalog.METHOD_CALL_HANGUP, true],
      [catalog.METHOD_PING, false],
      [catalog.METHOD_RECORDING_START, false],
      [catalog.METHOD_RECORDING_STOP, false],
      [catalog.METHOD_SESSION_GET, false],
      [catalog.METHOD_SESSION_SET, false],
      [catalog.METHOD_SESSION_TERMINATE, false],
    ],
  );
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_APPLICATION_MOVE)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeApplicationMoveRequest("{\"reason\":\"handoff\",\"application_id\":\"app-2\"}"));
    assert.equal(encodeWireJson(reply), "{\"next_application_id\":\"app-2\"}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_AUDIO_BUFFER_CLEAR)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeAudioBufferClearRequest("{}"));
    assert.equal(encodeWireJson(reply), "{\"len\":320}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_CALL_HANGUP)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeCallHangupRequest("{\"reason\":\"caller\"}"));
    assert.equal(encodeWireJson(reply), "{}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_PING)!;
    const reply = await registration.handle(CONTEXT, catalog.decodePingRequest("{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}"));
    assert.equal(encodeWireJson(reply), "{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_RECORDING_START)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeRecordingStartRequest("{\"tags\":[\"support\",\"canonical\"]}"));
    assert.equal(encodeWireJson(reply), "{\"id\":\"recording-1\"}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_RECORDING_STOP)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeRecordingStopRequest("{\"id\":\"recording-1\"}"));
    assert.equal(encodeWireJson(reply), "{}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_SESSION_GET)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeSessionGetRequest("{\"keys\":[\"customer\",\"attempt\"]}"));
    assert.equal(encodeWireJson(reply), "{\"attempt\":2,\"customer\":\"Ada\"}");
  }
  {
    const registration = registrations.find((candidate) => candidate.method === catalog.METHOD_SESSION_SET)!;
    const reply = await registration.handle(CONTEXT, catalog.decodeSessionSetRequest("{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}"));
    assert.equal(encodeWireJson(reply), "{}");
  }
  await assert.rejects(
    registrations.find((candidate) => candidate.method === catalog.METHOD_SESSION_TERMINATE)!.handle(CONTEXT, catalog.decodeSessionTerminateRequest("{\"reason\":\"completed\"}")),
    (error: unknown) => {
      assert.ok(error instanceof ProtocolHandlerError);
      assert.equal(error.wire.code, 501);
      assert.equal(error.wire.message, "session.terminate is not supported. please use application.move or call.hangup instead");
      return true;
    },
  );
});

test("generated voice peer calls application.move", async () => {
  const peer = new roles.VoicePeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_APPLICATION_MOVE);
      assert.equal(encodeWireJson(params), "{\"reason\":\"handoff\",\"application_id\":\"app-2\"}");
      assert.equal(options?.terminal, true);
      return catalog.decodeApplicationMoveResponse("{\"next_application_id\":\"app-2\"}");
    },
  });
  assert.deepEqual(await peer.applicationMove({"reason":"handoff","application_id":"app-2"}), {"next_application_id":"app-2"});
});

test("generated voice peer calls audio.buffer.clear", async () => {
  const peer = new roles.VoicePeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_AUDIO_BUFFER_CLEAR);
      assert.equal(encodeWireJson(params), "{}");
      assert.equal(options?.terminal, false);
      return catalog.decodeAudioBufferClearResponse("{\"len\":320}");
    },
  });
  assert.deepEqual(await peer.audioBufferClear({}), {"len":320});
});

test("generated voice peer calls call.hangup", async () => {
  const peer = new roles.VoicePeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_CALL_HANGUP);
      assert.equal(encodeWireJson(params), "{\"reason\":\"caller\"}");
      assert.equal(options?.terminal, true);
      return catalog.decodeEmptyResponse("{}");
    },
  });
  assert.deepEqual(await peer.callHangup({"reason":"caller"}), {});
});

test("generated voice peer calls ping", async () => {
  const peer = new roles.VoicePeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_PING);
      assert.equal(encodeWireJson(params), "{\"t0\":1700000000000,\"rtt\":42,\"data\":{\"probe\":\"canonical\"}}");
      assert.equal(options?.terminal, false);
      return catalog.decodePingResponse("{\"t0\":1700000000000,\"t1\":1700000000010,\"t2\":1700000000012,\"owd\":5,\"data\":{\"probe\":\"canonical\"}}");
    },
  });
  assert.deepEqual(await peer.ping({"t0":1700000000000,"rtt":42,"data":{"probe":"canonical"}}), {"t0":1700000000000,"t1":1700000000010,"t2":1700000000012,"owd":5,"data":{"probe":"canonical"}});
});

test("generated voice peer calls recording.start", async () => {
  const peer = new roles.VoicePeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_RECORDING_START);
      assert.equal(encodeWireJson(params), "{\"tags\":[\"support\",\"canonical\"]}");
      assert.equal(options?.terminal, false);
      return catalog.decodeRecordingStartResponse("{\"id\":\"recording-1\"}");
    },
  });
  assert.deepEqual(await peer.recordingStart({"tags":["support","canonical"]}), {"id":"recording-1"});
});

test("generated voice peer calls recording.stop", async () => {
  const peer = new roles.VoicePeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_RECORDING_STOP);
      assert.equal(encodeWireJson(params), "{\"id\":\"recording-1\"}");
      assert.equal(options?.terminal, false);
      return catalog.decodeEmptyResponse("{}");
    },
  });
  assert.deepEqual(await peer.recordingStop({"id":"recording-1"}), {});
});

test("generated voice peer calls session.get", async () => {
  const peer = new roles.VoicePeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_SESSION_GET);
      assert.equal(encodeWireJson(params), "{\"keys\":[\"customer\",\"attempt\"]}");
      assert.equal(options?.terminal, false);
      return catalog.decodeSessionGetResponse("{\"attempt\":2,\"customer\":\"Ada\"}");
    },
  });
  assert.deepEqual(await peer.sessionGet({"keys":["customer","attempt"]}), {"attempt":2,"customer":"Ada"});
});

test("generated voice peer calls session.set", async () => {
  const peer = new roles.VoicePeer({
    async request(method, params, options) {
      assert.equal(method, catalog.METHOD_SESSION_SET);
      assert.equal(encodeWireJson(params), "{\"data\":{\"attempt\":2,\"customer\":\"Ada\"}}");
      assert.equal(options?.terminal, false);
      return catalog.decodeEmptyResponse("{}");
    },
  });
  assert.deepEqual(await peer.sessionSet({"data":{"attempt":2,"customer":"Ada"}}), {});
});

test("generated voice event adapter validates every peer event", async () => {
  const handler: roles.VoiceEventHandler = {
    agentToolCall(_context, event) { assert.deepEqual(event, {"name":"lookup_order"}); },
    audioSpeechStarted(_context, event) { assert.deepEqual(event, {"origin":"sender"}); },
    inputTranscript(_context, event) { assert.deepEqual(event, {"delta":"hello there"}); },
    outputTranscriptDelta(_context, event) { assert.deepEqual(event, {"delta":"Hi "}); },
    outputTranscriptDone(_context, event) { assert.deepEqual(event, {}); },
  };
  const registrations = roles.voiceEventHandlers(handler);
  await registrations.find((candidate) => candidate.event === catalog.EVENT_AGENT_TOOL_CALL)!.handle(CONTEXT, catalog.decodeAgentToolCallEvent("{\"name\":\"lookup_order\"}"));
  await registrations.find((candidate) => candidate.event === catalog.EVENT_AUDIO_SPEECH_STARTED)!.handle(CONTEXT, catalog.decodeAudioSpeechStartedEvent("{\"origin\":\"sender\"}"));
  await registrations.find((candidate) => candidate.event === catalog.EVENT_INPUT_TRANSCRIPT)!.handle(CONTEXT, catalog.decodeInputTranscriptEvent("{\"delta\":\"hello there\"}"));
  await registrations.find((candidate) => candidate.event === catalog.EVENT_OUTPUT_TRANSCRIPT_DELTA)!.handle(CONTEXT, catalog.decodeOutputTranscriptDeltaEvent("{\"delta\":\"Hi \"}"));
  await registrations.find((candidate) => candidate.event === catalog.EVENT_OUTPUT_TRANSCRIPT_DONE)!.handle(CONTEXT, catalog.decodeOutputTranscriptDoneEvent("{}"));
  const unknown = { request: async () => {}, event: async () => {} };
  assert.equal(roles.voiceAdapter(handler as unknown as roles.VoiceHandler, handler, unknown).unknown, unknown);
});

test("generated voice event emitter sends audio.info", async () => {
  const events = new roles.VoiceEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_AUDIO_INFO);
      assert.equal(encodeWireJson(payload), "{\"read\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0},\"write\":{\"bytes\":0,\"bytes_per_second\":0,\"bytes_total\":0}}");
    },
  });
  await events.audioInfo({"read":{"bytes":0,"bytes_per_second":0,"bytes_total":0},"write":{"bytes":0,"bytes_per_second":0,"bytes_total":0}});
});

test("generated voice event emitter sends call.hangup", async () => {
  const events = new roles.VoiceEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_CALL_HANGUP);
      assert.equal(encodeWireJson(payload), "{\"reason\":\"caller\"}");
    },
  });
  await events.callHangup({"reason":"caller"});
});

test("generated voice event emitter sends dtmf", async () => {
  const events = new roles.VoiceEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_DTMF);
      assert.equal(encodeWireJson(payload), "{\"seq\":7,\"pressed_at\":1700000000000,\"released_at\":1700000000120,\"digit\":\"5\"}");
    },
  });
  await events.dtmf({"seq":7,"pressed_at":1700000000000,"released_at":1700000000120,"digit":"5"});
});

test("generated voice event emitter sends session.updated", async () => {
  const events = new roles.VoiceEvents({
    async notify(event, payload) {
      assert.equal(event, catalog.EVENT_SESSION_UPDATED);
      assert.equal(encodeWireJson(payload), "{\"audio_codec\":{\"id\":\"L16/8000/1\",\"name\":\"L16\",\"sample_rate\":8000,\"bit_depth\":16,\"channels\":1}}");
    },
  });
  await events.sessionUpdated({"audio_codec":{"id":"L16/8000/1","name":"L16","sample_rate":8000,"bit_depth":16,"channels":1}});
});
