import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Start here",
    },
    {
      type: "category",
      label: "Build",
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/category/build",
        title: "Build with RTVBP",
        description: "Choose an SDK or implement the wire protocol directly.",
      },
      items: [
        "getting-started/typescript",
        "getting-started/go",
        "getting-started/rust",
        "getting-started/protocol",
        "deployments/babelforce-cloud",
      ],
    },
    {
      type: "category",
      label: "Understand",
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/category/understand",
        title: "Understand the protocol",
        description: "Learn the role, layer, profile, and media model before choosing an implementation.",
      },
      items: [
        "concepts",
        "profiles",
        {
          type: "category",
          label: "Transport bindings",
          link: {
            type: "generated-index",
            title: "Transport bindings",
            description: "Bindings that carry RTVBP control frames and media.",
          },
          items: ["transports/websocket", "transports/webrtc-websocket"],
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      link: {
        type: "generated-index",
        slug: "/category/reference",
        title: "Generated protocol reference",
        description: "Spec-generated profiles, catalogs, roles, operations, events, envelopes, and proven flows.",
      },
      items: [
        "reference/profiles/index",
        {type: "autogenerated", dirName: "reference/babelforce.v1"},
        {type: "autogenerated", dirName: "reference/demo.v1"},
      ],
    },
    {
      type: "category",
      label: "Project",
      collapsed: true,
      items: ["releases", "outlook"],
    },
  ],
};

export default sidebars;
